
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  admin_audit_log: 'admin_audit_log',
  agents: 'agents',
  inquiries: 'inquiries',
  kyc_requests: 'kyc_requests',
  notifications: 'notifications',
  owners: 'owners',
  payments: 'payments',
  profiles: 'profiles',
  properties: 'properties',
  property_details: 'property_details',
  property_documents: 'property_documents',
  property_media: 'property_media',
  reviews: 'reviews',
  saved_properties: 'saved_properties',
  users: 'users',
  waitlist: 'waitlist',
  poll_responses: 'poll_responses',
  poll_forms: 'poll_forms',
  poll_questions: 'poll_questions',
  poll_submissions: 'poll_submissions',
  poll_submission_answers: 'poll_submission_answers',
  email_campaigns: 'email_campaigns',
  property_validation_jobs: 'property_validation_jobs',
  referral_events: 'referral_events',
  reward_catalog: 'reward_catalog',
  reward_entitlements: 'reward_entitlements',
  reward_redemptions: 'reward_redemptions',
  waitlist_rank_history: 'waitlist_rank_history'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const Admin_audit_logScalarFieldEnum = {
  id: 'id',
  actor_id: 'actor_id',
  action: 'action',
  target_id: 'target_id',
  metadata: 'metadata',
  created_at: 'created_at'
} as const

export type Admin_audit_logScalarFieldEnum = (typeof Admin_audit_logScalarFieldEnum)[keyof typeof Admin_audit_logScalarFieldEnum]


export const AgentsScalarFieldEnum = {
  id: 'id',
  profile_id: 'profile_id',
  license_number: 'license_number',
  agency_name: 'agency_name',
  specialization: 'specialization',
  phone: 'phone',
  verified: 'verified',
  verification_date: 'verification_date',
  years_experience: 'years_experience',
  bio: 'bio',
  photo_url: 'photo_url',
  rating: 'rating',
  total_sales: 'total_sales',
  total_listings: 'total_listings',
  created_at: 'created_at',
  updated_at: 'updated_at',
  whatsapp: 'whatsapp'
} as const

export type AgentsScalarFieldEnum = (typeof AgentsScalarFieldEnum)[keyof typeof AgentsScalarFieldEnum]


export const InquiriesScalarFieldEnum = {
  id: 'id',
  property_id: 'property_id',
  sender_id: 'sender_id',
  owner_id: 'owner_id',
  message: 'message',
  status: 'status',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type InquiriesScalarFieldEnum = (typeof InquiriesScalarFieldEnum)[keyof typeof InquiriesScalarFieldEnum]


export const Kyc_requestsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  user_type: 'user_type',
  status: 'status',
  kyc_provider: 'kyc_provider',
  kyc_reference_id: 'kyc_reference_id',
  documents: 'documents',
  submitted_at: 'submitted_at',
  approved_at: 'approved_at',
  rejected_at: 'rejected_at',
  rejection_reason: 'rejection_reason',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Kyc_requestsScalarFieldEnum = (typeof Kyc_requestsScalarFieldEnum)[keyof typeof Kyc_requestsScalarFieldEnum]


export const NotificationsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  type: 'type',
  title: 'title',
  message: 'message',
  data: 'data',
  is_read: 'is_read',
  read_at: 'read_at',
  created_at: 'created_at'
} as const

export type NotificationsScalarFieldEnum = (typeof NotificationsScalarFieldEnum)[keyof typeof NotificationsScalarFieldEnum]


export const OwnersScalarFieldEnum = {
  id: 'id',
  profile_id: 'profile_id',
  business_name: 'business_name',
  property_types: 'property_types',
  phone: 'phone',
  verified: 'verified',
  verification_date: 'verification_date',
  years_experience: 'years_experience',
  bio: 'bio',
  photo_url: 'photo_url',
  rating: 'rating',
  total_properties: 'total_properties',
  whatsapp: 'whatsapp',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type OwnersScalarFieldEnum = (typeof OwnersScalarFieldEnum)[keyof typeof OwnersScalarFieldEnum]


export const PaymentsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  property_id: 'property_id',
  amount: 'amount',
  currency: 'currency',
  type: 'type',
  status: 'status',
  transaction_id: 'transaction_id',
  created_at: 'created_at'
} as const

export type PaymentsScalarFieldEnum = (typeof PaymentsScalarFieldEnum)[keyof typeof PaymentsScalarFieldEnum]


export const ProfilesScalarFieldEnum = {
  id: 'id',
  email: 'email',
  full_name: 'full_name',
  avatar_url: 'avatar_url',
  phone: 'phone',
  bio: 'bio',
  created_at: 'created_at',
  updated_at: 'updated_at',
  referral_code: 'referral_code',
  referred_by: 'referred_by',
  referred_by_code: 'referred_by_code',
  referral_count: 'referral_count',
  waitlist_persona: 'waitlist_persona',
  candidate_role: 'candidate_role',
  role_activated_at: 'role_activated_at',
  launch_reward_window_ends_at: 'launch_reward_window_ends_at'
} as const

export type ProfilesScalarFieldEnum = (typeof ProfilesScalarFieldEnum)[keyof typeof ProfilesScalarFieldEnum]


export const PropertiesScalarFieldEnum = {
  id: 'id',
  owner_id: 'owner_id',
  title: 'title',
  description: 'description',
  price: 'price',
  property_type: 'property_type',
  listing_type: 'listing_type',
  address: 'address',
  city: 'city',
  state: 'state',
  postal_code: 'postal_code',
  country: 'country',
  latitude: 'latitude',
  longitude: 'longitude',
  bedrooms: 'bedrooms',
  bathrooms: 'bathrooms',
  square_feet: 'square_feet',
  year_built: 'year_built',
  status: 'status',
  verification_status: 'verification_status',
  created_at: 'created_at',
  updated_at: 'updated_at',
  agent_id: 'agent_id',
  listing_source: 'listing_source',
  price_frequency: 'price_frequency'
} as const

export type PropertiesScalarFieldEnum = (typeof PropertiesScalarFieldEnum)[keyof typeof PropertiesScalarFieldEnum]


export const Property_detailsScalarFieldEnum = {
  id: 'id',
  property_id: 'property_id',
  parking_spaces: 'parking_spaces',
  has_pool: 'has_pool',
  has_garage: 'has_garage',
  has_garden: 'has_garden',
  heating_type: 'heating_type',
  cooling_type: 'cooling_type',
  flooring_type: 'flooring_type',
  roof_type: 'roof_type',
  foundation_type: 'foundation_type',
  created_at: 'created_at',
  updated_at: 'updated_at',
  metadata: 'metadata',
  amenities: 'amenities',
  features: 'features'
} as const

export type Property_detailsScalarFieldEnum = (typeof Property_detailsScalarFieldEnum)[keyof typeof Property_detailsScalarFieldEnum]


export const Property_documentsScalarFieldEnum = {
  id: 'id',
  property_id: 'property_id',
  document_type: 'document_type',
  document_url: 'document_url',
  file_name: 'file_name',
  file_size: 'file_size',
  verification_status: 'verification_status',
  verified_by: 'verified_by',
  verified_at: 'verified_at',
  notes: 'notes',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Property_documentsScalarFieldEnum = (typeof Property_documentsScalarFieldEnum)[keyof typeof Property_documentsScalarFieldEnum]


export const Property_mediaScalarFieldEnum = {
  id: 'id',
  property_id: 'property_id',
  media_type: 'media_type',
  media_url: 'media_url',
  file_name: 'file_name',
  display_order: 'display_order',
  is_featured: 'is_featured',
  created_at: 'created_at'
} as const

export type Property_mediaScalarFieldEnum = (typeof Property_mediaScalarFieldEnum)[keyof typeof Property_mediaScalarFieldEnum]


export const ReviewsScalarFieldEnum = {
  id: 'id',
  property_id: 'property_id',
  reviewer_id: 'reviewer_id',
  target_type: 'target_type',
  rating: 'rating',
  comment: 'comment',
  created_at: 'created_at'
} as const

export type ReviewsScalarFieldEnum = (typeof ReviewsScalarFieldEnum)[keyof typeof ReviewsScalarFieldEnum]


export const Saved_propertiesScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  property_id: 'property_id',
  created_at: 'created_at'
} as const

export type Saved_propertiesScalarFieldEnum = (typeof Saved_propertiesScalarFieldEnum)[keyof typeof Saved_propertiesScalarFieldEnum]


export const UsersScalarFieldEnum = {
  id: 'id',
  email: 'email',
  phone: 'phone',
  full_name: 'full_name',
  avatar_url: 'avatar_url',
  role: 'role',
  is_active: 'is_active',
  metadata: 'metadata',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
} as const

export type UsersScalarFieldEnum = (typeof UsersScalarFieldEnum)[keyof typeof UsersScalarFieldEnum]


export const WaitlistScalarFieldEnum = {
  id: 'id',
  email: 'email',
  first_name: 'first_name',
  last_name: 'last_name',
  phone: 'phone',
  source: 'source',
  status: 'status',
  interests: 'interests',
  location_preference: 'location_preference',
  property_type_preference: 'property_type_preference',
  budget_range: 'budget_range',
  subscribed_at: 'subscribed_at',
  unsubscribed_at: 'unsubscribed_at',
  last_contacted_at: 'last_contacted_at',
  contact_count: 'contact_count',
  referrer_url: 'referrer_url',
  user_agent: 'user_agent',
  ip_address: 'ip_address',
  utm_source: 'utm_source',
  utm_medium: 'utm_medium',
  utm_campaign: 'utm_campaign',
  referral_code: 'referral_code',
  referred_by: 'referred_by',
  referral_count: 'referral_count',
  created_at: 'created_at',
  updated_at: 'updated_at',
  persona: 'persona',
  persona_details: 'persona_details',
  queue_score: 'queue_score',
  queue_rank: 'queue_rank',
  candidate_role: 'candidate_role',
  poll_completion_count: 'poll_completion_count',
  waitlist_reward_eligible: 'waitlist_reward_eligible'
} as const

export type WaitlistScalarFieldEnum = (typeof WaitlistScalarFieldEnum)[keyof typeof WaitlistScalarFieldEnum]


export const Poll_responsesScalarFieldEnum = {
  id: 'id',
  question_key: 'question_key',
  answer: 'answer',
  ref: 'ref',
  ip_address: 'ip_address',
  created_at: 'created_at'
} as const

export type Poll_responsesScalarFieldEnum = (typeof Poll_responsesScalarFieldEnum)[keyof typeof Poll_responsesScalarFieldEnum]


export const Poll_formsScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  title: 'title',
  description: 'description',
  is_active: 'is_active',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Poll_formsScalarFieldEnum = (typeof Poll_formsScalarFieldEnum)[keyof typeof Poll_formsScalarFieldEnum]


export const Poll_questionsScalarFieldEnum = {
  id: 'id',
  form_id: 'form_id',
  question_key: 'question_key',
  segment: 'segment',
  prompt: 'prompt',
  question_type: 'question_type',
  options: 'options',
  is_required: 'is_required',
  display_order: 'display_order',
  show_if: 'show_if',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Poll_questionsScalarFieldEnum = (typeof Poll_questionsScalarFieldEnum)[keyof typeof Poll_questionsScalarFieldEnum]


export const Poll_submissionsScalarFieldEnum = {
  id: 'id',
  form_id: 'form_id',
  segment: 'segment',
  full_name: 'full_name',
  email: 'email',
  opt_in_email_results: 'opt_in_email_results',
  referral_code: 'referral_code',
  source: 'source',
  created_at: 'created_at'
} as const

export type Poll_submissionsScalarFieldEnum = (typeof Poll_submissionsScalarFieldEnum)[keyof typeof Poll_submissionsScalarFieldEnum]


export const Poll_submission_answersScalarFieldEnum = {
  id: 'id',
  submission_id: 'submission_id',
  question_key: 'question_key',
  answer: 'answer',
  created_at: 'created_at'
} as const

export type Poll_submission_answersScalarFieldEnum = (typeof Poll_submission_answersScalarFieldEnum)[keyof typeof Poll_submission_answersScalarFieldEnum]


export const Email_campaignsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  template_name: 'template_name',
  subject: 'subject',
  audience_type: 'audience_type',
  audience_id: 'audience_id',
  audience_filter: 'audience_filter',
  send_mode: 'send_mode',
  status: 'status',
  template_props: 'template_props',
  scheduled_at: 'scheduled_at',
  sent_at: 'sent_at',
  total_recipients: 'total_recipients',
  sent_count: 'sent_count',
  failed_count: 'failed_count',
  resend_id: 'resend_id',
  created_by: 'created_by',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Email_campaignsScalarFieldEnum = (typeof Email_campaignsScalarFieldEnum)[keyof typeof Email_campaignsScalarFieldEnum]


export const Property_validation_jobsScalarFieldEnum = {
  id: 'id',
  property_id: 'property_id',
  job_kind: 'job_kind',
  source: 'source',
  status: 'status',
  attempts: 'attempts',
  retry_count: 'retry_count',
  last_error: 'last_error',
  failure_reason: 'failure_reason',
  final_property_status: 'final_property_status',
  queued_at: 'queued_at',
  started_at: 'started_at',
  finished_at: 'finished_at',
  updated_at: 'updated_at',
  next_retry_at: 'next_retry_at',
  request_payload: 'request_payload',
  result: 'result',
  requested_by: 'requested_by'
} as const

export type Property_validation_jobsScalarFieldEnum = (typeof Property_validation_jobsScalarFieldEnum)[keyof typeof Property_validation_jobsScalarFieldEnum]


export const Referral_eventsScalarFieldEnum = {
  id: 'id',
  referrer_waitlist_id: 'referrer_waitlist_id',
  referrer_profile_id: 'referrer_profile_id',
  referred_waitlist_id: 'referred_waitlist_id',
  referred_profile_id: 'referred_profile_id',
  referral_code: 'referral_code',
  event_type: 'event_type',
  metadata: 'metadata',
  created_at: 'created_at'
} as const

export type Referral_eventsScalarFieldEnum = (typeof Referral_eventsScalarFieldEnum)[keyof typeof Referral_eventsScalarFieldEnum]


export const Reward_catalogScalarFieldEnum = {
  id: 'id',
  key: 'key',
  name: 'name',
  reward_system: 'reward_system',
  description: 'description',
  is_redeemable: 'is_redeemable',
  metadata: 'metadata',
  created_at: 'created_at'
} as const

export type Reward_catalogScalarFieldEnum = (typeof Reward_catalogScalarFieldEnum)[keyof typeof Reward_catalogScalarFieldEnum]


export const Reward_entitlementsScalarFieldEnum = {
  id: 'id',
  user_email: 'user_email',
  waitlist_id: 'waitlist_id',
  profile_id: 'profile_id',
  reward_key: 'reward_key',
  source_event: 'source_event',
  source_referral_count: 'source_referral_count',
  status: 'status',
  granted_at: 'granted_at',
  expires_at: 'expires_at',
  metadata: 'metadata'
} as const

export type Reward_entitlementsScalarFieldEnum = (typeof Reward_entitlementsScalarFieldEnum)[keyof typeof Reward_entitlementsScalarFieldEnum]


export const Reward_redemptionsScalarFieldEnum = {
  id: 'id',
  entitlement_id: 'entitlement_id',
  profile_id: 'profile_id',
  redemption_context: 'redemption_context',
  redemption_reference_id: 'redemption_reference_id',
  redeemed_at: 'redeemed_at',
  metadata: 'metadata'
} as const

export type Reward_redemptionsScalarFieldEnum = (typeof Reward_redemptionsScalarFieldEnum)[keyof typeof Reward_redemptionsScalarFieldEnum]


export const Waitlist_rank_historyScalarFieldEnum = {
  id: 'id',
  waitlist_id: 'waitlist_id',
  rank: 'rank',
  score: 'score',
  reason: 'reason',
  created_at: 'created_at'
} as const

export type Waitlist_rank_historyScalarFieldEnum = (typeof Waitlist_rank_historyScalarFieldEnum)[keyof typeof Waitlist_rank_historyScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

