
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `property_validation_jobs` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model property_validation_jobs
 * 
 */
export type property_validation_jobsModel = runtime.Types.Result.DefaultSelection<Prisma.$property_validation_jobsPayload>

export type AggregateProperty_validation_jobs = {
  _count: Property_validation_jobsCountAggregateOutputType | null
  _avg: Property_validation_jobsAvgAggregateOutputType | null
  _sum: Property_validation_jobsSumAggregateOutputType | null
  _min: Property_validation_jobsMinAggregateOutputType | null
  _max: Property_validation_jobsMaxAggregateOutputType | null
}

export type Property_validation_jobsAvgAggregateOutputType = {
  attempts: number | null
  retry_count: number | null
}

export type Property_validation_jobsSumAggregateOutputType = {
  attempts: number | null
  retry_count: number | null
}

export type Property_validation_jobsMinAggregateOutputType = {
  id: string | null
  property_id: string | null
  job_kind: string | null
  source: string | null
  status: string | null
  attempts: number | null
  retry_count: number | null
  last_error: string | null
  failure_reason: string | null
  final_property_status: string | null
  queued_at: Date | null
  started_at: Date | null
  finished_at: Date | null
  updated_at: Date | null
  next_retry_at: Date | null
  requested_by: string | null
}

export type Property_validation_jobsMaxAggregateOutputType = {
  id: string | null
  property_id: string | null
  job_kind: string | null
  source: string | null
  status: string | null
  attempts: number | null
  retry_count: number | null
  last_error: string | null
  failure_reason: string | null
  final_property_status: string | null
  queued_at: Date | null
  started_at: Date | null
  finished_at: Date | null
  updated_at: Date | null
  next_retry_at: Date | null
  requested_by: string | null
}

export type Property_validation_jobsCountAggregateOutputType = {
  id: number
  property_id: number
  job_kind: number
  source: number
  status: number
  attempts: number
  retry_count: number
  last_error: number
  failure_reason: number
  final_property_status: number
  queued_at: number
  started_at: number
  finished_at: number
  updated_at: number
  next_retry_at: number
  request_payload: number
  result: number
  requested_by: number
  _all: number
}


export type Property_validation_jobsAvgAggregateInputType = {
  attempts?: true
  retry_count?: true
}

export type Property_validation_jobsSumAggregateInputType = {
  attempts?: true
  retry_count?: true
}

export type Property_validation_jobsMinAggregateInputType = {
  id?: true
  property_id?: true
  job_kind?: true
  source?: true
  status?: true
  attempts?: true
  retry_count?: true
  last_error?: true
  failure_reason?: true
  final_property_status?: true
  queued_at?: true
  started_at?: true
  finished_at?: true
  updated_at?: true
  next_retry_at?: true
  requested_by?: true
}

export type Property_validation_jobsMaxAggregateInputType = {
  id?: true
  property_id?: true
  job_kind?: true
  source?: true
  status?: true
  attempts?: true
  retry_count?: true
  last_error?: true
  failure_reason?: true
  final_property_status?: true
  queued_at?: true
  started_at?: true
  finished_at?: true
  updated_at?: true
  next_retry_at?: true
  requested_by?: true
}

export type Property_validation_jobsCountAggregateInputType = {
  id?: true
  property_id?: true
  job_kind?: true
  source?: true
  status?: true
  attempts?: true
  retry_count?: true
  last_error?: true
  failure_reason?: true
  final_property_status?: true
  queued_at?: true
  started_at?: true
  finished_at?: true
  updated_at?: true
  next_retry_at?: true
  request_payload?: true
  result?: true
  requested_by?: true
  _all?: true
}

export type Property_validation_jobsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which property_validation_jobs to aggregate.
   */
  where?: Prisma.property_validation_jobsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of property_validation_jobs to fetch.
   */
  orderBy?: Prisma.property_validation_jobsOrderByWithRelationInput | Prisma.property_validation_jobsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.property_validation_jobsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` property_validation_jobs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` property_validation_jobs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned property_validation_jobs
  **/
  _count?: true | Property_validation_jobsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Property_validation_jobsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Property_validation_jobsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Property_validation_jobsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Property_validation_jobsMaxAggregateInputType
}

export type GetProperty_validation_jobsAggregateType<T extends Property_validation_jobsAggregateArgs> = {
      [P in keyof T & keyof AggregateProperty_validation_jobs]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProperty_validation_jobs[P]>
    : Prisma.GetScalarType<T[P], AggregateProperty_validation_jobs[P]>
}




export type property_validation_jobsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.property_validation_jobsWhereInput
  orderBy?: Prisma.property_validation_jobsOrderByWithAggregationInput | Prisma.property_validation_jobsOrderByWithAggregationInput[]
  by: Prisma.Property_validation_jobsScalarFieldEnum[] | Prisma.Property_validation_jobsScalarFieldEnum
  having?: Prisma.property_validation_jobsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Property_validation_jobsCountAggregateInputType | true
  _avg?: Property_validation_jobsAvgAggregateInputType
  _sum?: Property_validation_jobsSumAggregateInputType
  _min?: Property_validation_jobsMinAggregateInputType
  _max?: Property_validation_jobsMaxAggregateInputType
}

export type Property_validation_jobsGroupByOutputType = {
  id: string
  property_id: string
  job_kind: string
  source: string
  status: string
  attempts: number
  retry_count: number
  last_error: string | null
  failure_reason: string | null
  final_property_status: string | null
  queued_at: Date
  started_at: Date | null
  finished_at: Date | null
  updated_at: Date
  next_retry_at: Date | null
  request_payload: runtime.JsonValue | null
  result: runtime.JsonValue | null
  requested_by: string | null
  _count: Property_validation_jobsCountAggregateOutputType | null
  _avg: Property_validation_jobsAvgAggregateOutputType | null
  _sum: Property_validation_jobsSumAggregateOutputType | null
  _min: Property_validation_jobsMinAggregateOutputType | null
  _max: Property_validation_jobsMaxAggregateOutputType | null
}

export type GetProperty_validation_jobsGroupByPayload<T extends property_validation_jobsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Property_validation_jobsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Property_validation_jobsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Property_validation_jobsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Property_validation_jobsGroupByOutputType[P]>
      }
    >
  >



export type property_validation_jobsWhereInput = {
  AND?: Prisma.property_validation_jobsWhereInput | Prisma.property_validation_jobsWhereInput[]
  OR?: Prisma.property_validation_jobsWhereInput[]
  NOT?: Prisma.property_validation_jobsWhereInput | Prisma.property_validation_jobsWhereInput[]
  id?: Prisma.UuidFilter<"property_validation_jobs"> | string
  property_id?: Prisma.UuidFilter<"property_validation_jobs"> | string
  job_kind?: Prisma.StringFilter<"property_validation_jobs"> | string
  source?: Prisma.StringFilter<"property_validation_jobs"> | string
  status?: Prisma.StringFilter<"property_validation_jobs"> | string
  attempts?: Prisma.IntFilter<"property_validation_jobs"> | number
  retry_count?: Prisma.IntFilter<"property_validation_jobs"> | number
  last_error?: Prisma.StringNullableFilter<"property_validation_jobs"> | string | null
  failure_reason?: Prisma.StringNullableFilter<"property_validation_jobs"> | string | null
  final_property_status?: Prisma.StringNullableFilter<"property_validation_jobs"> | string | null
  queued_at?: Prisma.DateTimeFilter<"property_validation_jobs"> | Date | string
  started_at?: Prisma.DateTimeNullableFilter<"property_validation_jobs"> | Date | string | null
  finished_at?: Prisma.DateTimeNullableFilter<"property_validation_jobs"> | Date | string | null
  updated_at?: Prisma.DateTimeFilter<"property_validation_jobs"> | Date | string
  next_retry_at?: Prisma.DateTimeNullableFilter<"property_validation_jobs"> | Date | string | null
  request_payload?: Prisma.JsonNullableFilter<"property_validation_jobs">
  result?: Prisma.JsonNullableFilter<"property_validation_jobs">
  requested_by?: Prisma.UuidNullableFilter<"property_validation_jobs"> | string | null
  properties?: Prisma.XOR<Prisma.PropertiesScalarRelationFilter, Prisma.propertiesWhereInput>
  users?: Prisma.XOR<Prisma.UsersNullableScalarRelationFilter, Prisma.usersWhereInput> | null
}

export type property_validation_jobsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  property_id?: Prisma.SortOrder
  job_kind?: Prisma.SortOrder
  source?: Prisma.SortOrder
  status?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
  retry_count?: Prisma.SortOrder
  last_error?: Prisma.SortOrderInput | Prisma.SortOrder
  failure_reason?: Prisma.SortOrderInput | Prisma.SortOrder
  final_property_status?: Prisma.SortOrderInput | Prisma.SortOrder
  queued_at?: Prisma.SortOrder
  started_at?: Prisma.SortOrderInput | Prisma.SortOrder
  finished_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  next_retry_at?: Prisma.SortOrderInput | Prisma.SortOrder
  request_payload?: Prisma.SortOrderInput | Prisma.SortOrder
  result?: Prisma.SortOrderInput | Prisma.SortOrder
  requested_by?: Prisma.SortOrderInput | Prisma.SortOrder
  properties?: Prisma.propertiesOrderByWithRelationInput
  users?: Prisma.usersOrderByWithRelationInput
}

export type property_validation_jobsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.property_validation_jobsWhereInput | Prisma.property_validation_jobsWhereInput[]
  OR?: Prisma.property_validation_jobsWhereInput[]
  NOT?: Prisma.property_validation_jobsWhereInput | Prisma.property_validation_jobsWhereInput[]
  property_id?: Prisma.UuidFilter<"property_validation_jobs"> | string
  job_kind?: Prisma.StringFilter<"property_validation_jobs"> | string
  source?: Prisma.StringFilter<"property_validation_jobs"> | string
  status?: Prisma.StringFilter<"property_validation_jobs"> | string
  attempts?: Prisma.IntFilter<"property_validation_jobs"> | number
  retry_count?: Prisma.IntFilter<"property_validation_jobs"> | number
  last_error?: Prisma.StringNullableFilter<"property_validation_jobs"> | string | null
  failure_reason?: Prisma.StringNullableFilter<"property_validation_jobs"> | string | null
  final_property_status?: Prisma.StringNullableFilter<"property_validation_jobs"> | string | null
  queued_at?: Prisma.DateTimeFilter<"property_validation_jobs"> | Date | string
  started_at?: Prisma.DateTimeNullableFilter<"property_validation_jobs"> | Date | string | null
  finished_at?: Prisma.DateTimeNullableFilter<"property_validation_jobs"> | Date | string | null
  updated_at?: Prisma.DateTimeFilter<"property_validation_jobs"> | Date | string
  next_retry_at?: Prisma.DateTimeNullableFilter<"property_validation_jobs"> | Date | string | null
  request_payload?: Prisma.JsonNullableFilter<"property_validation_jobs">
  result?: Prisma.JsonNullableFilter<"property_validation_jobs">
  requested_by?: Prisma.UuidNullableFilter<"property_validation_jobs"> | string | null
  properties?: Prisma.XOR<Prisma.PropertiesScalarRelationFilter, Prisma.propertiesWhereInput>
  users?: Prisma.XOR<Prisma.UsersNullableScalarRelationFilter, Prisma.usersWhereInput> | null
}, "id">

export type property_validation_jobsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  property_id?: Prisma.SortOrder
  job_kind?: Prisma.SortOrder
  source?: Prisma.SortOrder
  status?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
  retry_count?: Prisma.SortOrder
  last_error?: Prisma.SortOrderInput | Prisma.SortOrder
  failure_reason?: Prisma.SortOrderInput | Prisma.SortOrder
  final_property_status?: Prisma.SortOrderInput | Prisma.SortOrder
  queued_at?: Prisma.SortOrder
  started_at?: Prisma.SortOrderInput | Prisma.SortOrder
  finished_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  next_retry_at?: Prisma.SortOrderInput | Prisma.SortOrder
  request_payload?: Prisma.SortOrderInput | Prisma.SortOrder
  result?: Prisma.SortOrderInput | Prisma.SortOrder
  requested_by?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.property_validation_jobsCountOrderByAggregateInput
  _avg?: Prisma.property_validation_jobsAvgOrderByAggregateInput
  _max?: Prisma.property_validation_jobsMaxOrderByAggregateInput
  _min?: Prisma.property_validation_jobsMinOrderByAggregateInput
  _sum?: Prisma.property_validation_jobsSumOrderByAggregateInput
}

export type property_validation_jobsScalarWhereWithAggregatesInput = {
  AND?: Prisma.property_validation_jobsScalarWhereWithAggregatesInput | Prisma.property_validation_jobsScalarWhereWithAggregatesInput[]
  OR?: Prisma.property_validation_jobsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.property_validation_jobsScalarWhereWithAggregatesInput | Prisma.property_validation_jobsScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"property_validation_jobs"> | string
  property_id?: Prisma.UuidWithAggregatesFilter<"property_validation_jobs"> | string
  job_kind?: Prisma.StringWithAggregatesFilter<"property_validation_jobs"> | string
  source?: Prisma.StringWithAggregatesFilter<"property_validation_jobs"> | string
  status?: Prisma.StringWithAggregatesFilter<"property_validation_jobs"> | string
  attempts?: Prisma.IntWithAggregatesFilter<"property_validation_jobs"> | number
  retry_count?: Prisma.IntWithAggregatesFilter<"property_validation_jobs"> | number
  last_error?: Prisma.StringNullableWithAggregatesFilter<"property_validation_jobs"> | string | null
  failure_reason?: Prisma.StringNullableWithAggregatesFilter<"property_validation_jobs"> | string | null
  final_property_status?: Prisma.StringNullableWithAggregatesFilter<"property_validation_jobs"> | string | null
  queued_at?: Prisma.DateTimeWithAggregatesFilter<"property_validation_jobs"> | Date | string
  started_at?: Prisma.DateTimeNullableWithAggregatesFilter<"property_validation_jobs"> | Date | string | null
  finished_at?: Prisma.DateTimeNullableWithAggregatesFilter<"property_validation_jobs"> | Date | string | null
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"property_validation_jobs"> | Date | string
  next_retry_at?: Prisma.DateTimeNullableWithAggregatesFilter<"property_validation_jobs"> | Date | string | null
  request_payload?: Prisma.JsonNullableWithAggregatesFilter<"property_validation_jobs">
  result?: Prisma.JsonNullableWithAggregatesFilter<"property_validation_jobs">
  requested_by?: Prisma.UuidNullableWithAggregatesFilter<"property_validation_jobs"> | string | null
}

export type property_validation_jobsCreateInput = {
  id?: string
  job_kind?: string
  source?: string
  status?: string
  attempts?: number
  retry_count?: number
  last_error?: string | null
  failure_reason?: string | null
  final_property_status?: string | null
  queued_at?: Date | string
  started_at?: Date | string | null
  finished_at?: Date | string | null
  updated_at?: Date | string
  next_retry_at?: Date | string | null
  request_payload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  properties: Prisma.propertiesCreateNestedOneWithoutProperty_validation_jobsInput
  users?: Prisma.usersCreateNestedOneWithoutProperty_validation_jobsInput
}

export type property_validation_jobsUncheckedCreateInput = {
  id?: string
  property_id: string
  job_kind?: string
  source?: string
  status?: string
  attempts?: number
  retry_count?: number
  last_error?: string | null
  failure_reason?: string | null
  final_property_status?: string | null
  queued_at?: Date | string
  started_at?: Date | string | null
  finished_at?: Date | string | null
  updated_at?: Date | string
  next_retry_at?: Date | string | null
  request_payload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  requested_by?: string | null
}

export type property_validation_jobsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  job_kind?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  retry_count?: Prisma.IntFieldUpdateOperationsInput | number
  last_error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  failure_reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  final_property_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  queued_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  started_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  finished_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  next_retry_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  request_payload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  properties?: Prisma.propertiesUpdateOneRequiredWithoutProperty_validation_jobsNestedInput
  users?: Prisma.usersUpdateOneWithoutProperty_validation_jobsNestedInput
}

export type property_validation_jobsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  property_id?: Prisma.StringFieldUpdateOperationsInput | string
  job_kind?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  retry_count?: Prisma.IntFieldUpdateOperationsInput | number
  last_error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  failure_reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  final_property_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  queued_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  started_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  finished_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  next_retry_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  request_payload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  requested_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type property_validation_jobsCreateManyInput = {
  id?: string
  property_id: string
  job_kind?: string
  source?: string
  status?: string
  attempts?: number
  retry_count?: number
  last_error?: string | null
  failure_reason?: string | null
  final_property_status?: string | null
  queued_at?: Date | string
  started_at?: Date | string | null
  finished_at?: Date | string | null
  updated_at?: Date | string
  next_retry_at?: Date | string | null
  request_payload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  requested_by?: string | null
}

export type property_validation_jobsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  job_kind?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  retry_count?: Prisma.IntFieldUpdateOperationsInput | number
  last_error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  failure_reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  final_property_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  queued_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  started_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  finished_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  next_retry_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  request_payload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type property_validation_jobsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  property_id?: Prisma.StringFieldUpdateOperationsInput | string
  job_kind?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  retry_count?: Prisma.IntFieldUpdateOperationsInput | number
  last_error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  failure_reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  final_property_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  queued_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  started_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  finished_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  next_retry_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  request_payload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  requested_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type Property_validation_jobsListRelationFilter = {
  every?: Prisma.property_validation_jobsWhereInput
  some?: Prisma.property_validation_jobsWhereInput
  none?: Prisma.property_validation_jobsWhereInput
}

export type property_validation_jobsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type property_validation_jobsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  property_id?: Prisma.SortOrder
  job_kind?: Prisma.SortOrder
  source?: Prisma.SortOrder
  status?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
  retry_count?: Prisma.SortOrder
  last_error?: Prisma.SortOrder
  failure_reason?: Prisma.SortOrder
  final_property_status?: Prisma.SortOrder
  queued_at?: Prisma.SortOrder
  started_at?: Prisma.SortOrder
  finished_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  next_retry_at?: Prisma.SortOrder
  request_payload?: Prisma.SortOrder
  result?: Prisma.SortOrder
  requested_by?: Prisma.SortOrder
}

export type property_validation_jobsAvgOrderByAggregateInput = {
  attempts?: Prisma.SortOrder
  retry_count?: Prisma.SortOrder
}

export type property_validation_jobsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  property_id?: Prisma.SortOrder
  job_kind?: Prisma.SortOrder
  source?: Prisma.SortOrder
  status?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
  retry_count?: Prisma.SortOrder
  last_error?: Prisma.SortOrder
  failure_reason?: Prisma.SortOrder
  final_property_status?: Prisma.SortOrder
  queued_at?: Prisma.SortOrder
  started_at?: Prisma.SortOrder
  finished_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  next_retry_at?: Prisma.SortOrder
  requested_by?: Prisma.SortOrder
}

export type property_validation_jobsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  property_id?: Prisma.SortOrder
  job_kind?: Prisma.SortOrder
  source?: Prisma.SortOrder
  status?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
  retry_count?: Prisma.SortOrder
  last_error?: Prisma.SortOrder
  failure_reason?: Prisma.SortOrder
  final_property_status?: Prisma.SortOrder
  queued_at?: Prisma.SortOrder
  started_at?: Prisma.SortOrder
  finished_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  next_retry_at?: Prisma.SortOrder
  requested_by?: Prisma.SortOrder
}

export type property_validation_jobsSumOrderByAggregateInput = {
  attempts?: Prisma.SortOrder
  retry_count?: Prisma.SortOrder
}

export type property_validation_jobsCreateNestedManyWithoutPropertiesInput = {
  create?: Prisma.XOR<Prisma.property_validation_jobsCreateWithoutPropertiesInput, Prisma.property_validation_jobsUncheckedCreateWithoutPropertiesInput> | Prisma.property_validation_jobsCreateWithoutPropertiesInput[] | Prisma.property_validation_jobsUncheckedCreateWithoutPropertiesInput[]
  connectOrCreate?: Prisma.property_validation_jobsCreateOrConnectWithoutPropertiesInput | Prisma.property_validation_jobsCreateOrConnectWithoutPropertiesInput[]
  createMany?: Prisma.property_validation_jobsCreateManyPropertiesInputEnvelope
  connect?: Prisma.property_validation_jobsWhereUniqueInput | Prisma.property_validation_jobsWhereUniqueInput[]
}

export type property_validation_jobsUncheckedCreateNestedManyWithoutPropertiesInput = {
  create?: Prisma.XOR<Prisma.property_validation_jobsCreateWithoutPropertiesInput, Prisma.property_validation_jobsUncheckedCreateWithoutPropertiesInput> | Prisma.property_validation_jobsCreateWithoutPropertiesInput[] | Prisma.property_validation_jobsUncheckedCreateWithoutPropertiesInput[]
  connectOrCreate?: Prisma.property_validation_jobsCreateOrConnectWithoutPropertiesInput | Prisma.property_validation_jobsCreateOrConnectWithoutPropertiesInput[]
  createMany?: Prisma.property_validation_jobsCreateManyPropertiesInputEnvelope
  connect?: Prisma.property_validation_jobsWhereUniqueInput | Prisma.property_validation_jobsWhereUniqueInput[]
}

export type property_validation_jobsUpdateManyWithoutPropertiesNestedInput = {
  create?: Prisma.XOR<Prisma.property_validation_jobsCreateWithoutPropertiesInput, Prisma.property_validation_jobsUncheckedCreateWithoutPropertiesInput> | Prisma.property_validation_jobsCreateWithoutPropertiesInput[] | Prisma.property_validation_jobsUncheckedCreateWithoutPropertiesInput[]
  connectOrCreate?: Prisma.property_validation_jobsCreateOrConnectWithoutPropertiesInput | Prisma.property_validation_jobsCreateOrConnectWithoutPropertiesInput[]
  upsert?: Prisma.property_validation_jobsUpsertWithWhereUniqueWithoutPropertiesInput | Prisma.property_validation_jobsUpsertWithWhereUniqueWithoutPropertiesInput[]
  createMany?: Prisma.property_validation_jobsCreateManyPropertiesInputEnvelope
  set?: Prisma.property_validation_jobsWhereUniqueInput | Prisma.property_validation_jobsWhereUniqueInput[]
  disconnect?: Prisma.property_validation_jobsWhereUniqueInput | Prisma.property_validation_jobsWhereUniqueInput[]
  delete?: Prisma.property_validation_jobsWhereUniqueInput | Prisma.property_validation_jobsWhereUniqueInput[]
  connect?: Prisma.property_validation_jobsWhereUniqueInput | Prisma.property_validation_jobsWhereUniqueInput[]
  update?: Prisma.property_validation_jobsUpdateWithWhereUniqueWithoutPropertiesInput | Prisma.property_validation_jobsUpdateWithWhereUniqueWithoutPropertiesInput[]
  updateMany?: Prisma.property_validation_jobsUpdateManyWithWhereWithoutPropertiesInput | Prisma.property_validation_jobsUpdateManyWithWhereWithoutPropertiesInput[]
  deleteMany?: Prisma.property_validation_jobsScalarWhereInput | Prisma.property_validation_jobsScalarWhereInput[]
}

export type property_validation_jobsUncheckedUpdateManyWithoutPropertiesNestedInput = {
  create?: Prisma.XOR<Prisma.property_validation_jobsCreateWithoutPropertiesInput, Prisma.property_validation_jobsUncheckedCreateWithoutPropertiesInput> | Prisma.property_validation_jobsCreateWithoutPropertiesInput[] | Prisma.property_validation_jobsUncheckedCreateWithoutPropertiesInput[]
  connectOrCreate?: Prisma.property_validation_jobsCreateOrConnectWithoutPropertiesInput | Prisma.property_validation_jobsCreateOrConnectWithoutPropertiesInput[]
  upsert?: Prisma.property_validation_jobsUpsertWithWhereUniqueWithoutPropertiesInput | Prisma.property_validation_jobsUpsertWithWhereUniqueWithoutPropertiesInput[]
  createMany?: Prisma.property_validation_jobsCreateManyPropertiesInputEnvelope
  set?: Prisma.property_validation_jobsWhereUniqueInput | Prisma.property_validation_jobsWhereUniqueInput[]
  disconnect?: Prisma.property_validation_jobsWhereUniqueInput | Prisma.property_validation_jobsWhereUniqueInput[]
  delete?: Prisma.property_validation_jobsWhereUniqueInput | Prisma.property_validation_jobsWhereUniqueInput[]
  connect?: Prisma.property_validation_jobsWhereUniqueInput | Prisma.property_validation_jobsWhereUniqueInput[]
  update?: Prisma.property_validation_jobsUpdateWithWhereUniqueWithoutPropertiesInput | Prisma.property_validation_jobsUpdateWithWhereUniqueWithoutPropertiesInput[]
  updateMany?: Prisma.property_validation_jobsUpdateManyWithWhereWithoutPropertiesInput | Prisma.property_validation_jobsUpdateManyWithWhereWithoutPropertiesInput[]
  deleteMany?: Prisma.property_validation_jobsScalarWhereInput | Prisma.property_validation_jobsScalarWhereInput[]
}

export type property_validation_jobsCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.property_validation_jobsCreateWithoutUsersInput, Prisma.property_validation_jobsUncheckedCreateWithoutUsersInput> | Prisma.property_validation_jobsCreateWithoutUsersInput[] | Prisma.property_validation_jobsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.property_validation_jobsCreateOrConnectWithoutUsersInput | Prisma.property_validation_jobsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.property_validation_jobsCreateManyUsersInputEnvelope
  connect?: Prisma.property_validation_jobsWhereUniqueInput | Prisma.property_validation_jobsWhereUniqueInput[]
}

export type property_validation_jobsUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.property_validation_jobsCreateWithoutUsersInput, Prisma.property_validation_jobsUncheckedCreateWithoutUsersInput> | Prisma.property_validation_jobsCreateWithoutUsersInput[] | Prisma.property_validation_jobsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.property_validation_jobsCreateOrConnectWithoutUsersInput | Prisma.property_validation_jobsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.property_validation_jobsCreateManyUsersInputEnvelope
  connect?: Prisma.property_validation_jobsWhereUniqueInput | Prisma.property_validation_jobsWhereUniqueInput[]
}

export type property_validation_jobsUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.property_validation_jobsCreateWithoutUsersInput, Prisma.property_validation_jobsUncheckedCreateWithoutUsersInput> | Prisma.property_validation_jobsCreateWithoutUsersInput[] | Prisma.property_validation_jobsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.property_validation_jobsCreateOrConnectWithoutUsersInput | Prisma.property_validation_jobsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.property_validation_jobsUpsertWithWhereUniqueWithoutUsersInput | Prisma.property_validation_jobsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.property_validation_jobsCreateManyUsersInputEnvelope
  set?: Prisma.property_validation_jobsWhereUniqueInput | Prisma.property_validation_jobsWhereUniqueInput[]
  disconnect?: Prisma.property_validation_jobsWhereUniqueInput | Prisma.property_validation_jobsWhereUniqueInput[]
  delete?: Prisma.property_validation_jobsWhereUniqueInput | Prisma.property_validation_jobsWhereUniqueInput[]
  connect?: Prisma.property_validation_jobsWhereUniqueInput | Prisma.property_validation_jobsWhereUniqueInput[]
  update?: Prisma.property_validation_jobsUpdateWithWhereUniqueWithoutUsersInput | Prisma.property_validation_jobsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.property_validation_jobsUpdateManyWithWhereWithoutUsersInput | Prisma.property_validation_jobsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.property_validation_jobsScalarWhereInput | Prisma.property_validation_jobsScalarWhereInput[]
}

export type property_validation_jobsUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.property_validation_jobsCreateWithoutUsersInput, Prisma.property_validation_jobsUncheckedCreateWithoutUsersInput> | Prisma.property_validation_jobsCreateWithoutUsersInput[] | Prisma.property_validation_jobsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.property_validation_jobsCreateOrConnectWithoutUsersInput | Prisma.property_validation_jobsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.property_validation_jobsUpsertWithWhereUniqueWithoutUsersInput | Prisma.property_validation_jobsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.property_validation_jobsCreateManyUsersInputEnvelope
  set?: Prisma.property_validation_jobsWhereUniqueInput | Prisma.property_validation_jobsWhereUniqueInput[]
  disconnect?: Prisma.property_validation_jobsWhereUniqueInput | Prisma.property_validation_jobsWhereUniqueInput[]
  delete?: Prisma.property_validation_jobsWhereUniqueInput | Prisma.property_validation_jobsWhereUniqueInput[]
  connect?: Prisma.property_validation_jobsWhereUniqueInput | Prisma.property_validation_jobsWhereUniqueInput[]
  update?: Prisma.property_validation_jobsUpdateWithWhereUniqueWithoutUsersInput | Prisma.property_validation_jobsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.property_validation_jobsUpdateManyWithWhereWithoutUsersInput | Prisma.property_validation_jobsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.property_validation_jobsScalarWhereInput | Prisma.property_validation_jobsScalarWhereInput[]
}

export type property_validation_jobsCreateWithoutPropertiesInput = {
  id?: string
  job_kind?: string
  source?: string
  status?: string
  attempts?: number
  retry_count?: number
  last_error?: string | null
  failure_reason?: string | null
  final_property_status?: string | null
  queued_at?: Date | string
  started_at?: Date | string | null
  finished_at?: Date | string | null
  updated_at?: Date | string
  next_retry_at?: Date | string | null
  request_payload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  users?: Prisma.usersCreateNestedOneWithoutProperty_validation_jobsInput
}

export type property_validation_jobsUncheckedCreateWithoutPropertiesInput = {
  id?: string
  job_kind?: string
  source?: string
  status?: string
  attempts?: number
  retry_count?: number
  last_error?: string | null
  failure_reason?: string | null
  final_property_status?: string | null
  queued_at?: Date | string
  started_at?: Date | string | null
  finished_at?: Date | string | null
  updated_at?: Date | string
  next_retry_at?: Date | string | null
  request_payload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  requested_by?: string | null
}

export type property_validation_jobsCreateOrConnectWithoutPropertiesInput = {
  where: Prisma.property_validation_jobsWhereUniqueInput
  create: Prisma.XOR<Prisma.property_validation_jobsCreateWithoutPropertiesInput, Prisma.property_validation_jobsUncheckedCreateWithoutPropertiesInput>
}

export type property_validation_jobsCreateManyPropertiesInputEnvelope = {
  data: Prisma.property_validation_jobsCreateManyPropertiesInput | Prisma.property_validation_jobsCreateManyPropertiesInput[]
  skipDuplicates?: boolean
}

export type property_validation_jobsUpsertWithWhereUniqueWithoutPropertiesInput = {
  where: Prisma.property_validation_jobsWhereUniqueInput
  update: Prisma.XOR<Prisma.property_validation_jobsUpdateWithoutPropertiesInput, Prisma.property_validation_jobsUncheckedUpdateWithoutPropertiesInput>
  create: Prisma.XOR<Prisma.property_validation_jobsCreateWithoutPropertiesInput, Prisma.property_validation_jobsUncheckedCreateWithoutPropertiesInput>
}

export type property_validation_jobsUpdateWithWhereUniqueWithoutPropertiesInput = {
  where: Prisma.property_validation_jobsWhereUniqueInput
  data: Prisma.XOR<Prisma.property_validation_jobsUpdateWithoutPropertiesInput, Prisma.property_validation_jobsUncheckedUpdateWithoutPropertiesInput>
}

export type property_validation_jobsUpdateManyWithWhereWithoutPropertiesInput = {
  where: Prisma.property_validation_jobsScalarWhereInput
  data: Prisma.XOR<Prisma.property_validation_jobsUpdateManyMutationInput, Prisma.property_validation_jobsUncheckedUpdateManyWithoutPropertiesInput>
}

export type property_validation_jobsScalarWhereInput = {
  AND?: Prisma.property_validation_jobsScalarWhereInput | Prisma.property_validation_jobsScalarWhereInput[]
  OR?: Prisma.property_validation_jobsScalarWhereInput[]
  NOT?: Prisma.property_validation_jobsScalarWhereInput | Prisma.property_validation_jobsScalarWhereInput[]
  id?: Prisma.UuidFilter<"property_validation_jobs"> | string
  property_id?: Prisma.UuidFilter<"property_validation_jobs"> | string
  job_kind?: Prisma.StringFilter<"property_validation_jobs"> | string
  source?: Prisma.StringFilter<"property_validation_jobs"> | string
  status?: Prisma.StringFilter<"property_validation_jobs"> | string
  attempts?: Prisma.IntFilter<"property_validation_jobs"> | number
  retry_count?: Prisma.IntFilter<"property_validation_jobs"> | number
  last_error?: Prisma.StringNullableFilter<"property_validation_jobs"> | string | null
  failure_reason?: Prisma.StringNullableFilter<"property_validation_jobs"> | string | null
  final_property_status?: Prisma.StringNullableFilter<"property_validation_jobs"> | string | null
  queued_at?: Prisma.DateTimeFilter<"property_validation_jobs"> | Date | string
  started_at?: Prisma.DateTimeNullableFilter<"property_validation_jobs"> | Date | string | null
  finished_at?: Prisma.DateTimeNullableFilter<"property_validation_jobs"> | Date | string | null
  updated_at?: Prisma.DateTimeFilter<"property_validation_jobs"> | Date | string
  next_retry_at?: Prisma.DateTimeNullableFilter<"property_validation_jobs"> | Date | string | null
  request_payload?: Prisma.JsonNullableFilter<"property_validation_jobs">
  result?: Prisma.JsonNullableFilter<"property_validation_jobs">
  requested_by?: Prisma.UuidNullableFilter<"property_validation_jobs"> | string | null
}

export type property_validation_jobsCreateWithoutUsersInput = {
  id?: string
  job_kind?: string
  source?: string
  status?: string
  attempts?: number
  retry_count?: number
  last_error?: string | null
  failure_reason?: string | null
  final_property_status?: string | null
  queued_at?: Date | string
  started_at?: Date | string | null
  finished_at?: Date | string | null
  updated_at?: Date | string
  next_retry_at?: Date | string | null
  request_payload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  properties: Prisma.propertiesCreateNestedOneWithoutProperty_validation_jobsInput
}

export type property_validation_jobsUncheckedCreateWithoutUsersInput = {
  id?: string
  property_id: string
  job_kind?: string
  source?: string
  status?: string
  attempts?: number
  retry_count?: number
  last_error?: string | null
  failure_reason?: string | null
  final_property_status?: string | null
  queued_at?: Date | string
  started_at?: Date | string | null
  finished_at?: Date | string | null
  updated_at?: Date | string
  next_retry_at?: Date | string | null
  request_payload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type property_validation_jobsCreateOrConnectWithoutUsersInput = {
  where: Prisma.property_validation_jobsWhereUniqueInput
  create: Prisma.XOR<Prisma.property_validation_jobsCreateWithoutUsersInput, Prisma.property_validation_jobsUncheckedCreateWithoutUsersInput>
}

export type property_validation_jobsCreateManyUsersInputEnvelope = {
  data: Prisma.property_validation_jobsCreateManyUsersInput | Prisma.property_validation_jobsCreateManyUsersInput[]
  skipDuplicates?: boolean
}

export type property_validation_jobsUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.property_validation_jobsWhereUniqueInput
  update: Prisma.XOR<Prisma.property_validation_jobsUpdateWithoutUsersInput, Prisma.property_validation_jobsUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.property_validation_jobsCreateWithoutUsersInput, Prisma.property_validation_jobsUncheckedCreateWithoutUsersInput>
}

export type property_validation_jobsUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.property_validation_jobsWhereUniqueInput
  data: Prisma.XOR<Prisma.property_validation_jobsUpdateWithoutUsersInput, Prisma.property_validation_jobsUncheckedUpdateWithoutUsersInput>
}

export type property_validation_jobsUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.property_validation_jobsScalarWhereInput
  data: Prisma.XOR<Prisma.property_validation_jobsUpdateManyMutationInput, Prisma.property_validation_jobsUncheckedUpdateManyWithoutUsersInput>
}

export type property_validation_jobsCreateManyPropertiesInput = {
  id?: string
  job_kind?: string
  source?: string
  status?: string
  attempts?: number
  retry_count?: number
  last_error?: string | null
  failure_reason?: string | null
  final_property_status?: string | null
  queued_at?: Date | string
  started_at?: Date | string | null
  finished_at?: Date | string | null
  updated_at?: Date | string
  next_retry_at?: Date | string | null
  request_payload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  requested_by?: string | null
}

export type property_validation_jobsUpdateWithoutPropertiesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  job_kind?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  retry_count?: Prisma.IntFieldUpdateOperationsInput | number
  last_error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  failure_reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  final_property_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  queued_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  started_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  finished_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  next_retry_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  request_payload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  users?: Prisma.usersUpdateOneWithoutProperty_validation_jobsNestedInput
}

export type property_validation_jobsUncheckedUpdateWithoutPropertiesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  job_kind?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  retry_count?: Prisma.IntFieldUpdateOperationsInput | number
  last_error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  failure_reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  final_property_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  queued_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  started_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  finished_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  next_retry_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  request_payload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  requested_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type property_validation_jobsUncheckedUpdateManyWithoutPropertiesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  job_kind?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  retry_count?: Prisma.IntFieldUpdateOperationsInput | number
  last_error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  failure_reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  final_property_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  queued_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  started_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  finished_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  next_retry_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  request_payload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  requested_by?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type property_validation_jobsCreateManyUsersInput = {
  id?: string
  property_id: string
  job_kind?: string
  source?: string
  status?: string
  attempts?: number
  retry_count?: number
  last_error?: string | null
  failure_reason?: string | null
  final_property_status?: string | null
  queued_at?: Date | string
  started_at?: Date | string | null
  finished_at?: Date | string | null
  updated_at?: Date | string
  next_retry_at?: Date | string | null
  request_payload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type property_validation_jobsUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  job_kind?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  retry_count?: Prisma.IntFieldUpdateOperationsInput | number
  last_error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  failure_reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  final_property_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  queued_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  started_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  finished_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  next_retry_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  request_payload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  properties?: Prisma.propertiesUpdateOneRequiredWithoutProperty_validation_jobsNestedInput
}

export type property_validation_jobsUncheckedUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  property_id?: Prisma.StringFieldUpdateOperationsInput | string
  job_kind?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  retry_count?: Prisma.IntFieldUpdateOperationsInput | number
  last_error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  failure_reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  final_property_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  queued_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  started_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  finished_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  next_retry_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  request_payload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type property_validation_jobsUncheckedUpdateManyWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  property_id?: Prisma.StringFieldUpdateOperationsInput | string
  job_kind?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  retry_count?: Prisma.IntFieldUpdateOperationsInput | number
  last_error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  failure_reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  final_property_status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  queued_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  started_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  finished_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  next_retry_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  request_payload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}



export type property_validation_jobsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  property_id?: boolean
  job_kind?: boolean
  source?: boolean
  status?: boolean
  attempts?: boolean
  retry_count?: boolean
  last_error?: boolean
  failure_reason?: boolean
  final_property_status?: boolean
  queued_at?: boolean
  started_at?: boolean
  finished_at?: boolean
  updated_at?: boolean
  next_retry_at?: boolean
  request_payload?: boolean
  result?: boolean
  requested_by?: boolean
  properties?: boolean | Prisma.propertiesDefaultArgs<ExtArgs>
  users?: boolean | Prisma.property_validation_jobs$usersArgs<ExtArgs>
}, ExtArgs["result"]["property_validation_jobs"]>

export type property_validation_jobsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  property_id?: boolean
  job_kind?: boolean
  source?: boolean
  status?: boolean
  attempts?: boolean
  retry_count?: boolean
  last_error?: boolean
  failure_reason?: boolean
  final_property_status?: boolean
  queued_at?: boolean
  started_at?: boolean
  finished_at?: boolean
  updated_at?: boolean
  next_retry_at?: boolean
  request_payload?: boolean
  result?: boolean
  requested_by?: boolean
  properties?: boolean | Prisma.propertiesDefaultArgs<ExtArgs>
  users?: boolean | Prisma.property_validation_jobs$usersArgs<ExtArgs>
}, ExtArgs["result"]["property_validation_jobs"]>

export type property_validation_jobsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  property_id?: boolean
  job_kind?: boolean
  source?: boolean
  status?: boolean
  attempts?: boolean
  retry_count?: boolean
  last_error?: boolean
  failure_reason?: boolean
  final_property_status?: boolean
  queued_at?: boolean
  started_at?: boolean
  finished_at?: boolean
  updated_at?: boolean
  next_retry_at?: boolean
  request_payload?: boolean
  result?: boolean
  requested_by?: boolean
  properties?: boolean | Prisma.propertiesDefaultArgs<ExtArgs>
  users?: boolean | Prisma.property_validation_jobs$usersArgs<ExtArgs>
}, ExtArgs["result"]["property_validation_jobs"]>

export type property_validation_jobsSelectScalar = {
  id?: boolean
  property_id?: boolean
  job_kind?: boolean
  source?: boolean
  status?: boolean
  attempts?: boolean
  retry_count?: boolean
  last_error?: boolean
  failure_reason?: boolean
  final_property_status?: boolean
  queued_at?: boolean
  started_at?: boolean
  finished_at?: boolean
  updated_at?: boolean
  next_retry_at?: boolean
  request_payload?: boolean
  result?: boolean
  requested_by?: boolean
}

export type property_validation_jobsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "property_id" | "job_kind" | "source" | "status" | "attempts" | "retry_count" | "last_error" | "failure_reason" | "final_property_status" | "queued_at" | "started_at" | "finished_at" | "updated_at" | "next_retry_at" | "request_payload" | "result" | "requested_by", ExtArgs["result"]["property_validation_jobs"]>
export type property_validation_jobsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  properties?: boolean | Prisma.propertiesDefaultArgs<ExtArgs>
  users?: boolean | Prisma.property_validation_jobs$usersArgs<ExtArgs>
}
export type property_validation_jobsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  properties?: boolean | Prisma.propertiesDefaultArgs<ExtArgs>
  users?: boolean | Prisma.property_validation_jobs$usersArgs<ExtArgs>
}
export type property_validation_jobsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  properties?: boolean | Prisma.propertiesDefaultArgs<ExtArgs>
  users?: boolean | Prisma.property_validation_jobs$usersArgs<ExtArgs>
}

export type $property_validation_jobsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "property_validation_jobs"
  objects: {
    properties: Prisma.$propertiesPayload<ExtArgs>
    users: Prisma.$usersPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    property_id: string
    job_kind: string
    source: string
    status: string
    attempts: number
    retry_count: number
    last_error: string | null
    failure_reason: string | null
    final_property_status: string | null
    queued_at: Date
    started_at: Date | null
    finished_at: Date | null
    updated_at: Date
    next_retry_at: Date | null
    request_payload: runtime.JsonValue | null
    result: runtime.JsonValue | null
    requested_by: string | null
  }, ExtArgs["result"]["property_validation_jobs"]>
  composites: {}
}

export type property_validation_jobsGetPayload<S extends boolean | null | undefined | property_validation_jobsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$property_validation_jobsPayload, S>

export type property_validation_jobsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<property_validation_jobsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Property_validation_jobsCountAggregateInputType | true
  }

export interface property_validation_jobsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['property_validation_jobs'], meta: { name: 'property_validation_jobs' } }
  /**
   * Find zero or one Property_validation_jobs that matches the filter.
   * @param {property_validation_jobsFindUniqueArgs} args - Arguments to find a Property_validation_jobs
   * @example
   * // Get one Property_validation_jobs
   * const property_validation_jobs = await prisma.property_validation_jobs.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends property_validation_jobsFindUniqueArgs>(args: Prisma.SelectSubset<T, property_validation_jobsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__property_validation_jobsClient<runtime.Types.Result.GetResult<Prisma.$property_validation_jobsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Property_validation_jobs that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {property_validation_jobsFindUniqueOrThrowArgs} args - Arguments to find a Property_validation_jobs
   * @example
   * // Get one Property_validation_jobs
   * const property_validation_jobs = await prisma.property_validation_jobs.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends property_validation_jobsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, property_validation_jobsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__property_validation_jobsClient<runtime.Types.Result.GetResult<Prisma.$property_validation_jobsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Property_validation_jobs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {property_validation_jobsFindFirstArgs} args - Arguments to find a Property_validation_jobs
   * @example
   * // Get one Property_validation_jobs
   * const property_validation_jobs = await prisma.property_validation_jobs.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends property_validation_jobsFindFirstArgs>(args?: Prisma.SelectSubset<T, property_validation_jobsFindFirstArgs<ExtArgs>>): Prisma.Prisma__property_validation_jobsClient<runtime.Types.Result.GetResult<Prisma.$property_validation_jobsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Property_validation_jobs that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {property_validation_jobsFindFirstOrThrowArgs} args - Arguments to find a Property_validation_jobs
   * @example
   * // Get one Property_validation_jobs
   * const property_validation_jobs = await prisma.property_validation_jobs.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends property_validation_jobsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, property_validation_jobsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__property_validation_jobsClient<runtime.Types.Result.GetResult<Prisma.$property_validation_jobsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Property_validation_jobs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {property_validation_jobsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Property_validation_jobs
   * const property_validation_jobs = await prisma.property_validation_jobs.findMany()
   * 
   * // Get first 10 Property_validation_jobs
   * const property_validation_jobs = await prisma.property_validation_jobs.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const property_validation_jobsWithIdOnly = await prisma.property_validation_jobs.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends property_validation_jobsFindManyArgs>(args?: Prisma.SelectSubset<T, property_validation_jobsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$property_validation_jobsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Property_validation_jobs.
   * @param {property_validation_jobsCreateArgs} args - Arguments to create a Property_validation_jobs.
   * @example
   * // Create one Property_validation_jobs
   * const Property_validation_jobs = await prisma.property_validation_jobs.create({
   *   data: {
   *     // ... data to create a Property_validation_jobs
   *   }
   * })
   * 
   */
  create<T extends property_validation_jobsCreateArgs>(args: Prisma.SelectSubset<T, property_validation_jobsCreateArgs<ExtArgs>>): Prisma.Prisma__property_validation_jobsClient<runtime.Types.Result.GetResult<Prisma.$property_validation_jobsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Property_validation_jobs.
   * @param {property_validation_jobsCreateManyArgs} args - Arguments to create many Property_validation_jobs.
   * @example
   * // Create many Property_validation_jobs
   * const property_validation_jobs = await prisma.property_validation_jobs.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends property_validation_jobsCreateManyArgs>(args?: Prisma.SelectSubset<T, property_validation_jobsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Property_validation_jobs and returns the data saved in the database.
   * @param {property_validation_jobsCreateManyAndReturnArgs} args - Arguments to create many Property_validation_jobs.
   * @example
   * // Create many Property_validation_jobs
   * const property_validation_jobs = await prisma.property_validation_jobs.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Property_validation_jobs and only return the `id`
   * const property_validation_jobsWithIdOnly = await prisma.property_validation_jobs.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends property_validation_jobsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, property_validation_jobsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$property_validation_jobsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Property_validation_jobs.
   * @param {property_validation_jobsDeleteArgs} args - Arguments to delete one Property_validation_jobs.
   * @example
   * // Delete one Property_validation_jobs
   * const Property_validation_jobs = await prisma.property_validation_jobs.delete({
   *   where: {
   *     // ... filter to delete one Property_validation_jobs
   *   }
   * })
   * 
   */
  delete<T extends property_validation_jobsDeleteArgs>(args: Prisma.SelectSubset<T, property_validation_jobsDeleteArgs<ExtArgs>>): Prisma.Prisma__property_validation_jobsClient<runtime.Types.Result.GetResult<Prisma.$property_validation_jobsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Property_validation_jobs.
   * @param {property_validation_jobsUpdateArgs} args - Arguments to update one Property_validation_jobs.
   * @example
   * // Update one Property_validation_jobs
   * const property_validation_jobs = await prisma.property_validation_jobs.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends property_validation_jobsUpdateArgs>(args: Prisma.SelectSubset<T, property_validation_jobsUpdateArgs<ExtArgs>>): Prisma.Prisma__property_validation_jobsClient<runtime.Types.Result.GetResult<Prisma.$property_validation_jobsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Property_validation_jobs.
   * @param {property_validation_jobsDeleteManyArgs} args - Arguments to filter Property_validation_jobs to delete.
   * @example
   * // Delete a few Property_validation_jobs
   * const { count } = await prisma.property_validation_jobs.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends property_validation_jobsDeleteManyArgs>(args?: Prisma.SelectSubset<T, property_validation_jobsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Property_validation_jobs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {property_validation_jobsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Property_validation_jobs
   * const property_validation_jobs = await prisma.property_validation_jobs.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends property_validation_jobsUpdateManyArgs>(args: Prisma.SelectSubset<T, property_validation_jobsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Property_validation_jobs and returns the data updated in the database.
   * @param {property_validation_jobsUpdateManyAndReturnArgs} args - Arguments to update many Property_validation_jobs.
   * @example
   * // Update many Property_validation_jobs
   * const property_validation_jobs = await prisma.property_validation_jobs.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Property_validation_jobs and only return the `id`
   * const property_validation_jobsWithIdOnly = await prisma.property_validation_jobs.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends property_validation_jobsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, property_validation_jobsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$property_validation_jobsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Property_validation_jobs.
   * @param {property_validation_jobsUpsertArgs} args - Arguments to update or create a Property_validation_jobs.
   * @example
   * // Update or create a Property_validation_jobs
   * const property_validation_jobs = await prisma.property_validation_jobs.upsert({
   *   create: {
   *     // ... data to create a Property_validation_jobs
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Property_validation_jobs we want to update
   *   }
   * })
   */
  upsert<T extends property_validation_jobsUpsertArgs>(args: Prisma.SelectSubset<T, property_validation_jobsUpsertArgs<ExtArgs>>): Prisma.Prisma__property_validation_jobsClient<runtime.Types.Result.GetResult<Prisma.$property_validation_jobsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Property_validation_jobs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {property_validation_jobsCountArgs} args - Arguments to filter Property_validation_jobs to count.
   * @example
   * // Count the number of Property_validation_jobs
   * const count = await prisma.property_validation_jobs.count({
   *   where: {
   *     // ... the filter for the Property_validation_jobs we want to count
   *   }
   * })
  **/
  count<T extends property_validation_jobsCountArgs>(
    args?: Prisma.Subset<T, property_validation_jobsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Property_validation_jobsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Property_validation_jobs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Property_validation_jobsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Property_validation_jobsAggregateArgs>(args: Prisma.Subset<T, Property_validation_jobsAggregateArgs>): Prisma.PrismaPromise<GetProperty_validation_jobsAggregateType<T>>

  /**
   * Group by Property_validation_jobs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {property_validation_jobsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends property_validation_jobsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: property_validation_jobsGroupByArgs['orderBy'] }
      : { orderBy?: property_validation_jobsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, property_validation_jobsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProperty_validation_jobsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the property_validation_jobs model
 */
readonly fields: property_validation_jobsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for property_validation_jobs.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__property_validation_jobsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  properties<T extends Prisma.propertiesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.propertiesDefaultArgs<ExtArgs>>): Prisma.Prisma__propertiesClient<runtime.Types.Result.GetResult<Prisma.$propertiesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  users<T extends Prisma.property_validation_jobs$usersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.property_validation_jobs$usersArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the property_validation_jobs model
 */
export interface property_validation_jobsFieldRefs {
  readonly id: Prisma.FieldRef<"property_validation_jobs", 'String'>
  readonly property_id: Prisma.FieldRef<"property_validation_jobs", 'String'>
  readonly job_kind: Prisma.FieldRef<"property_validation_jobs", 'String'>
  readonly source: Prisma.FieldRef<"property_validation_jobs", 'String'>
  readonly status: Prisma.FieldRef<"property_validation_jobs", 'String'>
  readonly attempts: Prisma.FieldRef<"property_validation_jobs", 'Int'>
  readonly retry_count: Prisma.FieldRef<"property_validation_jobs", 'Int'>
  readonly last_error: Prisma.FieldRef<"property_validation_jobs", 'String'>
  readonly failure_reason: Prisma.FieldRef<"property_validation_jobs", 'String'>
  readonly final_property_status: Prisma.FieldRef<"property_validation_jobs", 'String'>
  readonly queued_at: Prisma.FieldRef<"property_validation_jobs", 'DateTime'>
  readonly started_at: Prisma.FieldRef<"property_validation_jobs", 'DateTime'>
  readonly finished_at: Prisma.FieldRef<"property_validation_jobs", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"property_validation_jobs", 'DateTime'>
  readonly next_retry_at: Prisma.FieldRef<"property_validation_jobs", 'DateTime'>
  readonly request_payload: Prisma.FieldRef<"property_validation_jobs", 'Json'>
  readonly result: Prisma.FieldRef<"property_validation_jobs", 'Json'>
  readonly requested_by: Prisma.FieldRef<"property_validation_jobs", 'String'>
}
    

// Custom InputTypes
/**
 * property_validation_jobs findUnique
 */
export type property_validation_jobsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the property_validation_jobs
   */
  select?: Prisma.property_validation_jobsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the property_validation_jobs
   */
  omit?: Prisma.property_validation_jobsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.property_validation_jobsInclude<ExtArgs> | null
  /**
   * Filter, which property_validation_jobs to fetch.
   */
  where: Prisma.property_validation_jobsWhereUniqueInput
}

/**
 * property_validation_jobs findUniqueOrThrow
 */
export type property_validation_jobsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the property_validation_jobs
   */
  select?: Prisma.property_validation_jobsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the property_validation_jobs
   */
  omit?: Prisma.property_validation_jobsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.property_validation_jobsInclude<ExtArgs> | null
  /**
   * Filter, which property_validation_jobs to fetch.
   */
  where: Prisma.property_validation_jobsWhereUniqueInput
}

/**
 * property_validation_jobs findFirst
 */
export type property_validation_jobsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the property_validation_jobs
   */
  select?: Prisma.property_validation_jobsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the property_validation_jobs
   */
  omit?: Prisma.property_validation_jobsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.property_validation_jobsInclude<ExtArgs> | null
  /**
   * Filter, which property_validation_jobs to fetch.
   */
  where?: Prisma.property_validation_jobsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of property_validation_jobs to fetch.
   */
  orderBy?: Prisma.property_validation_jobsOrderByWithRelationInput | Prisma.property_validation_jobsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for property_validation_jobs.
   */
  cursor?: Prisma.property_validation_jobsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` property_validation_jobs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` property_validation_jobs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of property_validation_jobs.
   */
  distinct?: Prisma.Property_validation_jobsScalarFieldEnum | Prisma.Property_validation_jobsScalarFieldEnum[]
}

/**
 * property_validation_jobs findFirstOrThrow
 */
export type property_validation_jobsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the property_validation_jobs
   */
  select?: Prisma.property_validation_jobsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the property_validation_jobs
   */
  omit?: Prisma.property_validation_jobsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.property_validation_jobsInclude<ExtArgs> | null
  /**
   * Filter, which property_validation_jobs to fetch.
   */
  where?: Prisma.property_validation_jobsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of property_validation_jobs to fetch.
   */
  orderBy?: Prisma.property_validation_jobsOrderByWithRelationInput | Prisma.property_validation_jobsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for property_validation_jobs.
   */
  cursor?: Prisma.property_validation_jobsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` property_validation_jobs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` property_validation_jobs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of property_validation_jobs.
   */
  distinct?: Prisma.Property_validation_jobsScalarFieldEnum | Prisma.Property_validation_jobsScalarFieldEnum[]
}

/**
 * property_validation_jobs findMany
 */
export type property_validation_jobsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the property_validation_jobs
   */
  select?: Prisma.property_validation_jobsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the property_validation_jobs
   */
  omit?: Prisma.property_validation_jobsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.property_validation_jobsInclude<ExtArgs> | null
  /**
   * Filter, which property_validation_jobs to fetch.
   */
  where?: Prisma.property_validation_jobsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of property_validation_jobs to fetch.
   */
  orderBy?: Prisma.property_validation_jobsOrderByWithRelationInput | Prisma.property_validation_jobsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing property_validation_jobs.
   */
  cursor?: Prisma.property_validation_jobsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` property_validation_jobs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` property_validation_jobs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of property_validation_jobs.
   */
  distinct?: Prisma.Property_validation_jobsScalarFieldEnum | Prisma.Property_validation_jobsScalarFieldEnum[]
}

/**
 * property_validation_jobs create
 */
export type property_validation_jobsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the property_validation_jobs
   */
  select?: Prisma.property_validation_jobsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the property_validation_jobs
   */
  omit?: Prisma.property_validation_jobsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.property_validation_jobsInclude<ExtArgs> | null
  /**
   * The data needed to create a property_validation_jobs.
   */
  data: Prisma.XOR<Prisma.property_validation_jobsCreateInput, Prisma.property_validation_jobsUncheckedCreateInput>
}

/**
 * property_validation_jobs createMany
 */
export type property_validation_jobsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many property_validation_jobs.
   */
  data: Prisma.property_validation_jobsCreateManyInput | Prisma.property_validation_jobsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * property_validation_jobs createManyAndReturn
 */
export type property_validation_jobsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the property_validation_jobs
   */
  select?: Prisma.property_validation_jobsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the property_validation_jobs
   */
  omit?: Prisma.property_validation_jobsOmit<ExtArgs> | null
  /**
   * The data used to create many property_validation_jobs.
   */
  data: Prisma.property_validation_jobsCreateManyInput | Prisma.property_validation_jobsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.property_validation_jobsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * property_validation_jobs update
 */
export type property_validation_jobsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the property_validation_jobs
   */
  select?: Prisma.property_validation_jobsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the property_validation_jobs
   */
  omit?: Prisma.property_validation_jobsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.property_validation_jobsInclude<ExtArgs> | null
  /**
   * The data needed to update a property_validation_jobs.
   */
  data: Prisma.XOR<Prisma.property_validation_jobsUpdateInput, Prisma.property_validation_jobsUncheckedUpdateInput>
  /**
   * Choose, which property_validation_jobs to update.
   */
  where: Prisma.property_validation_jobsWhereUniqueInput
}

/**
 * property_validation_jobs updateMany
 */
export type property_validation_jobsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update property_validation_jobs.
   */
  data: Prisma.XOR<Prisma.property_validation_jobsUpdateManyMutationInput, Prisma.property_validation_jobsUncheckedUpdateManyInput>
  /**
   * Filter which property_validation_jobs to update
   */
  where?: Prisma.property_validation_jobsWhereInput
  /**
   * Limit how many property_validation_jobs to update.
   */
  limit?: number
}

/**
 * property_validation_jobs updateManyAndReturn
 */
export type property_validation_jobsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the property_validation_jobs
   */
  select?: Prisma.property_validation_jobsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the property_validation_jobs
   */
  omit?: Prisma.property_validation_jobsOmit<ExtArgs> | null
  /**
   * The data used to update property_validation_jobs.
   */
  data: Prisma.XOR<Prisma.property_validation_jobsUpdateManyMutationInput, Prisma.property_validation_jobsUncheckedUpdateManyInput>
  /**
   * Filter which property_validation_jobs to update
   */
  where?: Prisma.property_validation_jobsWhereInput
  /**
   * Limit how many property_validation_jobs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.property_validation_jobsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * property_validation_jobs upsert
 */
export type property_validation_jobsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the property_validation_jobs
   */
  select?: Prisma.property_validation_jobsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the property_validation_jobs
   */
  omit?: Prisma.property_validation_jobsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.property_validation_jobsInclude<ExtArgs> | null
  /**
   * The filter to search for the property_validation_jobs to update in case it exists.
   */
  where: Prisma.property_validation_jobsWhereUniqueInput
  /**
   * In case the property_validation_jobs found by the `where` argument doesn't exist, create a new property_validation_jobs with this data.
   */
  create: Prisma.XOR<Prisma.property_validation_jobsCreateInput, Prisma.property_validation_jobsUncheckedCreateInput>
  /**
   * In case the property_validation_jobs was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.property_validation_jobsUpdateInput, Prisma.property_validation_jobsUncheckedUpdateInput>
}

/**
 * property_validation_jobs delete
 */
export type property_validation_jobsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the property_validation_jobs
   */
  select?: Prisma.property_validation_jobsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the property_validation_jobs
   */
  omit?: Prisma.property_validation_jobsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.property_validation_jobsInclude<ExtArgs> | null
  /**
   * Filter which property_validation_jobs to delete.
   */
  where: Prisma.property_validation_jobsWhereUniqueInput
}

/**
 * property_validation_jobs deleteMany
 */
export type property_validation_jobsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which property_validation_jobs to delete
   */
  where?: Prisma.property_validation_jobsWhereInput
  /**
   * Limit how many property_validation_jobs to delete.
   */
  limit?: number
}

/**
 * property_validation_jobs.users
 */
export type property_validation_jobs$usersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  where?: Prisma.usersWhereInput
}

/**
 * property_validation_jobs without action
 */
export type property_validation_jobsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the property_validation_jobs
   */
  select?: Prisma.property_validation_jobsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the property_validation_jobs
   */
  omit?: Prisma.property_validation_jobsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.property_validation_jobsInclude<ExtArgs> | null
}
