
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `reward_redemptions` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model reward_redemptions
 * This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info.
 */
export type reward_redemptionsModel = runtime.Types.Result.DefaultSelection<Prisma.$reward_redemptionsPayload>

export type AggregateReward_redemptions = {
  _count: Reward_redemptionsCountAggregateOutputType | null
  _min: Reward_redemptionsMinAggregateOutputType | null
  _max: Reward_redemptionsMaxAggregateOutputType | null
}

export type Reward_redemptionsMinAggregateOutputType = {
  id: string | null
  entitlement_id: string | null
  profile_id: string | null
  redemption_context: string | null
  redemption_reference_id: string | null
  redeemed_at: Date | null
}

export type Reward_redemptionsMaxAggregateOutputType = {
  id: string | null
  entitlement_id: string | null
  profile_id: string | null
  redemption_context: string | null
  redemption_reference_id: string | null
  redeemed_at: Date | null
}

export type Reward_redemptionsCountAggregateOutputType = {
  id: number
  entitlement_id: number
  profile_id: number
  redemption_context: number
  redemption_reference_id: number
  redeemed_at: number
  metadata: number
  _all: number
}


export type Reward_redemptionsMinAggregateInputType = {
  id?: true
  entitlement_id?: true
  profile_id?: true
  redemption_context?: true
  redemption_reference_id?: true
  redeemed_at?: true
}

export type Reward_redemptionsMaxAggregateInputType = {
  id?: true
  entitlement_id?: true
  profile_id?: true
  redemption_context?: true
  redemption_reference_id?: true
  redeemed_at?: true
}

export type Reward_redemptionsCountAggregateInputType = {
  id?: true
  entitlement_id?: true
  profile_id?: true
  redemption_context?: true
  redemption_reference_id?: true
  redeemed_at?: true
  metadata?: true
  _all?: true
}

export type Reward_redemptionsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which reward_redemptions to aggregate.
   */
  where?: Prisma.reward_redemptionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of reward_redemptions to fetch.
   */
  orderBy?: Prisma.reward_redemptionsOrderByWithRelationInput | Prisma.reward_redemptionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.reward_redemptionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` reward_redemptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` reward_redemptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned reward_redemptions
  **/
  _count?: true | Reward_redemptionsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Reward_redemptionsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Reward_redemptionsMaxAggregateInputType
}

export type GetReward_redemptionsAggregateType<T extends Reward_redemptionsAggregateArgs> = {
      [P in keyof T & keyof AggregateReward_redemptions]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateReward_redemptions[P]>
    : Prisma.GetScalarType<T[P], AggregateReward_redemptions[P]>
}




export type reward_redemptionsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.reward_redemptionsWhereInput
  orderBy?: Prisma.reward_redemptionsOrderByWithAggregationInput | Prisma.reward_redemptionsOrderByWithAggregationInput[]
  by: Prisma.Reward_redemptionsScalarFieldEnum[] | Prisma.Reward_redemptionsScalarFieldEnum
  having?: Prisma.reward_redemptionsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Reward_redemptionsCountAggregateInputType | true
  _min?: Reward_redemptionsMinAggregateInputType
  _max?: Reward_redemptionsMaxAggregateInputType
}

export type Reward_redemptionsGroupByOutputType = {
  id: string
  entitlement_id: string
  profile_id: string | null
  redemption_context: string
  redemption_reference_id: string | null
  redeemed_at: Date
  metadata: runtime.JsonValue
  _count: Reward_redemptionsCountAggregateOutputType | null
  _min: Reward_redemptionsMinAggregateOutputType | null
  _max: Reward_redemptionsMaxAggregateOutputType | null
}

export type GetReward_redemptionsGroupByPayload<T extends reward_redemptionsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Reward_redemptionsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Reward_redemptionsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Reward_redemptionsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Reward_redemptionsGroupByOutputType[P]>
      }
    >
  >



export type reward_redemptionsWhereInput = {
  AND?: Prisma.reward_redemptionsWhereInput | Prisma.reward_redemptionsWhereInput[]
  OR?: Prisma.reward_redemptionsWhereInput[]
  NOT?: Prisma.reward_redemptionsWhereInput | Prisma.reward_redemptionsWhereInput[]
  id?: Prisma.UuidFilter<"reward_redemptions"> | string
  entitlement_id?: Prisma.UuidFilter<"reward_redemptions"> | string
  profile_id?: Prisma.UuidNullableFilter<"reward_redemptions"> | string | null
  redemption_context?: Prisma.StringFilter<"reward_redemptions"> | string
  redemption_reference_id?: Prisma.StringNullableFilter<"reward_redemptions"> | string | null
  redeemed_at?: Prisma.DateTimeFilter<"reward_redemptions"> | Date | string
  metadata?: Prisma.JsonFilter<"reward_redemptions">
  reward_entitlements?: Prisma.XOR<Prisma.Reward_entitlementsScalarRelationFilter, Prisma.reward_entitlementsWhereInput>
  profiles?: Prisma.XOR<Prisma.ProfilesNullableScalarRelationFilter, Prisma.profilesWhereInput> | null
}

export type reward_redemptionsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  entitlement_id?: Prisma.SortOrder
  profile_id?: Prisma.SortOrderInput | Prisma.SortOrder
  redemption_context?: Prisma.SortOrder
  redemption_reference_id?: Prisma.SortOrderInput | Prisma.SortOrder
  redeemed_at?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  reward_entitlements?: Prisma.reward_entitlementsOrderByWithRelationInput
  profiles?: Prisma.profilesOrderByWithRelationInput
}

export type reward_redemptionsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.reward_redemptionsWhereInput | Prisma.reward_redemptionsWhereInput[]
  OR?: Prisma.reward_redemptionsWhereInput[]
  NOT?: Prisma.reward_redemptionsWhereInput | Prisma.reward_redemptionsWhereInput[]
  entitlement_id?: Prisma.UuidFilter<"reward_redemptions"> | string
  profile_id?: Prisma.UuidNullableFilter<"reward_redemptions"> | string | null
  redemption_context?: Prisma.StringFilter<"reward_redemptions"> | string
  redemption_reference_id?: Prisma.StringNullableFilter<"reward_redemptions"> | string | null
  redeemed_at?: Prisma.DateTimeFilter<"reward_redemptions"> | Date | string
  metadata?: Prisma.JsonFilter<"reward_redemptions">
  reward_entitlements?: Prisma.XOR<Prisma.Reward_entitlementsScalarRelationFilter, Prisma.reward_entitlementsWhereInput>
  profiles?: Prisma.XOR<Prisma.ProfilesNullableScalarRelationFilter, Prisma.profilesWhereInput> | null
}, "id">

export type reward_redemptionsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  entitlement_id?: Prisma.SortOrder
  profile_id?: Prisma.SortOrderInput | Prisma.SortOrder
  redemption_context?: Prisma.SortOrder
  redemption_reference_id?: Prisma.SortOrderInput | Prisma.SortOrder
  redeemed_at?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  _count?: Prisma.reward_redemptionsCountOrderByAggregateInput
  _max?: Prisma.reward_redemptionsMaxOrderByAggregateInput
  _min?: Prisma.reward_redemptionsMinOrderByAggregateInput
}

export type reward_redemptionsScalarWhereWithAggregatesInput = {
  AND?: Prisma.reward_redemptionsScalarWhereWithAggregatesInput | Prisma.reward_redemptionsScalarWhereWithAggregatesInput[]
  OR?: Prisma.reward_redemptionsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.reward_redemptionsScalarWhereWithAggregatesInput | Prisma.reward_redemptionsScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"reward_redemptions"> | string
  entitlement_id?: Prisma.UuidWithAggregatesFilter<"reward_redemptions"> | string
  profile_id?: Prisma.UuidNullableWithAggregatesFilter<"reward_redemptions"> | string | null
  redemption_context?: Prisma.StringWithAggregatesFilter<"reward_redemptions"> | string
  redemption_reference_id?: Prisma.StringNullableWithAggregatesFilter<"reward_redemptions"> | string | null
  redeemed_at?: Prisma.DateTimeWithAggregatesFilter<"reward_redemptions"> | Date | string
  metadata?: Prisma.JsonWithAggregatesFilter<"reward_redemptions">
}

export type reward_redemptionsCreateInput = {
  id?: string
  redemption_context: string
  redemption_reference_id?: string | null
  redeemed_at?: Date | string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  reward_entitlements: Prisma.reward_entitlementsCreateNestedOneWithoutReward_redemptionsInput
  profiles?: Prisma.profilesCreateNestedOneWithoutReward_redemptionsInput
}

export type reward_redemptionsUncheckedCreateInput = {
  id?: string
  entitlement_id: string
  profile_id?: string | null
  redemption_context: string
  redemption_reference_id?: string | null
  redeemed_at?: Date | string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type reward_redemptionsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  redemption_context?: Prisma.StringFieldUpdateOperationsInput | string
  redemption_reference_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redeemed_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  reward_entitlements?: Prisma.reward_entitlementsUpdateOneRequiredWithoutReward_redemptionsNestedInput
  profiles?: Prisma.profilesUpdateOneWithoutReward_redemptionsNestedInput
}

export type reward_redemptionsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entitlement_id?: Prisma.StringFieldUpdateOperationsInput | string
  profile_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redemption_context?: Prisma.StringFieldUpdateOperationsInput | string
  redemption_reference_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redeemed_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type reward_redemptionsCreateManyInput = {
  id?: string
  entitlement_id: string
  profile_id?: string | null
  redemption_context: string
  redemption_reference_id?: string | null
  redeemed_at?: Date | string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type reward_redemptionsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  redemption_context?: Prisma.StringFieldUpdateOperationsInput | string
  redemption_reference_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redeemed_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type reward_redemptionsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entitlement_id?: Prisma.StringFieldUpdateOperationsInput | string
  profile_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redemption_context?: Prisma.StringFieldUpdateOperationsInput | string
  redemption_reference_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redeemed_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type Reward_redemptionsListRelationFilter = {
  every?: Prisma.reward_redemptionsWhereInput
  some?: Prisma.reward_redemptionsWhereInput
  none?: Prisma.reward_redemptionsWhereInput
}

export type reward_redemptionsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type reward_redemptionsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  entitlement_id?: Prisma.SortOrder
  profile_id?: Prisma.SortOrder
  redemption_context?: Prisma.SortOrder
  redemption_reference_id?: Prisma.SortOrder
  redeemed_at?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
}

export type reward_redemptionsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  entitlement_id?: Prisma.SortOrder
  profile_id?: Prisma.SortOrder
  redemption_context?: Prisma.SortOrder
  redemption_reference_id?: Prisma.SortOrder
  redeemed_at?: Prisma.SortOrder
}

export type reward_redemptionsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  entitlement_id?: Prisma.SortOrder
  profile_id?: Prisma.SortOrder
  redemption_context?: Prisma.SortOrder
  redemption_reference_id?: Prisma.SortOrder
  redeemed_at?: Prisma.SortOrder
}

export type reward_redemptionsCreateNestedManyWithoutProfilesInput = {
  create?: Prisma.XOR<Prisma.reward_redemptionsCreateWithoutProfilesInput, Prisma.reward_redemptionsUncheckedCreateWithoutProfilesInput> | Prisma.reward_redemptionsCreateWithoutProfilesInput[] | Prisma.reward_redemptionsUncheckedCreateWithoutProfilesInput[]
  connectOrCreate?: Prisma.reward_redemptionsCreateOrConnectWithoutProfilesInput | Prisma.reward_redemptionsCreateOrConnectWithoutProfilesInput[]
  createMany?: Prisma.reward_redemptionsCreateManyProfilesInputEnvelope
  connect?: Prisma.reward_redemptionsWhereUniqueInput | Prisma.reward_redemptionsWhereUniqueInput[]
}

export type reward_redemptionsUncheckedCreateNestedManyWithoutProfilesInput = {
  create?: Prisma.XOR<Prisma.reward_redemptionsCreateWithoutProfilesInput, Prisma.reward_redemptionsUncheckedCreateWithoutProfilesInput> | Prisma.reward_redemptionsCreateWithoutProfilesInput[] | Prisma.reward_redemptionsUncheckedCreateWithoutProfilesInput[]
  connectOrCreate?: Prisma.reward_redemptionsCreateOrConnectWithoutProfilesInput | Prisma.reward_redemptionsCreateOrConnectWithoutProfilesInput[]
  createMany?: Prisma.reward_redemptionsCreateManyProfilesInputEnvelope
  connect?: Prisma.reward_redemptionsWhereUniqueInput | Prisma.reward_redemptionsWhereUniqueInput[]
}

export type reward_redemptionsUpdateManyWithoutProfilesNestedInput = {
  create?: Prisma.XOR<Prisma.reward_redemptionsCreateWithoutProfilesInput, Prisma.reward_redemptionsUncheckedCreateWithoutProfilesInput> | Prisma.reward_redemptionsCreateWithoutProfilesInput[] | Prisma.reward_redemptionsUncheckedCreateWithoutProfilesInput[]
  connectOrCreate?: Prisma.reward_redemptionsCreateOrConnectWithoutProfilesInput | Prisma.reward_redemptionsCreateOrConnectWithoutProfilesInput[]
  upsert?: Prisma.reward_redemptionsUpsertWithWhereUniqueWithoutProfilesInput | Prisma.reward_redemptionsUpsertWithWhereUniqueWithoutProfilesInput[]
  createMany?: Prisma.reward_redemptionsCreateManyProfilesInputEnvelope
  set?: Prisma.reward_redemptionsWhereUniqueInput | Prisma.reward_redemptionsWhereUniqueInput[]
  disconnect?: Prisma.reward_redemptionsWhereUniqueInput | Prisma.reward_redemptionsWhereUniqueInput[]
  delete?: Prisma.reward_redemptionsWhereUniqueInput | Prisma.reward_redemptionsWhereUniqueInput[]
  connect?: Prisma.reward_redemptionsWhereUniqueInput | Prisma.reward_redemptionsWhereUniqueInput[]
  update?: Prisma.reward_redemptionsUpdateWithWhereUniqueWithoutProfilesInput | Prisma.reward_redemptionsUpdateWithWhereUniqueWithoutProfilesInput[]
  updateMany?: Prisma.reward_redemptionsUpdateManyWithWhereWithoutProfilesInput | Prisma.reward_redemptionsUpdateManyWithWhereWithoutProfilesInput[]
  deleteMany?: Prisma.reward_redemptionsScalarWhereInput | Prisma.reward_redemptionsScalarWhereInput[]
}

export type reward_redemptionsUncheckedUpdateManyWithoutProfilesNestedInput = {
  create?: Prisma.XOR<Prisma.reward_redemptionsCreateWithoutProfilesInput, Prisma.reward_redemptionsUncheckedCreateWithoutProfilesInput> | Prisma.reward_redemptionsCreateWithoutProfilesInput[] | Prisma.reward_redemptionsUncheckedCreateWithoutProfilesInput[]
  connectOrCreate?: Prisma.reward_redemptionsCreateOrConnectWithoutProfilesInput | Prisma.reward_redemptionsCreateOrConnectWithoutProfilesInput[]
  upsert?: Prisma.reward_redemptionsUpsertWithWhereUniqueWithoutProfilesInput | Prisma.reward_redemptionsUpsertWithWhereUniqueWithoutProfilesInput[]
  createMany?: Prisma.reward_redemptionsCreateManyProfilesInputEnvelope
  set?: Prisma.reward_redemptionsWhereUniqueInput | Prisma.reward_redemptionsWhereUniqueInput[]
  disconnect?: Prisma.reward_redemptionsWhereUniqueInput | Prisma.reward_redemptionsWhereUniqueInput[]
  delete?: Prisma.reward_redemptionsWhereUniqueInput | Prisma.reward_redemptionsWhereUniqueInput[]
  connect?: Prisma.reward_redemptionsWhereUniqueInput | Prisma.reward_redemptionsWhereUniqueInput[]
  update?: Prisma.reward_redemptionsUpdateWithWhereUniqueWithoutProfilesInput | Prisma.reward_redemptionsUpdateWithWhereUniqueWithoutProfilesInput[]
  updateMany?: Prisma.reward_redemptionsUpdateManyWithWhereWithoutProfilesInput | Prisma.reward_redemptionsUpdateManyWithWhereWithoutProfilesInput[]
  deleteMany?: Prisma.reward_redemptionsScalarWhereInput | Prisma.reward_redemptionsScalarWhereInput[]
}

export type reward_redemptionsCreateNestedManyWithoutReward_entitlementsInput = {
  create?: Prisma.XOR<Prisma.reward_redemptionsCreateWithoutReward_entitlementsInput, Prisma.reward_redemptionsUncheckedCreateWithoutReward_entitlementsInput> | Prisma.reward_redemptionsCreateWithoutReward_entitlementsInput[] | Prisma.reward_redemptionsUncheckedCreateWithoutReward_entitlementsInput[]
  connectOrCreate?: Prisma.reward_redemptionsCreateOrConnectWithoutReward_entitlementsInput | Prisma.reward_redemptionsCreateOrConnectWithoutReward_entitlementsInput[]
  createMany?: Prisma.reward_redemptionsCreateManyReward_entitlementsInputEnvelope
  connect?: Prisma.reward_redemptionsWhereUniqueInput | Prisma.reward_redemptionsWhereUniqueInput[]
}

export type reward_redemptionsUncheckedCreateNestedManyWithoutReward_entitlementsInput = {
  create?: Prisma.XOR<Prisma.reward_redemptionsCreateWithoutReward_entitlementsInput, Prisma.reward_redemptionsUncheckedCreateWithoutReward_entitlementsInput> | Prisma.reward_redemptionsCreateWithoutReward_entitlementsInput[] | Prisma.reward_redemptionsUncheckedCreateWithoutReward_entitlementsInput[]
  connectOrCreate?: Prisma.reward_redemptionsCreateOrConnectWithoutReward_entitlementsInput | Prisma.reward_redemptionsCreateOrConnectWithoutReward_entitlementsInput[]
  createMany?: Prisma.reward_redemptionsCreateManyReward_entitlementsInputEnvelope
  connect?: Prisma.reward_redemptionsWhereUniqueInput | Prisma.reward_redemptionsWhereUniqueInput[]
}

export type reward_redemptionsUpdateManyWithoutReward_entitlementsNestedInput = {
  create?: Prisma.XOR<Prisma.reward_redemptionsCreateWithoutReward_entitlementsInput, Prisma.reward_redemptionsUncheckedCreateWithoutReward_entitlementsInput> | Prisma.reward_redemptionsCreateWithoutReward_entitlementsInput[] | Prisma.reward_redemptionsUncheckedCreateWithoutReward_entitlementsInput[]
  connectOrCreate?: Prisma.reward_redemptionsCreateOrConnectWithoutReward_entitlementsInput | Prisma.reward_redemptionsCreateOrConnectWithoutReward_entitlementsInput[]
  upsert?: Prisma.reward_redemptionsUpsertWithWhereUniqueWithoutReward_entitlementsInput | Prisma.reward_redemptionsUpsertWithWhereUniqueWithoutReward_entitlementsInput[]
  createMany?: Prisma.reward_redemptionsCreateManyReward_entitlementsInputEnvelope
  set?: Prisma.reward_redemptionsWhereUniqueInput | Prisma.reward_redemptionsWhereUniqueInput[]
  disconnect?: Prisma.reward_redemptionsWhereUniqueInput | Prisma.reward_redemptionsWhereUniqueInput[]
  delete?: Prisma.reward_redemptionsWhereUniqueInput | Prisma.reward_redemptionsWhereUniqueInput[]
  connect?: Prisma.reward_redemptionsWhereUniqueInput | Prisma.reward_redemptionsWhereUniqueInput[]
  update?: Prisma.reward_redemptionsUpdateWithWhereUniqueWithoutReward_entitlementsInput | Prisma.reward_redemptionsUpdateWithWhereUniqueWithoutReward_entitlementsInput[]
  updateMany?: Prisma.reward_redemptionsUpdateManyWithWhereWithoutReward_entitlementsInput | Prisma.reward_redemptionsUpdateManyWithWhereWithoutReward_entitlementsInput[]
  deleteMany?: Prisma.reward_redemptionsScalarWhereInput | Prisma.reward_redemptionsScalarWhereInput[]
}

export type reward_redemptionsUncheckedUpdateManyWithoutReward_entitlementsNestedInput = {
  create?: Prisma.XOR<Prisma.reward_redemptionsCreateWithoutReward_entitlementsInput, Prisma.reward_redemptionsUncheckedCreateWithoutReward_entitlementsInput> | Prisma.reward_redemptionsCreateWithoutReward_entitlementsInput[] | Prisma.reward_redemptionsUncheckedCreateWithoutReward_entitlementsInput[]
  connectOrCreate?: Prisma.reward_redemptionsCreateOrConnectWithoutReward_entitlementsInput | Prisma.reward_redemptionsCreateOrConnectWithoutReward_entitlementsInput[]
  upsert?: Prisma.reward_redemptionsUpsertWithWhereUniqueWithoutReward_entitlementsInput | Prisma.reward_redemptionsUpsertWithWhereUniqueWithoutReward_entitlementsInput[]
  createMany?: Prisma.reward_redemptionsCreateManyReward_entitlementsInputEnvelope
  set?: Prisma.reward_redemptionsWhereUniqueInput | Prisma.reward_redemptionsWhereUniqueInput[]
  disconnect?: Prisma.reward_redemptionsWhereUniqueInput | Prisma.reward_redemptionsWhereUniqueInput[]
  delete?: Prisma.reward_redemptionsWhereUniqueInput | Prisma.reward_redemptionsWhereUniqueInput[]
  connect?: Prisma.reward_redemptionsWhereUniqueInput | Prisma.reward_redemptionsWhereUniqueInput[]
  update?: Prisma.reward_redemptionsUpdateWithWhereUniqueWithoutReward_entitlementsInput | Prisma.reward_redemptionsUpdateWithWhereUniqueWithoutReward_entitlementsInput[]
  updateMany?: Prisma.reward_redemptionsUpdateManyWithWhereWithoutReward_entitlementsInput | Prisma.reward_redemptionsUpdateManyWithWhereWithoutReward_entitlementsInput[]
  deleteMany?: Prisma.reward_redemptionsScalarWhereInput | Prisma.reward_redemptionsScalarWhereInput[]
}

export type reward_redemptionsCreateWithoutProfilesInput = {
  id?: string
  redemption_context: string
  redemption_reference_id?: string | null
  redeemed_at?: Date | string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  reward_entitlements: Prisma.reward_entitlementsCreateNestedOneWithoutReward_redemptionsInput
}

export type reward_redemptionsUncheckedCreateWithoutProfilesInput = {
  id?: string
  entitlement_id: string
  redemption_context: string
  redemption_reference_id?: string | null
  redeemed_at?: Date | string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type reward_redemptionsCreateOrConnectWithoutProfilesInput = {
  where: Prisma.reward_redemptionsWhereUniqueInput
  create: Prisma.XOR<Prisma.reward_redemptionsCreateWithoutProfilesInput, Prisma.reward_redemptionsUncheckedCreateWithoutProfilesInput>
}

export type reward_redemptionsCreateManyProfilesInputEnvelope = {
  data: Prisma.reward_redemptionsCreateManyProfilesInput | Prisma.reward_redemptionsCreateManyProfilesInput[]
  skipDuplicates?: boolean
}

export type reward_redemptionsUpsertWithWhereUniqueWithoutProfilesInput = {
  where: Prisma.reward_redemptionsWhereUniqueInput
  update: Prisma.XOR<Prisma.reward_redemptionsUpdateWithoutProfilesInput, Prisma.reward_redemptionsUncheckedUpdateWithoutProfilesInput>
  create: Prisma.XOR<Prisma.reward_redemptionsCreateWithoutProfilesInput, Prisma.reward_redemptionsUncheckedCreateWithoutProfilesInput>
}

export type reward_redemptionsUpdateWithWhereUniqueWithoutProfilesInput = {
  where: Prisma.reward_redemptionsWhereUniqueInput
  data: Prisma.XOR<Prisma.reward_redemptionsUpdateWithoutProfilesInput, Prisma.reward_redemptionsUncheckedUpdateWithoutProfilesInput>
}

export type reward_redemptionsUpdateManyWithWhereWithoutProfilesInput = {
  where: Prisma.reward_redemptionsScalarWhereInput
  data: Prisma.XOR<Prisma.reward_redemptionsUpdateManyMutationInput, Prisma.reward_redemptionsUncheckedUpdateManyWithoutProfilesInput>
}

export type reward_redemptionsScalarWhereInput = {
  AND?: Prisma.reward_redemptionsScalarWhereInput | Prisma.reward_redemptionsScalarWhereInput[]
  OR?: Prisma.reward_redemptionsScalarWhereInput[]
  NOT?: Prisma.reward_redemptionsScalarWhereInput | Prisma.reward_redemptionsScalarWhereInput[]
  id?: Prisma.UuidFilter<"reward_redemptions"> | string
  entitlement_id?: Prisma.UuidFilter<"reward_redemptions"> | string
  profile_id?: Prisma.UuidNullableFilter<"reward_redemptions"> | string | null
  redemption_context?: Prisma.StringFilter<"reward_redemptions"> | string
  redemption_reference_id?: Prisma.StringNullableFilter<"reward_redemptions"> | string | null
  redeemed_at?: Prisma.DateTimeFilter<"reward_redemptions"> | Date | string
  metadata?: Prisma.JsonFilter<"reward_redemptions">
}

export type reward_redemptionsCreateWithoutReward_entitlementsInput = {
  id?: string
  redemption_context: string
  redemption_reference_id?: string | null
  redeemed_at?: Date | string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  profiles?: Prisma.profilesCreateNestedOneWithoutReward_redemptionsInput
}

export type reward_redemptionsUncheckedCreateWithoutReward_entitlementsInput = {
  id?: string
  profile_id?: string | null
  redemption_context: string
  redemption_reference_id?: string | null
  redeemed_at?: Date | string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type reward_redemptionsCreateOrConnectWithoutReward_entitlementsInput = {
  where: Prisma.reward_redemptionsWhereUniqueInput
  create: Prisma.XOR<Prisma.reward_redemptionsCreateWithoutReward_entitlementsInput, Prisma.reward_redemptionsUncheckedCreateWithoutReward_entitlementsInput>
}

export type reward_redemptionsCreateManyReward_entitlementsInputEnvelope = {
  data: Prisma.reward_redemptionsCreateManyReward_entitlementsInput | Prisma.reward_redemptionsCreateManyReward_entitlementsInput[]
  skipDuplicates?: boolean
}

export type reward_redemptionsUpsertWithWhereUniqueWithoutReward_entitlementsInput = {
  where: Prisma.reward_redemptionsWhereUniqueInput
  update: Prisma.XOR<Prisma.reward_redemptionsUpdateWithoutReward_entitlementsInput, Prisma.reward_redemptionsUncheckedUpdateWithoutReward_entitlementsInput>
  create: Prisma.XOR<Prisma.reward_redemptionsCreateWithoutReward_entitlementsInput, Prisma.reward_redemptionsUncheckedCreateWithoutReward_entitlementsInput>
}

export type reward_redemptionsUpdateWithWhereUniqueWithoutReward_entitlementsInput = {
  where: Prisma.reward_redemptionsWhereUniqueInput
  data: Prisma.XOR<Prisma.reward_redemptionsUpdateWithoutReward_entitlementsInput, Prisma.reward_redemptionsUncheckedUpdateWithoutReward_entitlementsInput>
}

export type reward_redemptionsUpdateManyWithWhereWithoutReward_entitlementsInput = {
  where: Prisma.reward_redemptionsScalarWhereInput
  data: Prisma.XOR<Prisma.reward_redemptionsUpdateManyMutationInput, Prisma.reward_redemptionsUncheckedUpdateManyWithoutReward_entitlementsInput>
}

export type reward_redemptionsCreateManyProfilesInput = {
  id?: string
  entitlement_id: string
  redemption_context: string
  redemption_reference_id?: string | null
  redeemed_at?: Date | string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type reward_redemptionsUpdateWithoutProfilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  redemption_context?: Prisma.StringFieldUpdateOperationsInput | string
  redemption_reference_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redeemed_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  reward_entitlements?: Prisma.reward_entitlementsUpdateOneRequiredWithoutReward_redemptionsNestedInput
}

export type reward_redemptionsUncheckedUpdateWithoutProfilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entitlement_id?: Prisma.StringFieldUpdateOperationsInput | string
  redemption_context?: Prisma.StringFieldUpdateOperationsInput | string
  redemption_reference_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redeemed_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type reward_redemptionsUncheckedUpdateManyWithoutProfilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entitlement_id?: Prisma.StringFieldUpdateOperationsInput | string
  redemption_context?: Prisma.StringFieldUpdateOperationsInput | string
  redemption_reference_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redeemed_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type reward_redemptionsCreateManyReward_entitlementsInput = {
  id?: string
  profile_id?: string | null
  redemption_context: string
  redemption_reference_id?: string | null
  redeemed_at?: Date | string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type reward_redemptionsUpdateWithoutReward_entitlementsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  redemption_context?: Prisma.StringFieldUpdateOperationsInput | string
  redemption_reference_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redeemed_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  profiles?: Prisma.profilesUpdateOneWithoutReward_redemptionsNestedInput
}

export type reward_redemptionsUncheckedUpdateWithoutReward_entitlementsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  profile_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redemption_context?: Prisma.StringFieldUpdateOperationsInput | string
  redemption_reference_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redeemed_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type reward_redemptionsUncheckedUpdateManyWithoutReward_entitlementsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  profile_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redemption_context?: Prisma.StringFieldUpdateOperationsInput | string
  redemption_reference_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  redeemed_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}



export type reward_redemptionsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  entitlement_id?: boolean
  profile_id?: boolean
  redemption_context?: boolean
  redemption_reference_id?: boolean
  redeemed_at?: boolean
  metadata?: boolean
  reward_entitlements?: boolean | Prisma.reward_entitlementsDefaultArgs<ExtArgs>
  profiles?: boolean | Prisma.reward_redemptions$profilesArgs<ExtArgs>
}, ExtArgs["result"]["reward_redemptions"]>

export type reward_redemptionsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  entitlement_id?: boolean
  profile_id?: boolean
  redemption_context?: boolean
  redemption_reference_id?: boolean
  redeemed_at?: boolean
  metadata?: boolean
  reward_entitlements?: boolean | Prisma.reward_entitlementsDefaultArgs<ExtArgs>
  profiles?: boolean | Prisma.reward_redemptions$profilesArgs<ExtArgs>
}, ExtArgs["result"]["reward_redemptions"]>

export type reward_redemptionsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  entitlement_id?: boolean
  profile_id?: boolean
  redemption_context?: boolean
  redemption_reference_id?: boolean
  redeemed_at?: boolean
  metadata?: boolean
  reward_entitlements?: boolean | Prisma.reward_entitlementsDefaultArgs<ExtArgs>
  profiles?: boolean | Prisma.reward_redemptions$profilesArgs<ExtArgs>
}, ExtArgs["result"]["reward_redemptions"]>

export type reward_redemptionsSelectScalar = {
  id?: boolean
  entitlement_id?: boolean
  profile_id?: boolean
  redemption_context?: boolean
  redemption_reference_id?: boolean
  redeemed_at?: boolean
  metadata?: boolean
}

export type reward_redemptionsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "entitlement_id" | "profile_id" | "redemption_context" | "redemption_reference_id" | "redeemed_at" | "metadata", ExtArgs["result"]["reward_redemptions"]>
export type reward_redemptionsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  reward_entitlements?: boolean | Prisma.reward_entitlementsDefaultArgs<ExtArgs>
  profiles?: boolean | Prisma.reward_redemptions$profilesArgs<ExtArgs>
}
export type reward_redemptionsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  reward_entitlements?: boolean | Prisma.reward_entitlementsDefaultArgs<ExtArgs>
  profiles?: boolean | Prisma.reward_redemptions$profilesArgs<ExtArgs>
}
export type reward_redemptionsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  reward_entitlements?: boolean | Prisma.reward_entitlementsDefaultArgs<ExtArgs>
  profiles?: boolean | Prisma.reward_redemptions$profilesArgs<ExtArgs>
}

export type $reward_redemptionsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "reward_redemptions"
  objects: {
    reward_entitlements: Prisma.$reward_entitlementsPayload<ExtArgs>
    profiles: Prisma.$profilesPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    entitlement_id: string
    profile_id: string | null
    redemption_context: string
    redemption_reference_id: string | null
    redeemed_at: Date
    metadata: runtime.JsonValue
  }, ExtArgs["result"]["reward_redemptions"]>
  composites: {}
}

export type reward_redemptionsGetPayload<S extends boolean | null | undefined | reward_redemptionsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$reward_redemptionsPayload, S>

export type reward_redemptionsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<reward_redemptionsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Reward_redemptionsCountAggregateInputType | true
  }

export interface reward_redemptionsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['reward_redemptions'], meta: { name: 'reward_redemptions' } }
  /**
   * Find zero or one Reward_redemptions that matches the filter.
   * @param {reward_redemptionsFindUniqueArgs} args - Arguments to find a Reward_redemptions
   * @example
   * // Get one Reward_redemptions
   * const reward_redemptions = await prisma.reward_redemptions.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends reward_redemptionsFindUniqueArgs>(args: Prisma.SelectSubset<T, reward_redemptionsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__reward_redemptionsClient<runtime.Types.Result.GetResult<Prisma.$reward_redemptionsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Reward_redemptions that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {reward_redemptionsFindUniqueOrThrowArgs} args - Arguments to find a Reward_redemptions
   * @example
   * // Get one Reward_redemptions
   * const reward_redemptions = await prisma.reward_redemptions.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends reward_redemptionsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, reward_redemptionsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__reward_redemptionsClient<runtime.Types.Result.GetResult<Prisma.$reward_redemptionsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Reward_redemptions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {reward_redemptionsFindFirstArgs} args - Arguments to find a Reward_redemptions
   * @example
   * // Get one Reward_redemptions
   * const reward_redemptions = await prisma.reward_redemptions.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends reward_redemptionsFindFirstArgs>(args?: Prisma.SelectSubset<T, reward_redemptionsFindFirstArgs<ExtArgs>>): Prisma.Prisma__reward_redemptionsClient<runtime.Types.Result.GetResult<Prisma.$reward_redemptionsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Reward_redemptions that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {reward_redemptionsFindFirstOrThrowArgs} args - Arguments to find a Reward_redemptions
   * @example
   * // Get one Reward_redemptions
   * const reward_redemptions = await prisma.reward_redemptions.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends reward_redemptionsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, reward_redemptionsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__reward_redemptionsClient<runtime.Types.Result.GetResult<Prisma.$reward_redemptionsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Reward_redemptions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {reward_redemptionsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Reward_redemptions
   * const reward_redemptions = await prisma.reward_redemptions.findMany()
   * 
   * // Get first 10 Reward_redemptions
   * const reward_redemptions = await prisma.reward_redemptions.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const reward_redemptionsWithIdOnly = await prisma.reward_redemptions.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends reward_redemptionsFindManyArgs>(args?: Prisma.SelectSubset<T, reward_redemptionsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$reward_redemptionsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Reward_redemptions.
   * @param {reward_redemptionsCreateArgs} args - Arguments to create a Reward_redemptions.
   * @example
   * // Create one Reward_redemptions
   * const Reward_redemptions = await prisma.reward_redemptions.create({
   *   data: {
   *     // ... data to create a Reward_redemptions
   *   }
   * })
   * 
   */
  create<T extends reward_redemptionsCreateArgs>(args: Prisma.SelectSubset<T, reward_redemptionsCreateArgs<ExtArgs>>): Prisma.Prisma__reward_redemptionsClient<runtime.Types.Result.GetResult<Prisma.$reward_redemptionsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Reward_redemptions.
   * @param {reward_redemptionsCreateManyArgs} args - Arguments to create many Reward_redemptions.
   * @example
   * // Create many Reward_redemptions
   * const reward_redemptions = await prisma.reward_redemptions.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends reward_redemptionsCreateManyArgs>(args?: Prisma.SelectSubset<T, reward_redemptionsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Reward_redemptions and returns the data saved in the database.
   * @param {reward_redemptionsCreateManyAndReturnArgs} args - Arguments to create many Reward_redemptions.
   * @example
   * // Create many Reward_redemptions
   * const reward_redemptions = await prisma.reward_redemptions.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Reward_redemptions and only return the `id`
   * const reward_redemptionsWithIdOnly = await prisma.reward_redemptions.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends reward_redemptionsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, reward_redemptionsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$reward_redemptionsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Reward_redemptions.
   * @param {reward_redemptionsDeleteArgs} args - Arguments to delete one Reward_redemptions.
   * @example
   * // Delete one Reward_redemptions
   * const Reward_redemptions = await prisma.reward_redemptions.delete({
   *   where: {
   *     // ... filter to delete one Reward_redemptions
   *   }
   * })
   * 
   */
  delete<T extends reward_redemptionsDeleteArgs>(args: Prisma.SelectSubset<T, reward_redemptionsDeleteArgs<ExtArgs>>): Prisma.Prisma__reward_redemptionsClient<runtime.Types.Result.GetResult<Prisma.$reward_redemptionsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Reward_redemptions.
   * @param {reward_redemptionsUpdateArgs} args - Arguments to update one Reward_redemptions.
   * @example
   * // Update one Reward_redemptions
   * const reward_redemptions = await prisma.reward_redemptions.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends reward_redemptionsUpdateArgs>(args: Prisma.SelectSubset<T, reward_redemptionsUpdateArgs<ExtArgs>>): Prisma.Prisma__reward_redemptionsClient<runtime.Types.Result.GetResult<Prisma.$reward_redemptionsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Reward_redemptions.
   * @param {reward_redemptionsDeleteManyArgs} args - Arguments to filter Reward_redemptions to delete.
   * @example
   * // Delete a few Reward_redemptions
   * const { count } = await prisma.reward_redemptions.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends reward_redemptionsDeleteManyArgs>(args?: Prisma.SelectSubset<T, reward_redemptionsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Reward_redemptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {reward_redemptionsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Reward_redemptions
   * const reward_redemptions = await prisma.reward_redemptions.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends reward_redemptionsUpdateManyArgs>(args: Prisma.SelectSubset<T, reward_redemptionsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Reward_redemptions and returns the data updated in the database.
   * @param {reward_redemptionsUpdateManyAndReturnArgs} args - Arguments to update many Reward_redemptions.
   * @example
   * // Update many Reward_redemptions
   * const reward_redemptions = await prisma.reward_redemptions.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Reward_redemptions and only return the `id`
   * const reward_redemptionsWithIdOnly = await prisma.reward_redemptions.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends reward_redemptionsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, reward_redemptionsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$reward_redemptionsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Reward_redemptions.
   * @param {reward_redemptionsUpsertArgs} args - Arguments to update or create a Reward_redemptions.
   * @example
   * // Update or create a Reward_redemptions
   * const reward_redemptions = await prisma.reward_redemptions.upsert({
   *   create: {
   *     // ... data to create a Reward_redemptions
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Reward_redemptions we want to update
   *   }
   * })
   */
  upsert<T extends reward_redemptionsUpsertArgs>(args: Prisma.SelectSubset<T, reward_redemptionsUpsertArgs<ExtArgs>>): Prisma.Prisma__reward_redemptionsClient<runtime.Types.Result.GetResult<Prisma.$reward_redemptionsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Reward_redemptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {reward_redemptionsCountArgs} args - Arguments to filter Reward_redemptions to count.
   * @example
   * // Count the number of Reward_redemptions
   * const count = await prisma.reward_redemptions.count({
   *   where: {
   *     // ... the filter for the Reward_redemptions we want to count
   *   }
   * })
  **/
  count<T extends reward_redemptionsCountArgs>(
    args?: Prisma.Subset<T, reward_redemptionsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Reward_redemptionsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Reward_redemptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Reward_redemptionsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Reward_redemptionsAggregateArgs>(args: Prisma.Subset<T, Reward_redemptionsAggregateArgs>): Prisma.PrismaPromise<GetReward_redemptionsAggregateType<T>>

  /**
   * Group by Reward_redemptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {reward_redemptionsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends reward_redemptionsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: reward_redemptionsGroupByArgs['orderBy'] }
      : { orderBy?: reward_redemptionsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, reward_redemptionsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetReward_redemptionsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the reward_redemptions model
 */
readonly fields: reward_redemptionsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for reward_redemptions.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__reward_redemptionsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  reward_entitlements<T extends Prisma.reward_entitlementsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.reward_entitlementsDefaultArgs<ExtArgs>>): Prisma.Prisma__reward_entitlementsClient<runtime.Types.Result.GetResult<Prisma.$reward_entitlementsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  profiles<T extends Prisma.reward_redemptions$profilesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.reward_redemptions$profilesArgs<ExtArgs>>): Prisma.Prisma__profilesClient<runtime.Types.Result.GetResult<Prisma.$profilesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the reward_redemptions model
 */
export interface reward_redemptionsFieldRefs {
  readonly id: Prisma.FieldRef<"reward_redemptions", 'String'>
  readonly entitlement_id: Prisma.FieldRef<"reward_redemptions", 'String'>
  readonly profile_id: Prisma.FieldRef<"reward_redemptions", 'String'>
  readonly redemption_context: Prisma.FieldRef<"reward_redemptions", 'String'>
  readonly redemption_reference_id: Prisma.FieldRef<"reward_redemptions", 'String'>
  readonly redeemed_at: Prisma.FieldRef<"reward_redemptions", 'DateTime'>
  readonly metadata: Prisma.FieldRef<"reward_redemptions", 'Json'>
}
    

// Custom InputTypes
/**
 * reward_redemptions findUnique
 */
export type reward_redemptionsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_redemptions
   */
  select?: Prisma.reward_redemptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_redemptions
   */
  omit?: Prisma.reward_redemptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_redemptionsInclude<ExtArgs> | null
  /**
   * Filter, which reward_redemptions to fetch.
   */
  where: Prisma.reward_redemptionsWhereUniqueInput
}

/**
 * reward_redemptions findUniqueOrThrow
 */
export type reward_redemptionsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_redemptions
   */
  select?: Prisma.reward_redemptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_redemptions
   */
  omit?: Prisma.reward_redemptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_redemptionsInclude<ExtArgs> | null
  /**
   * Filter, which reward_redemptions to fetch.
   */
  where: Prisma.reward_redemptionsWhereUniqueInput
}

/**
 * reward_redemptions findFirst
 */
export type reward_redemptionsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_redemptions
   */
  select?: Prisma.reward_redemptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_redemptions
   */
  omit?: Prisma.reward_redemptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_redemptionsInclude<ExtArgs> | null
  /**
   * Filter, which reward_redemptions to fetch.
   */
  where?: Prisma.reward_redemptionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of reward_redemptions to fetch.
   */
  orderBy?: Prisma.reward_redemptionsOrderByWithRelationInput | Prisma.reward_redemptionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for reward_redemptions.
   */
  cursor?: Prisma.reward_redemptionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` reward_redemptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` reward_redemptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of reward_redemptions.
   */
  distinct?: Prisma.Reward_redemptionsScalarFieldEnum | Prisma.Reward_redemptionsScalarFieldEnum[]
}

/**
 * reward_redemptions findFirstOrThrow
 */
export type reward_redemptionsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_redemptions
   */
  select?: Prisma.reward_redemptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_redemptions
   */
  omit?: Prisma.reward_redemptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_redemptionsInclude<ExtArgs> | null
  /**
   * Filter, which reward_redemptions to fetch.
   */
  where?: Prisma.reward_redemptionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of reward_redemptions to fetch.
   */
  orderBy?: Prisma.reward_redemptionsOrderByWithRelationInput | Prisma.reward_redemptionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for reward_redemptions.
   */
  cursor?: Prisma.reward_redemptionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` reward_redemptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` reward_redemptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of reward_redemptions.
   */
  distinct?: Prisma.Reward_redemptionsScalarFieldEnum | Prisma.Reward_redemptionsScalarFieldEnum[]
}

/**
 * reward_redemptions findMany
 */
export type reward_redemptionsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_redemptions
   */
  select?: Prisma.reward_redemptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_redemptions
   */
  omit?: Prisma.reward_redemptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_redemptionsInclude<ExtArgs> | null
  /**
   * Filter, which reward_redemptions to fetch.
   */
  where?: Prisma.reward_redemptionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of reward_redemptions to fetch.
   */
  orderBy?: Prisma.reward_redemptionsOrderByWithRelationInput | Prisma.reward_redemptionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing reward_redemptions.
   */
  cursor?: Prisma.reward_redemptionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` reward_redemptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` reward_redemptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of reward_redemptions.
   */
  distinct?: Prisma.Reward_redemptionsScalarFieldEnum | Prisma.Reward_redemptionsScalarFieldEnum[]
}

/**
 * reward_redemptions create
 */
export type reward_redemptionsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_redemptions
   */
  select?: Prisma.reward_redemptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_redemptions
   */
  omit?: Prisma.reward_redemptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_redemptionsInclude<ExtArgs> | null
  /**
   * The data needed to create a reward_redemptions.
   */
  data: Prisma.XOR<Prisma.reward_redemptionsCreateInput, Prisma.reward_redemptionsUncheckedCreateInput>
}

/**
 * reward_redemptions createMany
 */
export type reward_redemptionsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many reward_redemptions.
   */
  data: Prisma.reward_redemptionsCreateManyInput | Prisma.reward_redemptionsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * reward_redemptions createManyAndReturn
 */
export type reward_redemptionsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_redemptions
   */
  select?: Prisma.reward_redemptionsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the reward_redemptions
   */
  omit?: Prisma.reward_redemptionsOmit<ExtArgs> | null
  /**
   * The data used to create many reward_redemptions.
   */
  data: Prisma.reward_redemptionsCreateManyInput | Prisma.reward_redemptionsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_redemptionsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * reward_redemptions update
 */
export type reward_redemptionsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_redemptions
   */
  select?: Prisma.reward_redemptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_redemptions
   */
  omit?: Prisma.reward_redemptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_redemptionsInclude<ExtArgs> | null
  /**
   * The data needed to update a reward_redemptions.
   */
  data: Prisma.XOR<Prisma.reward_redemptionsUpdateInput, Prisma.reward_redemptionsUncheckedUpdateInput>
  /**
   * Choose, which reward_redemptions to update.
   */
  where: Prisma.reward_redemptionsWhereUniqueInput
}

/**
 * reward_redemptions updateMany
 */
export type reward_redemptionsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update reward_redemptions.
   */
  data: Prisma.XOR<Prisma.reward_redemptionsUpdateManyMutationInput, Prisma.reward_redemptionsUncheckedUpdateManyInput>
  /**
   * Filter which reward_redemptions to update
   */
  where?: Prisma.reward_redemptionsWhereInput
  /**
   * Limit how many reward_redemptions to update.
   */
  limit?: number
}

/**
 * reward_redemptions updateManyAndReturn
 */
export type reward_redemptionsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_redemptions
   */
  select?: Prisma.reward_redemptionsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the reward_redemptions
   */
  omit?: Prisma.reward_redemptionsOmit<ExtArgs> | null
  /**
   * The data used to update reward_redemptions.
   */
  data: Prisma.XOR<Prisma.reward_redemptionsUpdateManyMutationInput, Prisma.reward_redemptionsUncheckedUpdateManyInput>
  /**
   * Filter which reward_redemptions to update
   */
  where?: Prisma.reward_redemptionsWhereInput
  /**
   * Limit how many reward_redemptions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_redemptionsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * reward_redemptions upsert
 */
export type reward_redemptionsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_redemptions
   */
  select?: Prisma.reward_redemptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_redemptions
   */
  omit?: Prisma.reward_redemptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_redemptionsInclude<ExtArgs> | null
  /**
   * The filter to search for the reward_redemptions to update in case it exists.
   */
  where: Prisma.reward_redemptionsWhereUniqueInput
  /**
   * In case the reward_redemptions found by the `where` argument doesn't exist, create a new reward_redemptions with this data.
   */
  create: Prisma.XOR<Prisma.reward_redemptionsCreateInput, Prisma.reward_redemptionsUncheckedCreateInput>
  /**
   * In case the reward_redemptions was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.reward_redemptionsUpdateInput, Prisma.reward_redemptionsUncheckedUpdateInput>
}

/**
 * reward_redemptions delete
 */
export type reward_redemptionsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_redemptions
   */
  select?: Prisma.reward_redemptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_redemptions
   */
  omit?: Prisma.reward_redemptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_redemptionsInclude<ExtArgs> | null
  /**
   * Filter which reward_redemptions to delete.
   */
  where: Prisma.reward_redemptionsWhereUniqueInput
}

/**
 * reward_redemptions deleteMany
 */
export type reward_redemptionsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which reward_redemptions to delete
   */
  where?: Prisma.reward_redemptionsWhereInput
  /**
   * Limit how many reward_redemptions to delete.
   */
  limit?: number
}

/**
 * reward_redemptions.profiles
 */
export type reward_redemptions$profilesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the profiles
   */
  select?: Prisma.profilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the profiles
   */
  omit?: Prisma.profilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.profilesInclude<ExtArgs> | null
  where?: Prisma.profilesWhereInput
}

/**
 * reward_redemptions without action
 */
export type reward_redemptionsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_redemptions
   */
  select?: Prisma.reward_redemptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_redemptions
   */
  omit?: Prisma.reward_redemptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_redemptionsInclude<ExtArgs> | null
}
