
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `reward_entitlements` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model reward_entitlements
 * This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info.
 */
export type reward_entitlementsModel = runtime.Types.Result.DefaultSelection<Prisma.$reward_entitlementsPayload>

export type AggregateReward_entitlements = {
  _count: Reward_entitlementsCountAggregateOutputType | null
  _avg: Reward_entitlementsAvgAggregateOutputType | null
  _sum: Reward_entitlementsSumAggregateOutputType | null
  _min: Reward_entitlementsMinAggregateOutputType | null
  _max: Reward_entitlementsMaxAggregateOutputType | null
}

export type Reward_entitlementsAvgAggregateOutputType = {
  source_referral_count: number | null
}

export type Reward_entitlementsSumAggregateOutputType = {
  source_referral_count: number | null
}

export type Reward_entitlementsMinAggregateOutputType = {
  id: string | null
  user_email: string | null
  waitlist_id: string | null
  profile_id: string | null
  reward_key: string | null
  source_event: string | null
  source_referral_count: number | null
  status: string | null
  granted_at: Date | null
  expires_at: Date | null
}

export type Reward_entitlementsMaxAggregateOutputType = {
  id: string | null
  user_email: string | null
  waitlist_id: string | null
  profile_id: string | null
  reward_key: string | null
  source_event: string | null
  source_referral_count: number | null
  status: string | null
  granted_at: Date | null
  expires_at: Date | null
}

export type Reward_entitlementsCountAggregateOutputType = {
  id: number
  user_email: number
  waitlist_id: number
  profile_id: number
  reward_key: number
  source_event: number
  source_referral_count: number
  status: number
  granted_at: number
  expires_at: number
  metadata: number
  _all: number
}


export type Reward_entitlementsAvgAggregateInputType = {
  source_referral_count?: true
}

export type Reward_entitlementsSumAggregateInputType = {
  source_referral_count?: true
}

export type Reward_entitlementsMinAggregateInputType = {
  id?: true
  user_email?: true
  waitlist_id?: true
  profile_id?: true
  reward_key?: true
  source_event?: true
  source_referral_count?: true
  status?: true
  granted_at?: true
  expires_at?: true
}

export type Reward_entitlementsMaxAggregateInputType = {
  id?: true
  user_email?: true
  waitlist_id?: true
  profile_id?: true
  reward_key?: true
  source_event?: true
  source_referral_count?: true
  status?: true
  granted_at?: true
  expires_at?: true
}

export type Reward_entitlementsCountAggregateInputType = {
  id?: true
  user_email?: true
  waitlist_id?: true
  profile_id?: true
  reward_key?: true
  source_event?: true
  source_referral_count?: true
  status?: true
  granted_at?: true
  expires_at?: true
  metadata?: true
  _all?: true
}

export type Reward_entitlementsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which reward_entitlements to aggregate.
   */
  where?: Prisma.reward_entitlementsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of reward_entitlements to fetch.
   */
  orderBy?: Prisma.reward_entitlementsOrderByWithRelationInput | Prisma.reward_entitlementsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.reward_entitlementsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` reward_entitlements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` reward_entitlements.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned reward_entitlements
  **/
  _count?: true | Reward_entitlementsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Reward_entitlementsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Reward_entitlementsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Reward_entitlementsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Reward_entitlementsMaxAggregateInputType
}

export type GetReward_entitlementsAggregateType<T extends Reward_entitlementsAggregateArgs> = {
      [P in keyof T & keyof AggregateReward_entitlements]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateReward_entitlements[P]>
    : Prisma.GetScalarType<T[P], AggregateReward_entitlements[P]>
}




export type reward_entitlementsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.reward_entitlementsWhereInput
  orderBy?: Prisma.reward_entitlementsOrderByWithAggregationInput | Prisma.reward_entitlementsOrderByWithAggregationInput[]
  by: Prisma.Reward_entitlementsScalarFieldEnum[] | Prisma.Reward_entitlementsScalarFieldEnum
  having?: Prisma.reward_entitlementsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Reward_entitlementsCountAggregateInputType | true
  _avg?: Reward_entitlementsAvgAggregateInputType
  _sum?: Reward_entitlementsSumAggregateInputType
  _min?: Reward_entitlementsMinAggregateInputType
  _max?: Reward_entitlementsMaxAggregateInputType
}

export type Reward_entitlementsGroupByOutputType = {
  id: string
  user_email: string
  waitlist_id: string | null
  profile_id: string | null
  reward_key: string
  source_event: string
  source_referral_count: number | null
  status: string
  granted_at: Date
  expires_at: Date | null
  metadata: runtime.JsonValue
  _count: Reward_entitlementsCountAggregateOutputType | null
  _avg: Reward_entitlementsAvgAggregateOutputType | null
  _sum: Reward_entitlementsSumAggregateOutputType | null
  _min: Reward_entitlementsMinAggregateOutputType | null
  _max: Reward_entitlementsMaxAggregateOutputType | null
}

export type GetReward_entitlementsGroupByPayload<T extends reward_entitlementsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Reward_entitlementsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Reward_entitlementsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Reward_entitlementsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Reward_entitlementsGroupByOutputType[P]>
      }
    >
  >



export type reward_entitlementsWhereInput = {
  AND?: Prisma.reward_entitlementsWhereInput | Prisma.reward_entitlementsWhereInput[]
  OR?: Prisma.reward_entitlementsWhereInput[]
  NOT?: Prisma.reward_entitlementsWhereInput | Prisma.reward_entitlementsWhereInput[]
  id?: Prisma.UuidFilter<"reward_entitlements"> | string
  user_email?: Prisma.StringFilter<"reward_entitlements"> | string
  waitlist_id?: Prisma.UuidNullableFilter<"reward_entitlements"> | string | null
  profile_id?: Prisma.UuidNullableFilter<"reward_entitlements"> | string | null
  reward_key?: Prisma.StringFilter<"reward_entitlements"> | string
  source_event?: Prisma.StringFilter<"reward_entitlements"> | string
  source_referral_count?: Prisma.IntNullableFilter<"reward_entitlements"> | number | null
  status?: Prisma.StringFilter<"reward_entitlements"> | string
  granted_at?: Prisma.DateTimeFilter<"reward_entitlements"> | Date | string
  expires_at?: Prisma.DateTimeNullableFilter<"reward_entitlements"> | Date | string | null
  metadata?: Prisma.JsonFilter<"reward_entitlements">
  profiles?: Prisma.XOR<Prisma.ProfilesNullableScalarRelationFilter, Prisma.profilesWhereInput> | null
  reward_catalog?: Prisma.XOR<Prisma.Reward_catalogScalarRelationFilter, Prisma.reward_catalogWhereInput>
  waitlist?: Prisma.XOR<Prisma.WaitlistNullableScalarRelationFilter, Prisma.waitlistWhereInput> | null
  reward_redemptions?: Prisma.Reward_redemptionsListRelationFilter
}

export type reward_entitlementsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  user_email?: Prisma.SortOrder
  waitlist_id?: Prisma.SortOrderInput | Prisma.SortOrder
  profile_id?: Prisma.SortOrderInput | Prisma.SortOrder
  reward_key?: Prisma.SortOrder
  source_event?: Prisma.SortOrder
  source_referral_count?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  granted_at?: Prisma.SortOrder
  expires_at?: Prisma.SortOrderInput | Prisma.SortOrder
  metadata?: Prisma.SortOrder
  profiles?: Prisma.profilesOrderByWithRelationInput
  reward_catalog?: Prisma.reward_catalogOrderByWithRelationInput
  waitlist?: Prisma.waitlistOrderByWithRelationInput
  reward_redemptions?: Prisma.reward_redemptionsOrderByRelationAggregateInput
}

export type reward_entitlementsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  user_email_reward_key?: Prisma.reward_entitlementsUser_emailReward_keyCompoundUniqueInput
  AND?: Prisma.reward_entitlementsWhereInput | Prisma.reward_entitlementsWhereInput[]
  OR?: Prisma.reward_entitlementsWhereInput[]
  NOT?: Prisma.reward_entitlementsWhereInput | Prisma.reward_entitlementsWhereInput[]
  user_email?: Prisma.StringFilter<"reward_entitlements"> | string
  waitlist_id?: Prisma.UuidNullableFilter<"reward_entitlements"> | string | null
  profile_id?: Prisma.UuidNullableFilter<"reward_entitlements"> | string | null
  reward_key?: Prisma.StringFilter<"reward_entitlements"> | string
  source_event?: Prisma.StringFilter<"reward_entitlements"> | string
  source_referral_count?: Prisma.IntNullableFilter<"reward_entitlements"> | number | null
  status?: Prisma.StringFilter<"reward_entitlements"> | string
  granted_at?: Prisma.DateTimeFilter<"reward_entitlements"> | Date | string
  expires_at?: Prisma.DateTimeNullableFilter<"reward_entitlements"> | Date | string | null
  metadata?: Prisma.JsonFilter<"reward_entitlements">
  profiles?: Prisma.XOR<Prisma.ProfilesNullableScalarRelationFilter, Prisma.profilesWhereInput> | null
  reward_catalog?: Prisma.XOR<Prisma.Reward_catalogScalarRelationFilter, Prisma.reward_catalogWhereInput>
  waitlist?: Prisma.XOR<Prisma.WaitlistNullableScalarRelationFilter, Prisma.waitlistWhereInput> | null
  reward_redemptions?: Prisma.Reward_redemptionsListRelationFilter
}, "id" | "user_email_reward_key">

export type reward_entitlementsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  user_email?: Prisma.SortOrder
  waitlist_id?: Prisma.SortOrderInput | Prisma.SortOrder
  profile_id?: Prisma.SortOrderInput | Prisma.SortOrder
  reward_key?: Prisma.SortOrder
  source_event?: Prisma.SortOrder
  source_referral_count?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  granted_at?: Prisma.SortOrder
  expires_at?: Prisma.SortOrderInput | Prisma.SortOrder
  metadata?: Prisma.SortOrder
  _count?: Prisma.reward_entitlementsCountOrderByAggregateInput
  _avg?: Prisma.reward_entitlementsAvgOrderByAggregateInput
  _max?: Prisma.reward_entitlementsMaxOrderByAggregateInput
  _min?: Prisma.reward_entitlementsMinOrderByAggregateInput
  _sum?: Prisma.reward_entitlementsSumOrderByAggregateInput
}

export type reward_entitlementsScalarWhereWithAggregatesInput = {
  AND?: Prisma.reward_entitlementsScalarWhereWithAggregatesInput | Prisma.reward_entitlementsScalarWhereWithAggregatesInput[]
  OR?: Prisma.reward_entitlementsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.reward_entitlementsScalarWhereWithAggregatesInput | Prisma.reward_entitlementsScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"reward_entitlements"> | string
  user_email?: Prisma.StringWithAggregatesFilter<"reward_entitlements"> | string
  waitlist_id?: Prisma.UuidNullableWithAggregatesFilter<"reward_entitlements"> | string | null
  profile_id?: Prisma.UuidNullableWithAggregatesFilter<"reward_entitlements"> | string | null
  reward_key?: Prisma.StringWithAggregatesFilter<"reward_entitlements"> | string
  source_event?: Prisma.StringWithAggregatesFilter<"reward_entitlements"> | string
  source_referral_count?: Prisma.IntNullableWithAggregatesFilter<"reward_entitlements"> | number | null
  status?: Prisma.StringWithAggregatesFilter<"reward_entitlements"> | string
  granted_at?: Prisma.DateTimeWithAggregatesFilter<"reward_entitlements"> | Date | string
  expires_at?: Prisma.DateTimeNullableWithAggregatesFilter<"reward_entitlements"> | Date | string | null
  metadata?: Prisma.JsonWithAggregatesFilter<"reward_entitlements">
}

export type reward_entitlementsCreateInput = {
  id?: string
  user_email: string
  source_event: string
  source_referral_count?: number | null
  status?: string
  granted_at?: Date | string
  expires_at?: Date | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  profiles?: Prisma.profilesCreateNestedOneWithoutReward_entitlementsInput
  reward_catalog: Prisma.reward_catalogCreateNestedOneWithoutReward_entitlementsInput
  waitlist?: Prisma.waitlistCreateNestedOneWithoutReward_entitlementsInput
  reward_redemptions?: Prisma.reward_redemptionsCreateNestedManyWithoutReward_entitlementsInput
}

export type reward_entitlementsUncheckedCreateInput = {
  id?: string
  user_email: string
  waitlist_id?: string | null
  profile_id?: string | null
  reward_key: string
  source_event: string
  source_referral_count?: number | null
  status?: string
  granted_at?: Date | string
  expires_at?: Date | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  reward_redemptions?: Prisma.reward_redemptionsUncheckedCreateNestedManyWithoutReward_entitlementsInput
}

export type reward_entitlementsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_email?: Prisma.StringFieldUpdateOperationsInput | string
  source_event?: Prisma.StringFieldUpdateOperationsInput | string
  source_referral_count?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  granted_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  profiles?: Prisma.profilesUpdateOneWithoutReward_entitlementsNestedInput
  reward_catalog?: Prisma.reward_catalogUpdateOneRequiredWithoutReward_entitlementsNestedInput
  waitlist?: Prisma.waitlistUpdateOneWithoutReward_entitlementsNestedInput
  reward_redemptions?: Prisma.reward_redemptionsUpdateManyWithoutReward_entitlementsNestedInput
}

export type reward_entitlementsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_email?: Prisma.StringFieldUpdateOperationsInput | string
  waitlist_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profile_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reward_key?: Prisma.StringFieldUpdateOperationsInput | string
  source_event?: Prisma.StringFieldUpdateOperationsInput | string
  source_referral_count?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  granted_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  reward_redemptions?: Prisma.reward_redemptionsUncheckedUpdateManyWithoutReward_entitlementsNestedInput
}

export type reward_entitlementsCreateManyInput = {
  id?: string
  user_email: string
  waitlist_id?: string | null
  profile_id?: string | null
  reward_key: string
  source_event: string
  source_referral_count?: number | null
  status?: string
  granted_at?: Date | string
  expires_at?: Date | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type reward_entitlementsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_email?: Prisma.StringFieldUpdateOperationsInput | string
  source_event?: Prisma.StringFieldUpdateOperationsInput | string
  source_referral_count?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  granted_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type reward_entitlementsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_email?: Prisma.StringFieldUpdateOperationsInput | string
  waitlist_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profile_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reward_key?: Prisma.StringFieldUpdateOperationsInput | string
  source_event?: Prisma.StringFieldUpdateOperationsInput | string
  source_referral_count?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  granted_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type Reward_entitlementsListRelationFilter = {
  every?: Prisma.reward_entitlementsWhereInput
  some?: Prisma.reward_entitlementsWhereInput
  none?: Prisma.reward_entitlementsWhereInput
}

export type reward_entitlementsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type reward_entitlementsUser_emailReward_keyCompoundUniqueInput = {
  user_email: string
  reward_key: string
}

export type reward_entitlementsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_email?: Prisma.SortOrder
  waitlist_id?: Prisma.SortOrder
  profile_id?: Prisma.SortOrder
  reward_key?: Prisma.SortOrder
  source_event?: Prisma.SortOrder
  source_referral_count?: Prisma.SortOrder
  status?: Prisma.SortOrder
  granted_at?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
}

export type reward_entitlementsAvgOrderByAggregateInput = {
  source_referral_count?: Prisma.SortOrder
}

export type reward_entitlementsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_email?: Prisma.SortOrder
  waitlist_id?: Prisma.SortOrder
  profile_id?: Prisma.SortOrder
  reward_key?: Prisma.SortOrder
  source_event?: Prisma.SortOrder
  source_referral_count?: Prisma.SortOrder
  status?: Prisma.SortOrder
  granted_at?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
}

export type reward_entitlementsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_email?: Prisma.SortOrder
  waitlist_id?: Prisma.SortOrder
  profile_id?: Prisma.SortOrder
  reward_key?: Prisma.SortOrder
  source_event?: Prisma.SortOrder
  source_referral_count?: Prisma.SortOrder
  status?: Prisma.SortOrder
  granted_at?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
}

export type reward_entitlementsSumOrderByAggregateInput = {
  source_referral_count?: Prisma.SortOrder
}

export type Reward_entitlementsScalarRelationFilter = {
  is?: Prisma.reward_entitlementsWhereInput
  isNot?: Prisma.reward_entitlementsWhereInput
}

export type reward_entitlementsCreateNestedManyWithoutProfilesInput = {
  create?: Prisma.XOR<Prisma.reward_entitlementsCreateWithoutProfilesInput, Prisma.reward_entitlementsUncheckedCreateWithoutProfilesInput> | Prisma.reward_entitlementsCreateWithoutProfilesInput[] | Prisma.reward_entitlementsUncheckedCreateWithoutProfilesInput[]
  connectOrCreate?: Prisma.reward_entitlementsCreateOrConnectWithoutProfilesInput | Prisma.reward_entitlementsCreateOrConnectWithoutProfilesInput[]
  createMany?: Prisma.reward_entitlementsCreateManyProfilesInputEnvelope
  connect?: Prisma.reward_entitlementsWhereUniqueInput | Prisma.reward_entitlementsWhereUniqueInput[]
}

export type reward_entitlementsUncheckedCreateNestedManyWithoutProfilesInput = {
  create?: Prisma.XOR<Prisma.reward_entitlementsCreateWithoutProfilesInput, Prisma.reward_entitlementsUncheckedCreateWithoutProfilesInput> | Prisma.reward_entitlementsCreateWithoutProfilesInput[] | Prisma.reward_entitlementsUncheckedCreateWithoutProfilesInput[]
  connectOrCreate?: Prisma.reward_entitlementsCreateOrConnectWithoutProfilesInput | Prisma.reward_entitlementsCreateOrConnectWithoutProfilesInput[]
  createMany?: Prisma.reward_entitlementsCreateManyProfilesInputEnvelope
  connect?: Prisma.reward_entitlementsWhereUniqueInput | Prisma.reward_entitlementsWhereUniqueInput[]
}

export type reward_entitlementsUpdateManyWithoutProfilesNestedInput = {
  create?: Prisma.XOR<Prisma.reward_entitlementsCreateWithoutProfilesInput, Prisma.reward_entitlementsUncheckedCreateWithoutProfilesInput> | Prisma.reward_entitlementsCreateWithoutProfilesInput[] | Prisma.reward_entitlementsUncheckedCreateWithoutProfilesInput[]
  connectOrCreate?: Prisma.reward_entitlementsCreateOrConnectWithoutProfilesInput | Prisma.reward_entitlementsCreateOrConnectWithoutProfilesInput[]
  upsert?: Prisma.reward_entitlementsUpsertWithWhereUniqueWithoutProfilesInput | Prisma.reward_entitlementsUpsertWithWhereUniqueWithoutProfilesInput[]
  createMany?: Prisma.reward_entitlementsCreateManyProfilesInputEnvelope
  set?: Prisma.reward_entitlementsWhereUniqueInput | Prisma.reward_entitlementsWhereUniqueInput[]
  disconnect?: Prisma.reward_entitlementsWhereUniqueInput | Prisma.reward_entitlementsWhereUniqueInput[]
  delete?: Prisma.reward_entitlementsWhereUniqueInput | Prisma.reward_entitlementsWhereUniqueInput[]
  connect?: Prisma.reward_entitlementsWhereUniqueInput | Prisma.reward_entitlementsWhereUniqueInput[]
  update?: Prisma.reward_entitlementsUpdateWithWhereUniqueWithoutProfilesInput | Prisma.reward_entitlementsUpdateWithWhereUniqueWithoutProfilesInput[]
  updateMany?: Prisma.reward_entitlementsUpdateManyWithWhereWithoutProfilesInput | Prisma.reward_entitlementsUpdateManyWithWhereWithoutProfilesInput[]
  deleteMany?: Prisma.reward_entitlementsScalarWhereInput | Prisma.reward_entitlementsScalarWhereInput[]
}

export type reward_entitlementsUncheckedUpdateManyWithoutProfilesNestedInput = {
  create?: Prisma.XOR<Prisma.reward_entitlementsCreateWithoutProfilesInput, Prisma.reward_entitlementsUncheckedCreateWithoutProfilesInput> | Prisma.reward_entitlementsCreateWithoutProfilesInput[] | Prisma.reward_entitlementsUncheckedCreateWithoutProfilesInput[]
  connectOrCreate?: Prisma.reward_entitlementsCreateOrConnectWithoutProfilesInput | Prisma.reward_entitlementsCreateOrConnectWithoutProfilesInput[]
  upsert?: Prisma.reward_entitlementsUpsertWithWhereUniqueWithoutProfilesInput | Prisma.reward_entitlementsUpsertWithWhereUniqueWithoutProfilesInput[]
  createMany?: Prisma.reward_entitlementsCreateManyProfilesInputEnvelope
  set?: Prisma.reward_entitlementsWhereUniqueInput | Prisma.reward_entitlementsWhereUniqueInput[]
  disconnect?: Prisma.reward_entitlementsWhereUniqueInput | Prisma.reward_entitlementsWhereUniqueInput[]
  delete?: Prisma.reward_entitlementsWhereUniqueInput | Prisma.reward_entitlementsWhereUniqueInput[]
  connect?: Prisma.reward_entitlementsWhereUniqueInput | Prisma.reward_entitlementsWhereUniqueInput[]
  update?: Prisma.reward_entitlementsUpdateWithWhereUniqueWithoutProfilesInput | Prisma.reward_entitlementsUpdateWithWhereUniqueWithoutProfilesInput[]
  updateMany?: Prisma.reward_entitlementsUpdateManyWithWhereWithoutProfilesInput | Prisma.reward_entitlementsUpdateManyWithWhereWithoutProfilesInput[]
  deleteMany?: Prisma.reward_entitlementsScalarWhereInput | Prisma.reward_entitlementsScalarWhereInput[]
}

export type reward_entitlementsCreateNestedManyWithoutWaitlistInput = {
  create?: Prisma.XOR<Prisma.reward_entitlementsCreateWithoutWaitlistInput, Prisma.reward_entitlementsUncheckedCreateWithoutWaitlistInput> | Prisma.reward_entitlementsCreateWithoutWaitlistInput[] | Prisma.reward_entitlementsUncheckedCreateWithoutWaitlistInput[]
  connectOrCreate?: Prisma.reward_entitlementsCreateOrConnectWithoutWaitlistInput | Prisma.reward_entitlementsCreateOrConnectWithoutWaitlistInput[]
  createMany?: Prisma.reward_entitlementsCreateManyWaitlistInputEnvelope
  connect?: Prisma.reward_entitlementsWhereUniqueInput | Prisma.reward_entitlementsWhereUniqueInput[]
}

export type reward_entitlementsUncheckedCreateNestedManyWithoutWaitlistInput = {
  create?: Prisma.XOR<Prisma.reward_entitlementsCreateWithoutWaitlistInput, Prisma.reward_entitlementsUncheckedCreateWithoutWaitlistInput> | Prisma.reward_entitlementsCreateWithoutWaitlistInput[] | Prisma.reward_entitlementsUncheckedCreateWithoutWaitlistInput[]
  connectOrCreate?: Prisma.reward_entitlementsCreateOrConnectWithoutWaitlistInput | Prisma.reward_entitlementsCreateOrConnectWithoutWaitlistInput[]
  createMany?: Prisma.reward_entitlementsCreateManyWaitlistInputEnvelope
  connect?: Prisma.reward_entitlementsWhereUniqueInput | Prisma.reward_entitlementsWhereUniqueInput[]
}

export type reward_entitlementsUpdateManyWithoutWaitlistNestedInput = {
  create?: Prisma.XOR<Prisma.reward_entitlementsCreateWithoutWaitlistInput, Prisma.reward_entitlementsUncheckedCreateWithoutWaitlistInput> | Prisma.reward_entitlementsCreateWithoutWaitlistInput[] | Prisma.reward_entitlementsUncheckedCreateWithoutWaitlistInput[]
  connectOrCreate?: Prisma.reward_entitlementsCreateOrConnectWithoutWaitlistInput | Prisma.reward_entitlementsCreateOrConnectWithoutWaitlistInput[]
  upsert?: Prisma.reward_entitlementsUpsertWithWhereUniqueWithoutWaitlistInput | Prisma.reward_entitlementsUpsertWithWhereUniqueWithoutWaitlistInput[]
  createMany?: Prisma.reward_entitlementsCreateManyWaitlistInputEnvelope
  set?: Prisma.reward_entitlementsWhereUniqueInput | Prisma.reward_entitlementsWhereUniqueInput[]
  disconnect?: Prisma.reward_entitlementsWhereUniqueInput | Prisma.reward_entitlementsWhereUniqueInput[]
  delete?: Prisma.reward_entitlementsWhereUniqueInput | Prisma.reward_entitlementsWhereUniqueInput[]
  connect?: Prisma.reward_entitlementsWhereUniqueInput | Prisma.reward_entitlementsWhereUniqueInput[]
  update?: Prisma.reward_entitlementsUpdateWithWhereUniqueWithoutWaitlistInput | Prisma.reward_entitlementsUpdateWithWhereUniqueWithoutWaitlistInput[]
  updateMany?: Prisma.reward_entitlementsUpdateManyWithWhereWithoutWaitlistInput | Prisma.reward_entitlementsUpdateManyWithWhereWithoutWaitlistInput[]
  deleteMany?: Prisma.reward_entitlementsScalarWhereInput | Prisma.reward_entitlementsScalarWhereInput[]
}

export type reward_entitlementsUncheckedUpdateManyWithoutWaitlistNestedInput = {
  create?: Prisma.XOR<Prisma.reward_entitlementsCreateWithoutWaitlistInput, Prisma.reward_entitlementsUncheckedCreateWithoutWaitlistInput> | Prisma.reward_entitlementsCreateWithoutWaitlistInput[] | Prisma.reward_entitlementsUncheckedCreateWithoutWaitlistInput[]
  connectOrCreate?: Prisma.reward_entitlementsCreateOrConnectWithoutWaitlistInput | Prisma.reward_entitlementsCreateOrConnectWithoutWaitlistInput[]
  upsert?: Prisma.reward_entitlementsUpsertWithWhereUniqueWithoutWaitlistInput | Prisma.reward_entitlementsUpsertWithWhereUniqueWithoutWaitlistInput[]
  createMany?: Prisma.reward_entitlementsCreateManyWaitlistInputEnvelope
  set?: Prisma.reward_entitlementsWhereUniqueInput | Prisma.reward_entitlementsWhereUniqueInput[]
  disconnect?: Prisma.reward_entitlementsWhereUniqueInput | Prisma.reward_entitlementsWhereUniqueInput[]
  delete?: Prisma.reward_entitlementsWhereUniqueInput | Prisma.reward_entitlementsWhereUniqueInput[]
  connect?: Prisma.reward_entitlementsWhereUniqueInput | Prisma.reward_entitlementsWhereUniqueInput[]
  update?: Prisma.reward_entitlementsUpdateWithWhereUniqueWithoutWaitlistInput | Prisma.reward_entitlementsUpdateWithWhereUniqueWithoutWaitlistInput[]
  updateMany?: Prisma.reward_entitlementsUpdateManyWithWhereWithoutWaitlistInput | Prisma.reward_entitlementsUpdateManyWithWhereWithoutWaitlistInput[]
  deleteMany?: Prisma.reward_entitlementsScalarWhereInput | Prisma.reward_entitlementsScalarWhereInput[]
}

export type reward_entitlementsCreateNestedManyWithoutReward_catalogInput = {
  create?: Prisma.XOR<Prisma.reward_entitlementsCreateWithoutReward_catalogInput, Prisma.reward_entitlementsUncheckedCreateWithoutReward_catalogInput> | Prisma.reward_entitlementsCreateWithoutReward_catalogInput[] | Prisma.reward_entitlementsUncheckedCreateWithoutReward_catalogInput[]
  connectOrCreate?: Prisma.reward_entitlementsCreateOrConnectWithoutReward_catalogInput | Prisma.reward_entitlementsCreateOrConnectWithoutReward_catalogInput[]
  createMany?: Prisma.reward_entitlementsCreateManyReward_catalogInputEnvelope
  connect?: Prisma.reward_entitlementsWhereUniqueInput | Prisma.reward_entitlementsWhereUniqueInput[]
}

export type reward_entitlementsUncheckedCreateNestedManyWithoutReward_catalogInput = {
  create?: Prisma.XOR<Prisma.reward_entitlementsCreateWithoutReward_catalogInput, Prisma.reward_entitlementsUncheckedCreateWithoutReward_catalogInput> | Prisma.reward_entitlementsCreateWithoutReward_catalogInput[] | Prisma.reward_entitlementsUncheckedCreateWithoutReward_catalogInput[]
  connectOrCreate?: Prisma.reward_entitlementsCreateOrConnectWithoutReward_catalogInput | Prisma.reward_entitlementsCreateOrConnectWithoutReward_catalogInput[]
  createMany?: Prisma.reward_entitlementsCreateManyReward_catalogInputEnvelope
  connect?: Prisma.reward_entitlementsWhereUniqueInput | Prisma.reward_entitlementsWhereUniqueInput[]
}

export type reward_entitlementsUpdateManyWithoutReward_catalogNestedInput = {
  create?: Prisma.XOR<Prisma.reward_entitlementsCreateWithoutReward_catalogInput, Prisma.reward_entitlementsUncheckedCreateWithoutReward_catalogInput> | Prisma.reward_entitlementsCreateWithoutReward_catalogInput[] | Prisma.reward_entitlementsUncheckedCreateWithoutReward_catalogInput[]
  connectOrCreate?: Prisma.reward_entitlementsCreateOrConnectWithoutReward_catalogInput | Prisma.reward_entitlementsCreateOrConnectWithoutReward_catalogInput[]
  upsert?: Prisma.reward_entitlementsUpsertWithWhereUniqueWithoutReward_catalogInput | Prisma.reward_entitlementsUpsertWithWhereUniqueWithoutReward_catalogInput[]
  createMany?: Prisma.reward_entitlementsCreateManyReward_catalogInputEnvelope
  set?: Prisma.reward_entitlementsWhereUniqueInput | Prisma.reward_entitlementsWhereUniqueInput[]
  disconnect?: Prisma.reward_entitlementsWhereUniqueInput | Prisma.reward_entitlementsWhereUniqueInput[]
  delete?: Prisma.reward_entitlementsWhereUniqueInput | Prisma.reward_entitlementsWhereUniqueInput[]
  connect?: Prisma.reward_entitlementsWhereUniqueInput | Prisma.reward_entitlementsWhereUniqueInput[]
  update?: Prisma.reward_entitlementsUpdateWithWhereUniqueWithoutReward_catalogInput | Prisma.reward_entitlementsUpdateWithWhereUniqueWithoutReward_catalogInput[]
  updateMany?: Prisma.reward_entitlementsUpdateManyWithWhereWithoutReward_catalogInput | Prisma.reward_entitlementsUpdateManyWithWhereWithoutReward_catalogInput[]
  deleteMany?: Prisma.reward_entitlementsScalarWhereInput | Prisma.reward_entitlementsScalarWhereInput[]
}

export type reward_entitlementsUncheckedUpdateManyWithoutReward_catalogNestedInput = {
  create?: Prisma.XOR<Prisma.reward_entitlementsCreateWithoutReward_catalogInput, Prisma.reward_entitlementsUncheckedCreateWithoutReward_catalogInput> | Prisma.reward_entitlementsCreateWithoutReward_catalogInput[] | Prisma.reward_entitlementsUncheckedCreateWithoutReward_catalogInput[]
  connectOrCreate?: Prisma.reward_entitlementsCreateOrConnectWithoutReward_catalogInput | Prisma.reward_entitlementsCreateOrConnectWithoutReward_catalogInput[]
  upsert?: Prisma.reward_entitlementsUpsertWithWhereUniqueWithoutReward_catalogInput | Prisma.reward_entitlementsUpsertWithWhereUniqueWithoutReward_catalogInput[]
  createMany?: Prisma.reward_entitlementsCreateManyReward_catalogInputEnvelope
  set?: Prisma.reward_entitlementsWhereUniqueInput | Prisma.reward_entitlementsWhereUniqueInput[]
  disconnect?: Prisma.reward_entitlementsWhereUniqueInput | Prisma.reward_entitlementsWhereUniqueInput[]
  delete?: Prisma.reward_entitlementsWhereUniqueInput | Prisma.reward_entitlementsWhereUniqueInput[]
  connect?: Prisma.reward_entitlementsWhereUniqueInput | Prisma.reward_entitlementsWhereUniqueInput[]
  update?: Prisma.reward_entitlementsUpdateWithWhereUniqueWithoutReward_catalogInput | Prisma.reward_entitlementsUpdateWithWhereUniqueWithoutReward_catalogInput[]
  updateMany?: Prisma.reward_entitlementsUpdateManyWithWhereWithoutReward_catalogInput | Prisma.reward_entitlementsUpdateManyWithWhereWithoutReward_catalogInput[]
  deleteMany?: Prisma.reward_entitlementsScalarWhereInput | Prisma.reward_entitlementsScalarWhereInput[]
}

export type reward_entitlementsCreateNestedOneWithoutReward_redemptionsInput = {
  create?: Prisma.XOR<Prisma.reward_entitlementsCreateWithoutReward_redemptionsInput, Prisma.reward_entitlementsUncheckedCreateWithoutReward_redemptionsInput>
  connectOrCreate?: Prisma.reward_entitlementsCreateOrConnectWithoutReward_redemptionsInput
  connect?: Prisma.reward_entitlementsWhereUniqueInput
}

export type reward_entitlementsUpdateOneRequiredWithoutReward_redemptionsNestedInput = {
  create?: Prisma.XOR<Prisma.reward_entitlementsCreateWithoutReward_redemptionsInput, Prisma.reward_entitlementsUncheckedCreateWithoutReward_redemptionsInput>
  connectOrCreate?: Prisma.reward_entitlementsCreateOrConnectWithoutReward_redemptionsInput
  upsert?: Prisma.reward_entitlementsUpsertWithoutReward_redemptionsInput
  connect?: Prisma.reward_entitlementsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.reward_entitlementsUpdateToOneWithWhereWithoutReward_redemptionsInput, Prisma.reward_entitlementsUpdateWithoutReward_redemptionsInput>, Prisma.reward_entitlementsUncheckedUpdateWithoutReward_redemptionsInput>
}

export type reward_entitlementsCreateWithoutProfilesInput = {
  id?: string
  user_email: string
  source_event: string
  source_referral_count?: number | null
  status?: string
  granted_at?: Date | string
  expires_at?: Date | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  reward_catalog: Prisma.reward_catalogCreateNestedOneWithoutReward_entitlementsInput
  waitlist?: Prisma.waitlistCreateNestedOneWithoutReward_entitlementsInput
  reward_redemptions?: Prisma.reward_redemptionsCreateNestedManyWithoutReward_entitlementsInput
}

export type reward_entitlementsUncheckedCreateWithoutProfilesInput = {
  id?: string
  user_email: string
  waitlist_id?: string | null
  reward_key: string
  source_event: string
  source_referral_count?: number | null
  status?: string
  granted_at?: Date | string
  expires_at?: Date | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  reward_redemptions?: Prisma.reward_redemptionsUncheckedCreateNestedManyWithoutReward_entitlementsInput
}

export type reward_entitlementsCreateOrConnectWithoutProfilesInput = {
  where: Prisma.reward_entitlementsWhereUniqueInput
  create: Prisma.XOR<Prisma.reward_entitlementsCreateWithoutProfilesInput, Prisma.reward_entitlementsUncheckedCreateWithoutProfilesInput>
}

export type reward_entitlementsCreateManyProfilesInputEnvelope = {
  data: Prisma.reward_entitlementsCreateManyProfilesInput | Prisma.reward_entitlementsCreateManyProfilesInput[]
  skipDuplicates?: boolean
}

export type reward_entitlementsUpsertWithWhereUniqueWithoutProfilesInput = {
  where: Prisma.reward_entitlementsWhereUniqueInput
  update: Prisma.XOR<Prisma.reward_entitlementsUpdateWithoutProfilesInput, Prisma.reward_entitlementsUncheckedUpdateWithoutProfilesInput>
  create: Prisma.XOR<Prisma.reward_entitlementsCreateWithoutProfilesInput, Prisma.reward_entitlementsUncheckedCreateWithoutProfilesInput>
}

export type reward_entitlementsUpdateWithWhereUniqueWithoutProfilesInput = {
  where: Prisma.reward_entitlementsWhereUniqueInput
  data: Prisma.XOR<Prisma.reward_entitlementsUpdateWithoutProfilesInput, Prisma.reward_entitlementsUncheckedUpdateWithoutProfilesInput>
}

export type reward_entitlementsUpdateManyWithWhereWithoutProfilesInput = {
  where: Prisma.reward_entitlementsScalarWhereInput
  data: Prisma.XOR<Prisma.reward_entitlementsUpdateManyMutationInput, Prisma.reward_entitlementsUncheckedUpdateManyWithoutProfilesInput>
}

export type reward_entitlementsScalarWhereInput = {
  AND?: Prisma.reward_entitlementsScalarWhereInput | Prisma.reward_entitlementsScalarWhereInput[]
  OR?: Prisma.reward_entitlementsScalarWhereInput[]
  NOT?: Prisma.reward_entitlementsScalarWhereInput | Prisma.reward_entitlementsScalarWhereInput[]
  id?: Prisma.UuidFilter<"reward_entitlements"> | string
  user_email?: Prisma.StringFilter<"reward_entitlements"> | string
  waitlist_id?: Prisma.UuidNullableFilter<"reward_entitlements"> | string | null
  profile_id?: Prisma.UuidNullableFilter<"reward_entitlements"> | string | null
  reward_key?: Prisma.StringFilter<"reward_entitlements"> | string
  source_event?: Prisma.StringFilter<"reward_entitlements"> | string
  source_referral_count?: Prisma.IntNullableFilter<"reward_entitlements"> | number | null
  status?: Prisma.StringFilter<"reward_entitlements"> | string
  granted_at?: Prisma.DateTimeFilter<"reward_entitlements"> | Date | string
  expires_at?: Prisma.DateTimeNullableFilter<"reward_entitlements"> | Date | string | null
  metadata?: Prisma.JsonFilter<"reward_entitlements">
}

export type reward_entitlementsCreateWithoutWaitlistInput = {
  id?: string
  user_email: string
  source_event: string
  source_referral_count?: number | null
  status?: string
  granted_at?: Date | string
  expires_at?: Date | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  profiles?: Prisma.profilesCreateNestedOneWithoutReward_entitlementsInput
  reward_catalog: Prisma.reward_catalogCreateNestedOneWithoutReward_entitlementsInput
  reward_redemptions?: Prisma.reward_redemptionsCreateNestedManyWithoutReward_entitlementsInput
}

export type reward_entitlementsUncheckedCreateWithoutWaitlistInput = {
  id?: string
  user_email: string
  profile_id?: string | null
  reward_key: string
  source_event: string
  source_referral_count?: number | null
  status?: string
  granted_at?: Date | string
  expires_at?: Date | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  reward_redemptions?: Prisma.reward_redemptionsUncheckedCreateNestedManyWithoutReward_entitlementsInput
}

export type reward_entitlementsCreateOrConnectWithoutWaitlistInput = {
  where: Prisma.reward_entitlementsWhereUniqueInput
  create: Prisma.XOR<Prisma.reward_entitlementsCreateWithoutWaitlistInput, Prisma.reward_entitlementsUncheckedCreateWithoutWaitlistInput>
}

export type reward_entitlementsCreateManyWaitlistInputEnvelope = {
  data: Prisma.reward_entitlementsCreateManyWaitlistInput | Prisma.reward_entitlementsCreateManyWaitlistInput[]
  skipDuplicates?: boolean
}

export type reward_entitlementsUpsertWithWhereUniqueWithoutWaitlistInput = {
  where: Prisma.reward_entitlementsWhereUniqueInput
  update: Prisma.XOR<Prisma.reward_entitlementsUpdateWithoutWaitlistInput, Prisma.reward_entitlementsUncheckedUpdateWithoutWaitlistInput>
  create: Prisma.XOR<Prisma.reward_entitlementsCreateWithoutWaitlistInput, Prisma.reward_entitlementsUncheckedCreateWithoutWaitlistInput>
}

export type reward_entitlementsUpdateWithWhereUniqueWithoutWaitlistInput = {
  where: Prisma.reward_entitlementsWhereUniqueInput
  data: Prisma.XOR<Prisma.reward_entitlementsUpdateWithoutWaitlistInput, Prisma.reward_entitlementsUncheckedUpdateWithoutWaitlistInput>
}

export type reward_entitlementsUpdateManyWithWhereWithoutWaitlistInput = {
  where: Prisma.reward_entitlementsScalarWhereInput
  data: Prisma.XOR<Prisma.reward_entitlementsUpdateManyMutationInput, Prisma.reward_entitlementsUncheckedUpdateManyWithoutWaitlistInput>
}

export type reward_entitlementsCreateWithoutReward_catalogInput = {
  id?: string
  user_email: string
  source_event: string
  source_referral_count?: number | null
  status?: string
  granted_at?: Date | string
  expires_at?: Date | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  profiles?: Prisma.profilesCreateNestedOneWithoutReward_entitlementsInput
  waitlist?: Prisma.waitlistCreateNestedOneWithoutReward_entitlementsInput
  reward_redemptions?: Prisma.reward_redemptionsCreateNestedManyWithoutReward_entitlementsInput
}

export type reward_entitlementsUncheckedCreateWithoutReward_catalogInput = {
  id?: string
  user_email: string
  waitlist_id?: string | null
  profile_id?: string | null
  source_event: string
  source_referral_count?: number | null
  status?: string
  granted_at?: Date | string
  expires_at?: Date | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  reward_redemptions?: Prisma.reward_redemptionsUncheckedCreateNestedManyWithoutReward_entitlementsInput
}

export type reward_entitlementsCreateOrConnectWithoutReward_catalogInput = {
  where: Prisma.reward_entitlementsWhereUniqueInput
  create: Prisma.XOR<Prisma.reward_entitlementsCreateWithoutReward_catalogInput, Prisma.reward_entitlementsUncheckedCreateWithoutReward_catalogInput>
}

export type reward_entitlementsCreateManyReward_catalogInputEnvelope = {
  data: Prisma.reward_entitlementsCreateManyReward_catalogInput | Prisma.reward_entitlementsCreateManyReward_catalogInput[]
  skipDuplicates?: boolean
}

export type reward_entitlementsUpsertWithWhereUniqueWithoutReward_catalogInput = {
  where: Prisma.reward_entitlementsWhereUniqueInput
  update: Prisma.XOR<Prisma.reward_entitlementsUpdateWithoutReward_catalogInput, Prisma.reward_entitlementsUncheckedUpdateWithoutReward_catalogInput>
  create: Prisma.XOR<Prisma.reward_entitlementsCreateWithoutReward_catalogInput, Prisma.reward_entitlementsUncheckedCreateWithoutReward_catalogInput>
}

export type reward_entitlementsUpdateWithWhereUniqueWithoutReward_catalogInput = {
  where: Prisma.reward_entitlementsWhereUniqueInput
  data: Prisma.XOR<Prisma.reward_entitlementsUpdateWithoutReward_catalogInput, Prisma.reward_entitlementsUncheckedUpdateWithoutReward_catalogInput>
}

export type reward_entitlementsUpdateManyWithWhereWithoutReward_catalogInput = {
  where: Prisma.reward_entitlementsScalarWhereInput
  data: Prisma.XOR<Prisma.reward_entitlementsUpdateManyMutationInput, Prisma.reward_entitlementsUncheckedUpdateManyWithoutReward_catalogInput>
}

export type reward_entitlementsCreateWithoutReward_redemptionsInput = {
  id?: string
  user_email: string
  source_event: string
  source_referral_count?: number | null
  status?: string
  granted_at?: Date | string
  expires_at?: Date | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  profiles?: Prisma.profilesCreateNestedOneWithoutReward_entitlementsInput
  reward_catalog: Prisma.reward_catalogCreateNestedOneWithoutReward_entitlementsInput
  waitlist?: Prisma.waitlistCreateNestedOneWithoutReward_entitlementsInput
}

export type reward_entitlementsUncheckedCreateWithoutReward_redemptionsInput = {
  id?: string
  user_email: string
  waitlist_id?: string | null
  profile_id?: string | null
  reward_key: string
  source_event: string
  source_referral_count?: number | null
  status?: string
  granted_at?: Date | string
  expires_at?: Date | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type reward_entitlementsCreateOrConnectWithoutReward_redemptionsInput = {
  where: Prisma.reward_entitlementsWhereUniqueInput
  create: Prisma.XOR<Prisma.reward_entitlementsCreateWithoutReward_redemptionsInput, Prisma.reward_entitlementsUncheckedCreateWithoutReward_redemptionsInput>
}

export type reward_entitlementsUpsertWithoutReward_redemptionsInput = {
  update: Prisma.XOR<Prisma.reward_entitlementsUpdateWithoutReward_redemptionsInput, Prisma.reward_entitlementsUncheckedUpdateWithoutReward_redemptionsInput>
  create: Prisma.XOR<Prisma.reward_entitlementsCreateWithoutReward_redemptionsInput, Prisma.reward_entitlementsUncheckedCreateWithoutReward_redemptionsInput>
  where?: Prisma.reward_entitlementsWhereInput
}

export type reward_entitlementsUpdateToOneWithWhereWithoutReward_redemptionsInput = {
  where?: Prisma.reward_entitlementsWhereInput
  data: Prisma.XOR<Prisma.reward_entitlementsUpdateWithoutReward_redemptionsInput, Prisma.reward_entitlementsUncheckedUpdateWithoutReward_redemptionsInput>
}

export type reward_entitlementsUpdateWithoutReward_redemptionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_email?: Prisma.StringFieldUpdateOperationsInput | string
  source_event?: Prisma.StringFieldUpdateOperationsInput | string
  source_referral_count?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  granted_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  profiles?: Prisma.profilesUpdateOneWithoutReward_entitlementsNestedInput
  reward_catalog?: Prisma.reward_catalogUpdateOneRequiredWithoutReward_entitlementsNestedInput
  waitlist?: Prisma.waitlistUpdateOneWithoutReward_entitlementsNestedInput
}

export type reward_entitlementsUncheckedUpdateWithoutReward_redemptionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_email?: Prisma.StringFieldUpdateOperationsInput | string
  waitlist_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profile_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reward_key?: Prisma.StringFieldUpdateOperationsInput | string
  source_event?: Prisma.StringFieldUpdateOperationsInput | string
  source_referral_count?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  granted_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type reward_entitlementsCreateManyProfilesInput = {
  id?: string
  user_email: string
  waitlist_id?: string | null
  reward_key: string
  source_event: string
  source_referral_count?: number | null
  status?: string
  granted_at?: Date | string
  expires_at?: Date | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type reward_entitlementsUpdateWithoutProfilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_email?: Prisma.StringFieldUpdateOperationsInput | string
  source_event?: Prisma.StringFieldUpdateOperationsInput | string
  source_referral_count?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  granted_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  reward_catalog?: Prisma.reward_catalogUpdateOneRequiredWithoutReward_entitlementsNestedInput
  waitlist?: Prisma.waitlistUpdateOneWithoutReward_entitlementsNestedInput
  reward_redemptions?: Prisma.reward_redemptionsUpdateManyWithoutReward_entitlementsNestedInput
}

export type reward_entitlementsUncheckedUpdateWithoutProfilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_email?: Prisma.StringFieldUpdateOperationsInput | string
  waitlist_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reward_key?: Prisma.StringFieldUpdateOperationsInput | string
  source_event?: Prisma.StringFieldUpdateOperationsInput | string
  source_referral_count?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  granted_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  reward_redemptions?: Prisma.reward_redemptionsUncheckedUpdateManyWithoutReward_entitlementsNestedInput
}

export type reward_entitlementsUncheckedUpdateManyWithoutProfilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_email?: Prisma.StringFieldUpdateOperationsInput | string
  waitlist_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reward_key?: Prisma.StringFieldUpdateOperationsInput | string
  source_event?: Prisma.StringFieldUpdateOperationsInput | string
  source_referral_count?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  granted_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type reward_entitlementsCreateManyWaitlistInput = {
  id?: string
  user_email: string
  profile_id?: string | null
  reward_key: string
  source_event: string
  source_referral_count?: number | null
  status?: string
  granted_at?: Date | string
  expires_at?: Date | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type reward_entitlementsUpdateWithoutWaitlistInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_email?: Prisma.StringFieldUpdateOperationsInput | string
  source_event?: Prisma.StringFieldUpdateOperationsInput | string
  source_referral_count?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  granted_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  profiles?: Prisma.profilesUpdateOneWithoutReward_entitlementsNestedInput
  reward_catalog?: Prisma.reward_catalogUpdateOneRequiredWithoutReward_entitlementsNestedInput
  reward_redemptions?: Prisma.reward_redemptionsUpdateManyWithoutReward_entitlementsNestedInput
}

export type reward_entitlementsUncheckedUpdateWithoutWaitlistInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_email?: Prisma.StringFieldUpdateOperationsInput | string
  profile_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reward_key?: Prisma.StringFieldUpdateOperationsInput | string
  source_event?: Prisma.StringFieldUpdateOperationsInput | string
  source_referral_count?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  granted_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  reward_redemptions?: Prisma.reward_redemptionsUncheckedUpdateManyWithoutReward_entitlementsNestedInput
}

export type reward_entitlementsUncheckedUpdateManyWithoutWaitlistInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_email?: Prisma.StringFieldUpdateOperationsInput | string
  profile_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reward_key?: Prisma.StringFieldUpdateOperationsInput | string
  source_event?: Prisma.StringFieldUpdateOperationsInput | string
  source_referral_count?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  granted_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type reward_entitlementsCreateManyReward_catalogInput = {
  id?: string
  user_email: string
  waitlist_id?: string | null
  profile_id?: string | null
  source_event: string
  source_referral_count?: number | null
  status?: string
  granted_at?: Date | string
  expires_at?: Date | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}

export type reward_entitlementsUpdateWithoutReward_catalogInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_email?: Prisma.StringFieldUpdateOperationsInput | string
  source_event?: Prisma.StringFieldUpdateOperationsInput | string
  source_referral_count?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  granted_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  profiles?: Prisma.profilesUpdateOneWithoutReward_entitlementsNestedInput
  waitlist?: Prisma.waitlistUpdateOneWithoutReward_entitlementsNestedInput
  reward_redemptions?: Prisma.reward_redemptionsUpdateManyWithoutReward_entitlementsNestedInput
}

export type reward_entitlementsUncheckedUpdateWithoutReward_catalogInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_email?: Prisma.StringFieldUpdateOperationsInput | string
  waitlist_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profile_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source_event?: Prisma.StringFieldUpdateOperationsInput | string
  source_referral_count?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  granted_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  reward_redemptions?: Prisma.reward_redemptionsUncheckedUpdateManyWithoutReward_entitlementsNestedInput
}

export type reward_entitlementsUncheckedUpdateManyWithoutReward_catalogInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_email?: Prisma.StringFieldUpdateOperationsInput | string
  waitlist_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profile_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source_event?: Prisma.StringFieldUpdateOperationsInput | string
  source_referral_count?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  granted_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
}


/**
 * Count Type Reward_entitlementsCountOutputType
 */

export type Reward_entitlementsCountOutputType = {
  reward_redemptions: number
}

export type Reward_entitlementsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  reward_redemptions?: boolean | Reward_entitlementsCountOutputTypeCountReward_redemptionsArgs
}

/**
 * Reward_entitlementsCountOutputType without action
 */
export type Reward_entitlementsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reward_entitlementsCountOutputType
   */
  select?: Prisma.Reward_entitlementsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * Reward_entitlementsCountOutputType without action
 */
export type Reward_entitlementsCountOutputTypeCountReward_redemptionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.reward_redemptionsWhereInput
}


export type reward_entitlementsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_email?: boolean
  waitlist_id?: boolean
  profile_id?: boolean
  reward_key?: boolean
  source_event?: boolean
  source_referral_count?: boolean
  status?: boolean
  granted_at?: boolean
  expires_at?: boolean
  metadata?: boolean
  profiles?: boolean | Prisma.reward_entitlements$profilesArgs<ExtArgs>
  reward_catalog?: boolean | Prisma.reward_catalogDefaultArgs<ExtArgs>
  waitlist?: boolean | Prisma.reward_entitlements$waitlistArgs<ExtArgs>
  reward_redemptions?: boolean | Prisma.reward_entitlements$reward_redemptionsArgs<ExtArgs>
  _count?: boolean | Prisma.Reward_entitlementsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["reward_entitlements"]>

export type reward_entitlementsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_email?: boolean
  waitlist_id?: boolean
  profile_id?: boolean
  reward_key?: boolean
  source_event?: boolean
  source_referral_count?: boolean
  status?: boolean
  granted_at?: boolean
  expires_at?: boolean
  metadata?: boolean
  profiles?: boolean | Prisma.reward_entitlements$profilesArgs<ExtArgs>
  reward_catalog?: boolean | Prisma.reward_catalogDefaultArgs<ExtArgs>
  waitlist?: boolean | Prisma.reward_entitlements$waitlistArgs<ExtArgs>
}, ExtArgs["result"]["reward_entitlements"]>

export type reward_entitlementsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_email?: boolean
  waitlist_id?: boolean
  profile_id?: boolean
  reward_key?: boolean
  source_event?: boolean
  source_referral_count?: boolean
  status?: boolean
  granted_at?: boolean
  expires_at?: boolean
  metadata?: boolean
  profiles?: boolean | Prisma.reward_entitlements$profilesArgs<ExtArgs>
  reward_catalog?: boolean | Prisma.reward_catalogDefaultArgs<ExtArgs>
  waitlist?: boolean | Prisma.reward_entitlements$waitlistArgs<ExtArgs>
}, ExtArgs["result"]["reward_entitlements"]>

export type reward_entitlementsSelectScalar = {
  id?: boolean
  user_email?: boolean
  waitlist_id?: boolean
  profile_id?: boolean
  reward_key?: boolean
  source_event?: boolean
  source_referral_count?: boolean
  status?: boolean
  granted_at?: boolean
  expires_at?: boolean
  metadata?: boolean
}

export type reward_entitlementsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "user_email" | "waitlist_id" | "profile_id" | "reward_key" | "source_event" | "source_referral_count" | "status" | "granted_at" | "expires_at" | "metadata", ExtArgs["result"]["reward_entitlements"]>
export type reward_entitlementsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profiles?: boolean | Prisma.reward_entitlements$profilesArgs<ExtArgs>
  reward_catalog?: boolean | Prisma.reward_catalogDefaultArgs<ExtArgs>
  waitlist?: boolean | Prisma.reward_entitlements$waitlistArgs<ExtArgs>
  reward_redemptions?: boolean | Prisma.reward_entitlements$reward_redemptionsArgs<ExtArgs>
  _count?: boolean | Prisma.Reward_entitlementsCountOutputTypeDefaultArgs<ExtArgs>
}
export type reward_entitlementsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profiles?: boolean | Prisma.reward_entitlements$profilesArgs<ExtArgs>
  reward_catalog?: boolean | Prisma.reward_catalogDefaultArgs<ExtArgs>
  waitlist?: boolean | Prisma.reward_entitlements$waitlistArgs<ExtArgs>
}
export type reward_entitlementsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profiles?: boolean | Prisma.reward_entitlements$profilesArgs<ExtArgs>
  reward_catalog?: boolean | Prisma.reward_catalogDefaultArgs<ExtArgs>
  waitlist?: boolean | Prisma.reward_entitlements$waitlistArgs<ExtArgs>
}

export type $reward_entitlementsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "reward_entitlements"
  objects: {
    profiles: Prisma.$profilesPayload<ExtArgs> | null
    reward_catalog: Prisma.$reward_catalogPayload<ExtArgs>
    waitlist: Prisma.$waitlistPayload<ExtArgs> | null
    reward_redemptions: Prisma.$reward_redemptionsPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    user_email: string
    waitlist_id: string | null
    profile_id: string | null
    reward_key: string
    source_event: string
    source_referral_count: number | null
    status: string
    granted_at: Date
    expires_at: Date | null
    metadata: runtime.JsonValue
  }, ExtArgs["result"]["reward_entitlements"]>
  composites: {}
}

export type reward_entitlementsGetPayload<S extends boolean | null | undefined | reward_entitlementsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$reward_entitlementsPayload, S>

export type reward_entitlementsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<reward_entitlementsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Reward_entitlementsCountAggregateInputType | true
  }

export interface reward_entitlementsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['reward_entitlements'], meta: { name: 'reward_entitlements' } }
  /**
   * Find zero or one Reward_entitlements that matches the filter.
   * @param {reward_entitlementsFindUniqueArgs} args - Arguments to find a Reward_entitlements
   * @example
   * // Get one Reward_entitlements
   * const reward_entitlements = await prisma.reward_entitlements.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends reward_entitlementsFindUniqueArgs>(args: Prisma.SelectSubset<T, reward_entitlementsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__reward_entitlementsClient<runtime.Types.Result.GetResult<Prisma.$reward_entitlementsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Reward_entitlements that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {reward_entitlementsFindUniqueOrThrowArgs} args - Arguments to find a Reward_entitlements
   * @example
   * // Get one Reward_entitlements
   * const reward_entitlements = await prisma.reward_entitlements.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends reward_entitlementsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, reward_entitlementsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__reward_entitlementsClient<runtime.Types.Result.GetResult<Prisma.$reward_entitlementsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Reward_entitlements that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {reward_entitlementsFindFirstArgs} args - Arguments to find a Reward_entitlements
   * @example
   * // Get one Reward_entitlements
   * const reward_entitlements = await prisma.reward_entitlements.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends reward_entitlementsFindFirstArgs>(args?: Prisma.SelectSubset<T, reward_entitlementsFindFirstArgs<ExtArgs>>): Prisma.Prisma__reward_entitlementsClient<runtime.Types.Result.GetResult<Prisma.$reward_entitlementsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Reward_entitlements that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {reward_entitlementsFindFirstOrThrowArgs} args - Arguments to find a Reward_entitlements
   * @example
   * // Get one Reward_entitlements
   * const reward_entitlements = await prisma.reward_entitlements.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends reward_entitlementsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, reward_entitlementsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__reward_entitlementsClient<runtime.Types.Result.GetResult<Prisma.$reward_entitlementsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Reward_entitlements that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {reward_entitlementsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Reward_entitlements
   * const reward_entitlements = await prisma.reward_entitlements.findMany()
   * 
   * // Get first 10 Reward_entitlements
   * const reward_entitlements = await prisma.reward_entitlements.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const reward_entitlementsWithIdOnly = await prisma.reward_entitlements.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends reward_entitlementsFindManyArgs>(args?: Prisma.SelectSubset<T, reward_entitlementsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$reward_entitlementsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Reward_entitlements.
   * @param {reward_entitlementsCreateArgs} args - Arguments to create a Reward_entitlements.
   * @example
   * // Create one Reward_entitlements
   * const Reward_entitlements = await prisma.reward_entitlements.create({
   *   data: {
   *     // ... data to create a Reward_entitlements
   *   }
   * })
   * 
   */
  create<T extends reward_entitlementsCreateArgs>(args: Prisma.SelectSubset<T, reward_entitlementsCreateArgs<ExtArgs>>): Prisma.Prisma__reward_entitlementsClient<runtime.Types.Result.GetResult<Prisma.$reward_entitlementsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Reward_entitlements.
   * @param {reward_entitlementsCreateManyArgs} args - Arguments to create many Reward_entitlements.
   * @example
   * // Create many Reward_entitlements
   * const reward_entitlements = await prisma.reward_entitlements.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends reward_entitlementsCreateManyArgs>(args?: Prisma.SelectSubset<T, reward_entitlementsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Reward_entitlements and returns the data saved in the database.
   * @param {reward_entitlementsCreateManyAndReturnArgs} args - Arguments to create many Reward_entitlements.
   * @example
   * // Create many Reward_entitlements
   * const reward_entitlements = await prisma.reward_entitlements.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Reward_entitlements and only return the `id`
   * const reward_entitlementsWithIdOnly = await prisma.reward_entitlements.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends reward_entitlementsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, reward_entitlementsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$reward_entitlementsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Reward_entitlements.
   * @param {reward_entitlementsDeleteArgs} args - Arguments to delete one Reward_entitlements.
   * @example
   * // Delete one Reward_entitlements
   * const Reward_entitlements = await prisma.reward_entitlements.delete({
   *   where: {
   *     // ... filter to delete one Reward_entitlements
   *   }
   * })
   * 
   */
  delete<T extends reward_entitlementsDeleteArgs>(args: Prisma.SelectSubset<T, reward_entitlementsDeleteArgs<ExtArgs>>): Prisma.Prisma__reward_entitlementsClient<runtime.Types.Result.GetResult<Prisma.$reward_entitlementsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Reward_entitlements.
   * @param {reward_entitlementsUpdateArgs} args - Arguments to update one Reward_entitlements.
   * @example
   * // Update one Reward_entitlements
   * const reward_entitlements = await prisma.reward_entitlements.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends reward_entitlementsUpdateArgs>(args: Prisma.SelectSubset<T, reward_entitlementsUpdateArgs<ExtArgs>>): Prisma.Prisma__reward_entitlementsClient<runtime.Types.Result.GetResult<Prisma.$reward_entitlementsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Reward_entitlements.
   * @param {reward_entitlementsDeleteManyArgs} args - Arguments to filter Reward_entitlements to delete.
   * @example
   * // Delete a few Reward_entitlements
   * const { count } = await prisma.reward_entitlements.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends reward_entitlementsDeleteManyArgs>(args?: Prisma.SelectSubset<T, reward_entitlementsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Reward_entitlements.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {reward_entitlementsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Reward_entitlements
   * const reward_entitlements = await prisma.reward_entitlements.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends reward_entitlementsUpdateManyArgs>(args: Prisma.SelectSubset<T, reward_entitlementsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Reward_entitlements and returns the data updated in the database.
   * @param {reward_entitlementsUpdateManyAndReturnArgs} args - Arguments to update many Reward_entitlements.
   * @example
   * // Update many Reward_entitlements
   * const reward_entitlements = await prisma.reward_entitlements.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Reward_entitlements and only return the `id`
   * const reward_entitlementsWithIdOnly = await prisma.reward_entitlements.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends reward_entitlementsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, reward_entitlementsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$reward_entitlementsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Reward_entitlements.
   * @param {reward_entitlementsUpsertArgs} args - Arguments to update or create a Reward_entitlements.
   * @example
   * // Update or create a Reward_entitlements
   * const reward_entitlements = await prisma.reward_entitlements.upsert({
   *   create: {
   *     // ... data to create a Reward_entitlements
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Reward_entitlements we want to update
   *   }
   * })
   */
  upsert<T extends reward_entitlementsUpsertArgs>(args: Prisma.SelectSubset<T, reward_entitlementsUpsertArgs<ExtArgs>>): Prisma.Prisma__reward_entitlementsClient<runtime.Types.Result.GetResult<Prisma.$reward_entitlementsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Reward_entitlements.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {reward_entitlementsCountArgs} args - Arguments to filter Reward_entitlements to count.
   * @example
   * // Count the number of Reward_entitlements
   * const count = await prisma.reward_entitlements.count({
   *   where: {
   *     // ... the filter for the Reward_entitlements we want to count
   *   }
   * })
  **/
  count<T extends reward_entitlementsCountArgs>(
    args?: Prisma.Subset<T, reward_entitlementsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Reward_entitlementsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Reward_entitlements.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Reward_entitlementsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Reward_entitlementsAggregateArgs>(args: Prisma.Subset<T, Reward_entitlementsAggregateArgs>): Prisma.PrismaPromise<GetReward_entitlementsAggregateType<T>>

  /**
   * Group by Reward_entitlements.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {reward_entitlementsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends reward_entitlementsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: reward_entitlementsGroupByArgs['orderBy'] }
      : { orderBy?: reward_entitlementsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, reward_entitlementsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetReward_entitlementsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the reward_entitlements model
 */
readonly fields: reward_entitlementsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for reward_entitlements.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__reward_entitlementsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  profiles<T extends Prisma.reward_entitlements$profilesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.reward_entitlements$profilesArgs<ExtArgs>>): Prisma.Prisma__profilesClient<runtime.Types.Result.GetResult<Prisma.$profilesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  reward_catalog<T extends Prisma.reward_catalogDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.reward_catalogDefaultArgs<ExtArgs>>): Prisma.Prisma__reward_catalogClient<runtime.Types.Result.GetResult<Prisma.$reward_catalogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  waitlist<T extends Prisma.reward_entitlements$waitlistArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.reward_entitlements$waitlistArgs<ExtArgs>>): Prisma.Prisma__waitlistClient<runtime.Types.Result.GetResult<Prisma.$waitlistPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  reward_redemptions<T extends Prisma.reward_entitlements$reward_redemptionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.reward_entitlements$reward_redemptionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$reward_redemptionsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the reward_entitlements model
 */
export interface reward_entitlementsFieldRefs {
  readonly id: Prisma.FieldRef<"reward_entitlements", 'String'>
  readonly user_email: Prisma.FieldRef<"reward_entitlements", 'String'>
  readonly waitlist_id: Prisma.FieldRef<"reward_entitlements", 'String'>
  readonly profile_id: Prisma.FieldRef<"reward_entitlements", 'String'>
  readonly reward_key: Prisma.FieldRef<"reward_entitlements", 'String'>
  readonly source_event: Prisma.FieldRef<"reward_entitlements", 'String'>
  readonly source_referral_count: Prisma.FieldRef<"reward_entitlements", 'Int'>
  readonly status: Prisma.FieldRef<"reward_entitlements", 'String'>
  readonly granted_at: Prisma.FieldRef<"reward_entitlements", 'DateTime'>
  readonly expires_at: Prisma.FieldRef<"reward_entitlements", 'DateTime'>
  readonly metadata: Prisma.FieldRef<"reward_entitlements", 'Json'>
}
    

// Custom InputTypes
/**
 * reward_entitlements findUnique
 */
export type reward_entitlementsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_entitlements
   */
  select?: Prisma.reward_entitlementsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_entitlements
   */
  omit?: Prisma.reward_entitlementsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_entitlementsInclude<ExtArgs> | null
  /**
   * Filter, which reward_entitlements to fetch.
   */
  where: Prisma.reward_entitlementsWhereUniqueInput
}

/**
 * reward_entitlements findUniqueOrThrow
 */
export type reward_entitlementsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_entitlements
   */
  select?: Prisma.reward_entitlementsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_entitlements
   */
  omit?: Prisma.reward_entitlementsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_entitlementsInclude<ExtArgs> | null
  /**
   * Filter, which reward_entitlements to fetch.
   */
  where: Prisma.reward_entitlementsWhereUniqueInput
}

/**
 * reward_entitlements findFirst
 */
export type reward_entitlementsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_entitlements
   */
  select?: Prisma.reward_entitlementsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_entitlements
   */
  omit?: Prisma.reward_entitlementsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_entitlementsInclude<ExtArgs> | null
  /**
   * Filter, which reward_entitlements to fetch.
   */
  where?: Prisma.reward_entitlementsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of reward_entitlements to fetch.
   */
  orderBy?: Prisma.reward_entitlementsOrderByWithRelationInput | Prisma.reward_entitlementsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for reward_entitlements.
   */
  cursor?: Prisma.reward_entitlementsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` reward_entitlements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` reward_entitlements.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of reward_entitlements.
   */
  distinct?: Prisma.Reward_entitlementsScalarFieldEnum | Prisma.Reward_entitlementsScalarFieldEnum[]
}

/**
 * reward_entitlements findFirstOrThrow
 */
export type reward_entitlementsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_entitlements
   */
  select?: Prisma.reward_entitlementsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_entitlements
   */
  omit?: Prisma.reward_entitlementsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_entitlementsInclude<ExtArgs> | null
  /**
   * Filter, which reward_entitlements to fetch.
   */
  where?: Prisma.reward_entitlementsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of reward_entitlements to fetch.
   */
  orderBy?: Prisma.reward_entitlementsOrderByWithRelationInput | Prisma.reward_entitlementsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for reward_entitlements.
   */
  cursor?: Prisma.reward_entitlementsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` reward_entitlements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` reward_entitlements.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of reward_entitlements.
   */
  distinct?: Prisma.Reward_entitlementsScalarFieldEnum | Prisma.Reward_entitlementsScalarFieldEnum[]
}

/**
 * reward_entitlements findMany
 */
export type reward_entitlementsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_entitlements
   */
  select?: Prisma.reward_entitlementsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_entitlements
   */
  omit?: Prisma.reward_entitlementsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_entitlementsInclude<ExtArgs> | null
  /**
   * Filter, which reward_entitlements to fetch.
   */
  where?: Prisma.reward_entitlementsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of reward_entitlements to fetch.
   */
  orderBy?: Prisma.reward_entitlementsOrderByWithRelationInput | Prisma.reward_entitlementsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing reward_entitlements.
   */
  cursor?: Prisma.reward_entitlementsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` reward_entitlements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` reward_entitlements.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of reward_entitlements.
   */
  distinct?: Prisma.Reward_entitlementsScalarFieldEnum | Prisma.Reward_entitlementsScalarFieldEnum[]
}

/**
 * reward_entitlements create
 */
export type reward_entitlementsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_entitlements
   */
  select?: Prisma.reward_entitlementsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_entitlements
   */
  omit?: Prisma.reward_entitlementsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_entitlementsInclude<ExtArgs> | null
  /**
   * The data needed to create a reward_entitlements.
   */
  data: Prisma.XOR<Prisma.reward_entitlementsCreateInput, Prisma.reward_entitlementsUncheckedCreateInput>
}

/**
 * reward_entitlements createMany
 */
export type reward_entitlementsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many reward_entitlements.
   */
  data: Prisma.reward_entitlementsCreateManyInput | Prisma.reward_entitlementsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * reward_entitlements createManyAndReturn
 */
export type reward_entitlementsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_entitlements
   */
  select?: Prisma.reward_entitlementsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the reward_entitlements
   */
  omit?: Prisma.reward_entitlementsOmit<ExtArgs> | null
  /**
   * The data used to create many reward_entitlements.
   */
  data: Prisma.reward_entitlementsCreateManyInput | Prisma.reward_entitlementsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_entitlementsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * reward_entitlements update
 */
export type reward_entitlementsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_entitlements
   */
  select?: Prisma.reward_entitlementsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_entitlements
   */
  omit?: Prisma.reward_entitlementsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_entitlementsInclude<ExtArgs> | null
  /**
   * The data needed to update a reward_entitlements.
   */
  data: Prisma.XOR<Prisma.reward_entitlementsUpdateInput, Prisma.reward_entitlementsUncheckedUpdateInput>
  /**
   * Choose, which reward_entitlements to update.
   */
  where: Prisma.reward_entitlementsWhereUniqueInput
}

/**
 * reward_entitlements updateMany
 */
export type reward_entitlementsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update reward_entitlements.
   */
  data: Prisma.XOR<Prisma.reward_entitlementsUpdateManyMutationInput, Prisma.reward_entitlementsUncheckedUpdateManyInput>
  /**
   * Filter which reward_entitlements to update
   */
  where?: Prisma.reward_entitlementsWhereInput
  /**
   * Limit how many reward_entitlements to update.
   */
  limit?: number
}

/**
 * reward_entitlements updateManyAndReturn
 */
export type reward_entitlementsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_entitlements
   */
  select?: Prisma.reward_entitlementsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the reward_entitlements
   */
  omit?: Prisma.reward_entitlementsOmit<ExtArgs> | null
  /**
   * The data used to update reward_entitlements.
   */
  data: Prisma.XOR<Prisma.reward_entitlementsUpdateManyMutationInput, Prisma.reward_entitlementsUncheckedUpdateManyInput>
  /**
   * Filter which reward_entitlements to update
   */
  where?: Prisma.reward_entitlementsWhereInput
  /**
   * Limit how many reward_entitlements to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_entitlementsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * reward_entitlements upsert
 */
export type reward_entitlementsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_entitlements
   */
  select?: Prisma.reward_entitlementsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_entitlements
   */
  omit?: Prisma.reward_entitlementsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_entitlementsInclude<ExtArgs> | null
  /**
   * The filter to search for the reward_entitlements to update in case it exists.
   */
  where: Prisma.reward_entitlementsWhereUniqueInput
  /**
   * In case the reward_entitlements found by the `where` argument doesn't exist, create a new reward_entitlements with this data.
   */
  create: Prisma.XOR<Prisma.reward_entitlementsCreateInput, Prisma.reward_entitlementsUncheckedCreateInput>
  /**
   * In case the reward_entitlements was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.reward_entitlementsUpdateInput, Prisma.reward_entitlementsUncheckedUpdateInput>
}

/**
 * reward_entitlements delete
 */
export type reward_entitlementsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_entitlements
   */
  select?: Prisma.reward_entitlementsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_entitlements
   */
  omit?: Prisma.reward_entitlementsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_entitlementsInclude<ExtArgs> | null
  /**
   * Filter which reward_entitlements to delete.
   */
  where: Prisma.reward_entitlementsWhereUniqueInput
}

/**
 * reward_entitlements deleteMany
 */
export type reward_entitlementsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which reward_entitlements to delete
   */
  where?: Prisma.reward_entitlementsWhereInput
  /**
   * Limit how many reward_entitlements to delete.
   */
  limit?: number
}

/**
 * reward_entitlements.profiles
 */
export type reward_entitlements$profilesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the profiles
   */
  select?: Prisma.profilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the profiles
   */
  omit?: Prisma.profilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.profilesInclude<ExtArgs> | null
  where?: Prisma.profilesWhereInput
}

/**
 * reward_entitlements.waitlist
 */
export type reward_entitlements$waitlistArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the waitlist
   */
  select?: Prisma.waitlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the waitlist
   */
  omit?: Prisma.waitlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.waitlistInclude<ExtArgs> | null
  where?: Prisma.waitlistWhereInput
}

/**
 * reward_entitlements.reward_redemptions
 */
export type reward_entitlements$reward_redemptionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_redemptions
   */
  select?: Prisma.reward_redemptionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_redemptions
   */
  omit?: Prisma.reward_redemptionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_redemptionsInclude<ExtArgs> | null
  where?: Prisma.reward_redemptionsWhereInput
  orderBy?: Prisma.reward_redemptionsOrderByWithRelationInput | Prisma.reward_redemptionsOrderByWithRelationInput[]
  cursor?: Prisma.reward_redemptionsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Reward_redemptionsScalarFieldEnum | Prisma.Reward_redemptionsScalarFieldEnum[]
}

/**
 * reward_entitlements without action
 */
export type reward_entitlementsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_entitlements
   */
  select?: Prisma.reward_entitlementsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_entitlements
   */
  omit?: Prisma.reward_entitlementsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_entitlementsInclude<ExtArgs> | null
}
