
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `reward_catalog` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model reward_catalog
 * This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info.
 */
export type reward_catalogModel = runtime.Types.Result.DefaultSelection<Prisma.$reward_catalogPayload>

export type AggregateReward_catalog = {
  _count: Reward_catalogCountAggregateOutputType | null
  _min: Reward_catalogMinAggregateOutputType | null
  _max: Reward_catalogMaxAggregateOutputType | null
}

export type Reward_catalogMinAggregateOutputType = {
  id: string | null
  key: string | null
  name: string | null
  reward_system: string | null
  description: string | null
  is_redeemable: boolean | null
  created_at: Date | null
}

export type Reward_catalogMaxAggregateOutputType = {
  id: string | null
  key: string | null
  name: string | null
  reward_system: string | null
  description: string | null
  is_redeemable: boolean | null
  created_at: Date | null
}

export type Reward_catalogCountAggregateOutputType = {
  id: number
  key: number
  name: number
  reward_system: number
  description: number
  is_redeemable: number
  metadata: number
  created_at: number
  _all: number
}


export type Reward_catalogMinAggregateInputType = {
  id?: true
  key?: true
  name?: true
  reward_system?: true
  description?: true
  is_redeemable?: true
  created_at?: true
}

export type Reward_catalogMaxAggregateInputType = {
  id?: true
  key?: true
  name?: true
  reward_system?: true
  description?: true
  is_redeemable?: true
  created_at?: true
}

export type Reward_catalogCountAggregateInputType = {
  id?: true
  key?: true
  name?: true
  reward_system?: true
  description?: true
  is_redeemable?: true
  metadata?: true
  created_at?: true
  _all?: true
}

export type Reward_catalogAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which reward_catalog to aggregate.
   */
  where?: Prisma.reward_catalogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of reward_catalogs to fetch.
   */
  orderBy?: Prisma.reward_catalogOrderByWithRelationInput | Prisma.reward_catalogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.reward_catalogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` reward_catalogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` reward_catalogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned reward_catalogs
  **/
  _count?: true | Reward_catalogCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Reward_catalogMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Reward_catalogMaxAggregateInputType
}

export type GetReward_catalogAggregateType<T extends Reward_catalogAggregateArgs> = {
      [P in keyof T & keyof AggregateReward_catalog]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateReward_catalog[P]>
    : Prisma.GetScalarType<T[P], AggregateReward_catalog[P]>
}




export type reward_catalogGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.reward_catalogWhereInput
  orderBy?: Prisma.reward_catalogOrderByWithAggregationInput | Prisma.reward_catalogOrderByWithAggregationInput[]
  by: Prisma.Reward_catalogScalarFieldEnum[] | Prisma.Reward_catalogScalarFieldEnum
  having?: Prisma.reward_catalogScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Reward_catalogCountAggregateInputType | true
  _min?: Reward_catalogMinAggregateInputType
  _max?: Reward_catalogMaxAggregateInputType
}

export type Reward_catalogGroupByOutputType = {
  id: string
  key: string
  name: string
  reward_system: string
  description: string
  is_redeemable: boolean
  metadata: runtime.JsonValue
  created_at: Date
  _count: Reward_catalogCountAggregateOutputType | null
  _min: Reward_catalogMinAggregateOutputType | null
  _max: Reward_catalogMaxAggregateOutputType | null
}

export type GetReward_catalogGroupByPayload<T extends reward_catalogGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Reward_catalogGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Reward_catalogGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Reward_catalogGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Reward_catalogGroupByOutputType[P]>
      }
    >
  >



export type reward_catalogWhereInput = {
  AND?: Prisma.reward_catalogWhereInput | Prisma.reward_catalogWhereInput[]
  OR?: Prisma.reward_catalogWhereInput[]
  NOT?: Prisma.reward_catalogWhereInput | Prisma.reward_catalogWhereInput[]
  id?: Prisma.UuidFilter<"reward_catalog"> | string
  key?: Prisma.StringFilter<"reward_catalog"> | string
  name?: Prisma.StringFilter<"reward_catalog"> | string
  reward_system?: Prisma.StringFilter<"reward_catalog"> | string
  description?: Prisma.StringFilter<"reward_catalog"> | string
  is_redeemable?: Prisma.BoolFilter<"reward_catalog"> | boolean
  metadata?: Prisma.JsonFilter<"reward_catalog">
  created_at?: Prisma.DateTimeFilter<"reward_catalog"> | Date | string
  reward_entitlements?: Prisma.Reward_entitlementsListRelationFilter
}

export type reward_catalogOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  name?: Prisma.SortOrder
  reward_system?: Prisma.SortOrder
  description?: Prisma.SortOrder
  is_redeemable?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  reward_entitlements?: Prisma.reward_entitlementsOrderByRelationAggregateInput
}

export type reward_catalogWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  key?: string
  AND?: Prisma.reward_catalogWhereInput | Prisma.reward_catalogWhereInput[]
  OR?: Prisma.reward_catalogWhereInput[]
  NOT?: Prisma.reward_catalogWhereInput | Prisma.reward_catalogWhereInput[]
  name?: Prisma.StringFilter<"reward_catalog"> | string
  reward_system?: Prisma.StringFilter<"reward_catalog"> | string
  description?: Prisma.StringFilter<"reward_catalog"> | string
  is_redeemable?: Prisma.BoolFilter<"reward_catalog"> | boolean
  metadata?: Prisma.JsonFilter<"reward_catalog">
  created_at?: Prisma.DateTimeFilter<"reward_catalog"> | Date | string
  reward_entitlements?: Prisma.Reward_entitlementsListRelationFilter
}, "id" | "key">

export type reward_catalogOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  name?: Prisma.SortOrder
  reward_system?: Prisma.SortOrder
  description?: Prisma.SortOrder
  is_redeemable?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.reward_catalogCountOrderByAggregateInput
  _max?: Prisma.reward_catalogMaxOrderByAggregateInput
  _min?: Prisma.reward_catalogMinOrderByAggregateInput
}

export type reward_catalogScalarWhereWithAggregatesInput = {
  AND?: Prisma.reward_catalogScalarWhereWithAggregatesInput | Prisma.reward_catalogScalarWhereWithAggregatesInput[]
  OR?: Prisma.reward_catalogScalarWhereWithAggregatesInput[]
  NOT?: Prisma.reward_catalogScalarWhereWithAggregatesInput | Prisma.reward_catalogScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"reward_catalog"> | string
  key?: Prisma.StringWithAggregatesFilter<"reward_catalog"> | string
  name?: Prisma.StringWithAggregatesFilter<"reward_catalog"> | string
  reward_system?: Prisma.StringWithAggregatesFilter<"reward_catalog"> | string
  description?: Prisma.StringWithAggregatesFilter<"reward_catalog"> | string
  is_redeemable?: Prisma.BoolWithAggregatesFilter<"reward_catalog"> | boolean
  metadata?: Prisma.JsonWithAggregatesFilter<"reward_catalog">
  created_at?: Prisma.DateTimeWithAggregatesFilter<"reward_catalog"> | Date | string
}

export type reward_catalogCreateInput = {
  id?: string
  key: string
  name: string
  reward_system: string
  description: string
  is_redeemable?: boolean
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  reward_entitlements?: Prisma.reward_entitlementsCreateNestedManyWithoutReward_catalogInput
}

export type reward_catalogUncheckedCreateInput = {
  id?: string
  key: string
  name: string
  reward_system: string
  description: string
  is_redeemable?: boolean
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  reward_entitlements?: Prisma.reward_entitlementsUncheckedCreateNestedManyWithoutReward_catalogInput
}

export type reward_catalogUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  reward_system?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  is_redeemable?: Prisma.BoolFieldUpdateOperationsInput | boolean
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reward_entitlements?: Prisma.reward_entitlementsUpdateManyWithoutReward_catalogNestedInput
}

export type reward_catalogUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  reward_system?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  is_redeemable?: Prisma.BoolFieldUpdateOperationsInput | boolean
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reward_entitlements?: Prisma.reward_entitlementsUncheckedUpdateManyWithoutReward_catalogNestedInput
}

export type reward_catalogCreateManyInput = {
  id?: string
  key: string
  name: string
  reward_system: string
  description: string
  is_redeemable?: boolean
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
}

export type reward_catalogUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  reward_system?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  is_redeemable?: Prisma.BoolFieldUpdateOperationsInput | boolean
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type reward_catalogUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  reward_system?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  is_redeemable?: Prisma.BoolFieldUpdateOperationsInput | boolean
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type reward_catalogCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  name?: Prisma.SortOrder
  reward_system?: Prisma.SortOrder
  description?: Prisma.SortOrder
  is_redeemable?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type reward_catalogMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  name?: Prisma.SortOrder
  reward_system?: Prisma.SortOrder
  description?: Prisma.SortOrder
  is_redeemable?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type reward_catalogMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  name?: Prisma.SortOrder
  reward_system?: Prisma.SortOrder
  description?: Prisma.SortOrder
  is_redeemable?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type Reward_catalogScalarRelationFilter = {
  is?: Prisma.reward_catalogWhereInput
  isNot?: Prisma.reward_catalogWhereInput
}

export type reward_catalogCreateNestedOneWithoutReward_entitlementsInput = {
  create?: Prisma.XOR<Prisma.reward_catalogCreateWithoutReward_entitlementsInput, Prisma.reward_catalogUncheckedCreateWithoutReward_entitlementsInput>
  connectOrCreate?: Prisma.reward_catalogCreateOrConnectWithoutReward_entitlementsInput
  connect?: Prisma.reward_catalogWhereUniqueInput
}

export type reward_catalogUpdateOneRequiredWithoutReward_entitlementsNestedInput = {
  create?: Prisma.XOR<Prisma.reward_catalogCreateWithoutReward_entitlementsInput, Prisma.reward_catalogUncheckedCreateWithoutReward_entitlementsInput>
  connectOrCreate?: Prisma.reward_catalogCreateOrConnectWithoutReward_entitlementsInput
  upsert?: Prisma.reward_catalogUpsertWithoutReward_entitlementsInput
  connect?: Prisma.reward_catalogWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.reward_catalogUpdateToOneWithWhereWithoutReward_entitlementsInput, Prisma.reward_catalogUpdateWithoutReward_entitlementsInput>, Prisma.reward_catalogUncheckedUpdateWithoutReward_entitlementsInput>
}

export type reward_catalogCreateWithoutReward_entitlementsInput = {
  id?: string
  key: string
  name: string
  reward_system: string
  description: string
  is_redeemable?: boolean
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
}

export type reward_catalogUncheckedCreateWithoutReward_entitlementsInput = {
  id?: string
  key: string
  name: string
  reward_system: string
  description: string
  is_redeemable?: boolean
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
}

export type reward_catalogCreateOrConnectWithoutReward_entitlementsInput = {
  where: Prisma.reward_catalogWhereUniqueInput
  create: Prisma.XOR<Prisma.reward_catalogCreateWithoutReward_entitlementsInput, Prisma.reward_catalogUncheckedCreateWithoutReward_entitlementsInput>
}

export type reward_catalogUpsertWithoutReward_entitlementsInput = {
  update: Prisma.XOR<Prisma.reward_catalogUpdateWithoutReward_entitlementsInput, Prisma.reward_catalogUncheckedUpdateWithoutReward_entitlementsInput>
  create: Prisma.XOR<Prisma.reward_catalogCreateWithoutReward_entitlementsInput, Prisma.reward_catalogUncheckedCreateWithoutReward_entitlementsInput>
  where?: Prisma.reward_catalogWhereInput
}

export type reward_catalogUpdateToOneWithWhereWithoutReward_entitlementsInput = {
  where?: Prisma.reward_catalogWhereInput
  data: Prisma.XOR<Prisma.reward_catalogUpdateWithoutReward_entitlementsInput, Prisma.reward_catalogUncheckedUpdateWithoutReward_entitlementsInput>
}

export type reward_catalogUpdateWithoutReward_entitlementsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  reward_system?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  is_redeemable?: Prisma.BoolFieldUpdateOperationsInput | boolean
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type reward_catalogUncheckedUpdateWithoutReward_entitlementsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  reward_system?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  is_redeemable?: Prisma.BoolFieldUpdateOperationsInput | boolean
  metadata?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type Reward_catalogCountOutputType
 */

export type Reward_catalogCountOutputType = {
  reward_entitlements: number
}

export type Reward_catalogCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  reward_entitlements?: boolean | Reward_catalogCountOutputTypeCountReward_entitlementsArgs
}

/**
 * Reward_catalogCountOutputType without action
 */
export type Reward_catalogCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reward_catalogCountOutputType
   */
  select?: Prisma.Reward_catalogCountOutputTypeSelect<ExtArgs> | null
}

/**
 * Reward_catalogCountOutputType without action
 */
export type Reward_catalogCountOutputTypeCountReward_entitlementsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.reward_entitlementsWhereInput
}


export type reward_catalogSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  key?: boolean
  name?: boolean
  reward_system?: boolean
  description?: boolean
  is_redeemable?: boolean
  metadata?: boolean
  created_at?: boolean
  reward_entitlements?: boolean | Prisma.reward_catalog$reward_entitlementsArgs<ExtArgs>
  _count?: boolean | Prisma.Reward_catalogCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["reward_catalog"]>

export type reward_catalogSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  key?: boolean
  name?: boolean
  reward_system?: boolean
  description?: boolean
  is_redeemable?: boolean
  metadata?: boolean
  created_at?: boolean
}, ExtArgs["result"]["reward_catalog"]>

export type reward_catalogSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  key?: boolean
  name?: boolean
  reward_system?: boolean
  description?: boolean
  is_redeemable?: boolean
  metadata?: boolean
  created_at?: boolean
}, ExtArgs["result"]["reward_catalog"]>

export type reward_catalogSelectScalar = {
  id?: boolean
  key?: boolean
  name?: boolean
  reward_system?: boolean
  description?: boolean
  is_redeemable?: boolean
  metadata?: boolean
  created_at?: boolean
}

export type reward_catalogOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "key" | "name" | "reward_system" | "description" | "is_redeemable" | "metadata" | "created_at", ExtArgs["result"]["reward_catalog"]>
export type reward_catalogInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  reward_entitlements?: boolean | Prisma.reward_catalog$reward_entitlementsArgs<ExtArgs>
  _count?: boolean | Prisma.Reward_catalogCountOutputTypeDefaultArgs<ExtArgs>
}
export type reward_catalogIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type reward_catalogIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $reward_catalogPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "reward_catalog"
  objects: {
    reward_entitlements: Prisma.$reward_entitlementsPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    key: string
    name: string
    reward_system: string
    description: string
    is_redeemable: boolean
    metadata: runtime.JsonValue
    created_at: Date
  }, ExtArgs["result"]["reward_catalog"]>
  composites: {}
}

export type reward_catalogGetPayload<S extends boolean | null | undefined | reward_catalogDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$reward_catalogPayload, S>

export type reward_catalogCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<reward_catalogFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Reward_catalogCountAggregateInputType | true
  }

export interface reward_catalogDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['reward_catalog'], meta: { name: 'reward_catalog' } }
  /**
   * Find zero or one Reward_catalog that matches the filter.
   * @param {reward_catalogFindUniqueArgs} args - Arguments to find a Reward_catalog
   * @example
   * // Get one Reward_catalog
   * const reward_catalog = await prisma.reward_catalog.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends reward_catalogFindUniqueArgs>(args: Prisma.SelectSubset<T, reward_catalogFindUniqueArgs<ExtArgs>>): Prisma.Prisma__reward_catalogClient<runtime.Types.Result.GetResult<Prisma.$reward_catalogPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Reward_catalog that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {reward_catalogFindUniqueOrThrowArgs} args - Arguments to find a Reward_catalog
   * @example
   * // Get one Reward_catalog
   * const reward_catalog = await prisma.reward_catalog.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends reward_catalogFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, reward_catalogFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__reward_catalogClient<runtime.Types.Result.GetResult<Prisma.$reward_catalogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Reward_catalog that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {reward_catalogFindFirstArgs} args - Arguments to find a Reward_catalog
   * @example
   * // Get one Reward_catalog
   * const reward_catalog = await prisma.reward_catalog.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends reward_catalogFindFirstArgs>(args?: Prisma.SelectSubset<T, reward_catalogFindFirstArgs<ExtArgs>>): Prisma.Prisma__reward_catalogClient<runtime.Types.Result.GetResult<Prisma.$reward_catalogPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Reward_catalog that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {reward_catalogFindFirstOrThrowArgs} args - Arguments to find a Reward_catalog
   * @example
   * // Get one Reward_catalog
   * const reward_catalog = await prisma.reward_catalog.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends reward_catalogFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, reward_catalogFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__reward_catalogClient<runtime.Types.Result.GetResult<Prisma.$reward_catalogPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Reward_catalogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {reward_catalogFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Reward_catalogs
   * const reward_catalogs = await prisma.reward_catalog.findMany()
   * 
   * // Get first 10 Reward_catalogs
   * const reward_catalogs = await prisma.reward_catalog.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const reward_catalogWithIdOnly = await prisma.reward_catalog.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends reward_catalogFindManyArgs>(args?: Prisma.SelectSubset<T, reward_catalogFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$reward_catalogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Reward_catalog.
   * @param {reward_catalogCreateArgs} args - Arguments to create a Reward_catalog.
   * @example
   * // Create one Reward_catalog
   * const Reward_catalog = await prisma.reward_catalog.create({
   *   data: {
   *     // ... data to create a Reward_catalog
   *   }
   * })
   * 
   */
  create<T extends reward_catalogCreateArgs>(args: Prisma.SelectSubset<T, reward_catalogCreateArgs<ExtArgs>>): Prisma.Prisma__reward_catalogClient<runtime.Types.Result.GetResult<Prisma.$reward_catalogPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Reward_catalogs.
   * @param {reward_catalogCreateManyArgs} args - Arguments to create many Reward_catalogs.
   * @example
   * // Create many Reward_catalogs
   * const reward_catalog = await prisma.reward_catalog.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends reward_catalogCreateManyArgs>(args?: Prisma.SelectSubset<T, reward_catalogCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Reward_catalogs and returns the data saved in the database.
   * @param {reward_catalogCreateManyAndReturnArgs} args - Arguments to create many Reward_catalogs.
   * @example
   * // Create many Reward_catalogs
   * const reward_catalog = await prisma.reward_catalog.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Reward_catalogs and only return the `id`
   * const reward_catalogWithIdOnly = await prisma.reward_catalog.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends reward_catalogCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, reward_catalogCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$reward_catalogPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Reward_catalog.
   * @param {reward_catalogDeleteArgs} args - Arguments to delete one Reward_catalog.
   * @example
   * // Delete one Reward_catalog
   * const Reward_catalog = await prisma.reward_catalog.delete({
   *   where: {
   *     // ... filter to delete one Reward_catalog
   *   }
   * })
   * 
   */
  delete<T extends reward_catalogDeleteArgs>(args: Prisma.SelectSubset<T, reward_catalogDeleteArgs<ExtArgs>>): Prisma.Prisma__reward_catalogClient<runtime.Types.Result.GetResult<Prisma.$reward_catalogPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Reward_catalog.
   * @param {reward_catalogUpdateArgs} args - Arguments to update one Reward_catalog.
   * @example
   * // Update one Reward_catalog
   * const reward_catalog = await prisma.reward_catalog.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends reward_catalogUpdateArgs>(args: Prisma.SelectSubset<T, reward_catalogUpdateArgs<ExtArgs>>): Prisma.Prisma__reward_catalogClient<runtime.Types.Result.GetResult<Prisma.$reward_catalogPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Reward_catalogs.
   * @param {reward_catalogDeleteManyArgs} args - Arguments to filter Reward_catalogs to delete.
   * @example
   * // Delete a few Reward_catalogs
   * const { count } = await prisma.reward_catalog.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends reward_catalogDeleteManyArgs>(args?: Prisma.SelectSubset<T, reward_catalogDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Reward_catalogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {reward_catalogUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Reward_catalogs
   * const reward_catalog = await prisma.reward_catalog.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends reward_catalogUpdateManyArgs>(args: Prisma.SelectSubset<T, reward_catalogUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Reward_catalogs and returns the data updated in the database.
   * @param {reward_catalogUpdateManyAndReturnArgs} args - Arguments to update many Reward_catalogs.
   * @example
   * // Update many Reward_catalogs
   * const reward_catalog = await prisma.reward_catalog.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Reward_catalogs and only return the `id`
   * const reward_catalogWithIdOnly = await prisma.reward_catalog.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends reward_catalogUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, reward_catalogUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$reward_catalogPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Reward_catalog.
   * @param {reward_catalogUpsertArgs} args - Arguments to update or create a Reward_catalog.
   * @example
   * // Update or create a Reward_catalog
   * const reward_catalog = await prisma.reward_catalog.upsert({
   *   create: {
   *     // ... data to create a Reward_catalog
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Reward_catalog we want to update
   *   }
   * })
   */
  upsert<T extends reward_catalogUpsertArgs>(args: Prisma.SelectSubset<T, reward_catalogUpsertArgs<ExtArgs>>): Prisma.Prisma__reward_catalogClient<runtime.Types.Result.GetResult<Prisma.$reward_catalogPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Reward_catalogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {reward_catalogCountArgs} args - Arguments to filter Reward_catalogs to count.
   * @example
   * // Count the number of Reward_catalogs
   * const count = await prisma.reward_catalog.count({
   *   where: {
   *     // ... the filter for the Reward_catalogs we want to count
   *   }
   * })
  **/
  count<T extends reward_catalogCountArgs>(
    args?: Prisma.Subset<T, reward_catalogCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Reward_catalogCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Reward_catalog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Reward_catalogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Reward_catalogAggregateArgs>(args: Prisma.Subset<T, Reward_catalogAggregateArgs>): Prisma.PrismaPromise<GetReward_catalogAggregateType<T>>

  /**
   * Group by Reward_catalog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {reward_catalogGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends reward_catalogGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: reward_catalogGroupByArgs['orderBy'] }
      : { orderBy?: reward_catalogGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, reward_catalogGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetReward_catalogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the reward_catalog model
 */
readonly fields: reward_catalogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for reward_catalog.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__reward_catalogClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  reward_entitlements<T extends Prisma.reward_catalog$reward_entitlementsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.reward_catalog$reward_entitlementsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$reward_entitlementsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the reward_catalog model
 */
export interface reward_catalogFieldRefs {
  readonly id: Prisma.FieldRef<"reward_catalog", 'String'>
  readonly key: Prisma.FieldRef<"reward_catalog", 'String'>
  readonly name: Prisma.FieldRef<"reward_catalog", 'String'>
  readonly reward_system: Prisma.FieldRef<"reward_catalog", 'String'>
  readonly description: Prisma.FieldRef<"reward_catalog", 'String'>
  readonly is_redeemable: Prisma.FieldRef<"reward_catalog", 'Boolean'>
  readonly metadata: Prisma.FieldRef<"reward_catalog", 'Json'>
  readonly created_at: Prisma.FieldRef<"reward_catalog", 'DateTime'>
}
    

// Custom InputTypes
/**
 * reward_catalog findUnique
 */
export type reward_catalogFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_catalog
   */
  select?: Prisma.reward_catalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_catalog
   */
  omit?: Prisma.reward_catalogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_catalogInclude<ExtArgs> | null
  /**
   * Filter, which reward_catalog to fetch.
   */
  where: Prisma.reward_catalogWhereUniqueInput
}

/**
 * reward_catalog findUniqueOrThrow
 */
export type reward_catalogFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_catalog
   */
  select?: Prisma.reward_catalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_catalog
   */
  omit?: Prisma.reward_catalogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_catalogInclude<ExtArgs> | null
  /**
   * Filter, which reward_catalog to fetch.
   */
  where: Prisma.reward_catalogWhereUniqueInput
}

/**
 * reward_catalog findFirst
 */
export type reward_catalogFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_catalog
   */
  select?: Prisma.reward_catalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_catalog
   */
  omit?: Prisma.reward_catalogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_catalogInclude<ExtArgs> | null
  /**
   * Filter, which reward_catalog to fetch.
   */
  where?: Prisma.reward_catalogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of reward_catalogs to fetch.
   */
  orderBy?: Prisma.reward_catalogOrderByWithRelationInput | Prisma.reward_catalogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for reward_catalogs.
   */
  cursor?: Prisma.reward_catalogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` reward_catalogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` reward_catalogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of reward_catalogs.
   */
  distinct?: Prisma.Reward_catalogScalarFieldEnum | Prisma.Reward_catalogScalarFieldEnum[]
}

/**
 * reward_catalog findFirstOrThrow
 */
export type reward_catalogFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_catalog
   */
  select?: Prisma.reward_catalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_catalog
   */
  omit?: Prisma.reward_catalogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_catalogInclude<ExtArgs> | null
  /**
   * Filter, which reward_catalog to fetch.
   */
  where?: Prisma.reward_catalogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of reward_catalogs to fetch.
   */
  orderBy?: Prisma.reward_catalogOrderByWithRelationInput | Prisma.reward_catalogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for reward_catalogs.
   */
  cursor?: Prisma.reward_catalogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` reward_catalogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` reward_catalogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of reward_catalogs.
   */
  distinct?: Prisma.Reward_catalogScalarFieldEnum | Prisma.Reward_catalogScalarFieldEnum[]
}

/**
 * reward_catalog findMany
 */
export type reward_catalogFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_catalog
   */
  select?: Prisma.reward_catalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_catalog
   */
  omit?: Prisma.reward_catalogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_catalogInclude<ExtArgs> | null
  /**
   * Filter, which reward_catalogs to fetch.
   */
  where?: Prisma.reward_catalogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of reward_catalogs to fetch.
   */
  orderBy?: Prisma.reward_catalogOrderByWithRelationInput | Prisma.reward_catalogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing reward_catalogs.
   */
  cursor?: Prisma.reward_catalogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` reward_catalogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` reward_catalogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of reward_catalogs.
   */
  distinct?: Prisma.Reward_catalogScalarFieldEnum | Prisma.Reward_catalogScalarFieldEnum[]
}

/**
 * reward_catalog create
 */
export type reward_catalogCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_catalog
   */
  select?: Prisma.reward_catalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_catalog
   */
  omit?: Prisma.reward_catalogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_catalogInclude<ExtArgs> | null
  /**
   * The data needed to create a reward_catalog.
   */
  data: Prisma.XOR<Prisma.reward_catalogCreateInput, Prisma.reward_catalogUncheckedCreateInput>
}

/**
 * reward_catalog createMany
 */
export type reward_catalogCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many reward_catalogs.
   */
  data: Prisma.reward_catalogCreateManyInput | Prisma.reward_catalogCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * reward_catalog createManyAndReturn
 */
export type reward_catalogCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_catalog
   */
  select?: Prisma.reward_catalogSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the reward_catalog
   */
  omit?: Prisma.reward_catalogOmit<ExtArgs> | null
  /**
   * The data used to create many reward_catalogs.
   */
  data: Prisma.reward_catalogCreateManyInput | Prisma.reward_catalogCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * reward_catalog update
 */
export type reward_catalogUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_catalog
   */
  select?: Prisma.reward_catalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_catalog
   */
  omit?: Prisma.reward_catalogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_catalogInclude<ExtArgs> | null
  /**
   * The data needed to update a reward_catalog.
   */
  data: Prisma.XOR<Prisma.reward_catalogUpdateInput, Prisma.reward_catalogUncheckedUpdateInput>
  /**
   * Choose, which reward_catalog to update.
   */
  where: Prisma.reward_catalogWhereUniqueInput
}

/**
 * reward_catalog updateMany
 */
export type reward_catalogUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update reward_catalogs.
   */
  data: Prisma.XOR<Prisma.reward_catalogUpdateManyMutationInput, Prisma.reward_catalogUncheckedUpdateManyInput>
  /**
   * Filter which reward_catalogs to update
   */
  where?: Prisma.reward_catalogWhereInput
  /**
   * Limit how many reward_catalogs to update.
   */
  limit?: number
}

/**
 * reward_catalog updateManyAndReturn
 */
export type reward_catalogUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_catalog
   */
  select?: Prisma.reward_catalogSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the reward_catalog
   */
  omit?: Prisma.reward_catalogOmit<ExtArgs> | null
  /**
   * The data used to update reward_catalogs.
   */
  data: Prisma.XOR<Prisma.reward_catalogUpdateManyMutationInput, Prisma.reward_catalogUncheckedUpdateManyInput>
  /**
   * Filter which reward_catalogs to update
   */
  where?: Prisma.reward_catalogWhereInput
  /**
   * Limit how many reward_catalogs to update.
   */
  limit?: number
}

/**
 * reward_catalog upsert
 */
export type reward_catalogUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_catalog
   */
  select?: Prisma.reward_catalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_catalog
   */
  omit?: Prisma.reward_catalogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_catalogInclude<ExtArgs> | null
  /**
   * The filter to search for the reward_catalog to update in case it exists.
   */
  where: Prisma.reward_catalogWhereUniqueInput
  /**
   * In case the reward_catalog found by the `where` argument doesn't exist, create a new reward_catalog with this data.
   */
  create: Prisma.XOR<Prisma.reward_catalogCreateInput, Prisma.reward_catalogUncheckedCreateInput>
  /**
   * In case the reward_catalog was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.reward_catalogUpdateInput, Prisma.reward_catalogUncheckedUpdateInput>
}

/**
 * reward_catalog delete
 */
export type reward_catalogDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_catalog
   */
  select?: Prisma.reward_catalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_catalog
   */
  omit?: Prisma.reward_catalogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_catalogInclude<ExtArgs> | null
  /**
   * Filter which reward_catalog to delete.
   */
  where: Prisma.reward_catalogWhereUniqueInput
}

/**
 * reward_catalog deleteMany
 */
export type reward_catalogDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which reward_catalogs to delete
   */
  where?: Prisma.reward_catalogWhereInput
  /**
   * Limit how many reward_catalogs to delete.
   */
  limit?: number
}

/**
 * reward_catalog.reward_entitlements
 */
export type reward_catalog$reward_entitlementsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_entitlements
   */
  select?: Prisma.reward_entitlementsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_entitlements
   */
  omit?: Prisma.reward_entitlementsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_entitlementsInclude<ExtArgs> | null
  where?: Prisma.reward_entitlementsWhereInput
  orderBy?: Prisma.reward_entitlementsOrderByWithRelationInput | Prisma.reward_entitlementsOrderByWithRelationInput[]
  cursor?: Prisma.reward_entitlementsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Reward_entitlementsScalarFieldEnum | Prisma.Reward_entitlementsScalarFieldEnum[]
}

/**
 * reward_catalog without action
 */
export type reward_catalogDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reward_catalog
   */
  select?: Prisma.reward_catalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reward_catalog
   */
  omit?: Prisma.reward_catalogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reward_catalogInclude<ExtArgs> | null
}
