
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `waitlist_rank_history` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model waitlist_rank_history
 * This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info.
 */
export type waitlist_rank_historyModel = runtime.Types.Result.DefaultSelection<Prisma.$waitlist_rank_historyPayload>

export type AggregateWaitlist_rank_history = {
  _count: Waitlist_rank_historyCountAggregateOutputType | null
  _avg: Waitlist_rank_historyAvgAggregateOutputType | null
  _sum: Waitlist_rank_historySumAggregateOutputType | null
  _min: Waitlist_rank_historyMinAggregateOutputType | null
  _max: Waitlist_rank_historyMaxAggregateOutputType | null
}

export type Waitlist_rank_historyAvgAggregateOutputType = {
  rank: number | null
  score: number | null
}

export type Waitlist_rank_historySumAggregateOutputType = {
  rank: number | null
  score: number | null
}

export type Waitlist_rank_historyMinAggregateOutputType = {
  id: string | null
  waitlist_id: string | null
  rank: number | null
  score: number | null
  reason: string | null
  created_at: Date | null
}

export type Waitlist_rank_historyMaxAggregateOutputType = {
  id: string | null
  waitlist_id: string | null
  rank: number | null
  score: number | null
  reason: string | null
  created_at: Date | null
}

export type Waitlist_rank_historyCountAggregateOutputType = {
  id: number
  waitlist_id: number
  rank: number
  score: number
  reason: number
  created_at: number
  _all: number
}


export type Waitlist_rank_historyAvgAggregateInputType = {
  rank?: true
  score?: true
}

export type Waitlist_rank_historySumAggregateInputType = {
  rank?: true
  score?: true
}

export type Waitlist_rank_historyMinAggregateInputType = {
  id?: true
  waitlist_id?: true
  rank?: true
  score?: true
  reason?: true
  created_at?: true
}

export type Waitlist_rank_historyMaxAggregateInputType = {
  id?: true
  waitlist_id?: true
  rank?: true
  score?: true
  reason?: true
  created_at?: true
}

export type Waitlist_rank_historyCountAggregateInputType = {
  id?: true
  waitlist_id?: true
  rank?: true
  score?: true
  reason?: true
  created_at?: true
  _all?: true
}

export type Waitlist_rank_historyAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which waitlist_rank_history to aggregate.
   */
  where?: Prisma.waitlist_rank_historyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of waitlist_rank_histories to fetch.
   */
  orderBy?: Prisma.waitlist_rank_historyOrderByWithRelationInput | Prisma.waitlist_rank_historyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.waitlist_rank_historyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` waitlist_rank_histories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` waitlist_rank_histories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned waitlist_rank_histories
  **/
  _count?: true | Waitlist_rank_historyCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Waitlist_rank_historyAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Waitlist_rank_historySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Waitlist_rank_historyMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Waitlist_rank_historyMaxAggregateInputType
}

export type GetWaitlist_rank_historyAggregateType<T extends Waitlist_rank_historyAggregateArgs> = {
      [P in keyof T & keyof AggregateWaitlist_rank_history]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWaitlist_rank_history[P]>
    : Prisma.GetScalarType<T[P], AggregateWaitlist_rank_history[P]>
}




export type waitlist_rank_historyGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.waitlist_rank_historyWhereInput
  orderBy?: Prisma.waitlist_rank_historyOrderByWithAggregationInput | Prisma.waitlist_rank_historyOrderByWithAggregationInput[]
  by: Prisma.Waitlist_rank_historyScalarFieldEnum[] | Prisma.Waitlist_rank_historyScalarFieldEnum
  having?: Prisma.waitlist_rank_historyScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Waitlist_rank_historyCountAggregateInputType | true
  _avg?: Waitlist_rank_historyAvgAggregateInputType
  _sum?: Waitlist_rank_historySumAggregateInputType
  _min?: Waitlist_rank_historyMinAggregateInputType
  _max?: Waitlist_rank_historyMaxAggregateInputType
}

export type Waitlist_rank_historyGroupByOutputType = {
  id: string
  waitlist_id: string
  rank: number
  score: number
  reason: string
  created_at: Date
  _count: Waitlist_rank_historyCountAggregateOutputType | null
  _avg: Waitlist_rank_historyAvgAggregateOutputType | null
  _sum: Waitlist_rank_historySumAggregateOutputType | null
  _min: Waitlist_rank_historyMinAggregateOutputType | null
  _max: Waitlist_rank_historyMaxAggregateOutputType | null
}

export type GetWaitlist_rank_historyGroupByPayload<T extends waitlist_rank_historyGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Waitlist_rank_historyGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Waitlist_rank_historyGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Waitlist_rank_historyGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Waitlist_rank_historyGroupByOutputType[P]>
      }
    >
  >



export type waitlist_rank_historyWhereInput = {
  AND?: Prisma.waitlist_rank_historyWhereInput | Prisma.waitlist_rank_historyWhereInput[]
  OR?: Prisma.waitlist_rank_historyWhereInput[]
  NOT?: Prisma.waitlist_rank_historyWhereInput | Prisma.waitlist_rank_historyWhereInput[]
  id?: Prisma.UuidFilter<"waitlist_rank_history"> | string
  waitlist_id?: Prisma.UuidFilter<"waitlist_rank_history"> | string
  rank?: Prisma.IntFilter<"waitlist_rank_history"> | number
  score?: Prisma.IntFilter<"waitlist_rank_history"> | number
  reason?: Prisma.StringFilter<"waitlist_rank_history"> | string
  created_at?: Prisma.DateTimeFilter<"waitlist_rank_history"> | Date | string
  waitlist?: Prisma.XOR<Prisma.WaitlistScalarRelationFilter, Prisma.waitlistWhereInput>
}

export type waitlist_rank_historyOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  waitlist_id?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  score?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  waitlist?: Prisma.waitlistOrderByWithRelationInput
}

export type waitlist_rank_historyWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.waitlist_rank_historyWhereInput | Prisma.waitlist_rank_historyWhereInput[]
  OR?: Prisma.waitlist_rank_historyWhereInput[]
  NOT?: Prisma.waitlist_rank_historyWhereInput | Prisma.waitlist_rank_historyWhereInput[]
  waitlist_id?: Prisma.UuidFilter<"waitlist_rank_history"> | string
  rank?: Prisma.IntFilter<"waitlist_rank_history"> | number
  score?: Prisma.IntFilter<"waitlist_rank_history"> | number
  reason?: Prisma.StringFilter<"waitlist_rank_history"> | string
  created_at?: Prisma.DateTimeFilter<"waitlist_rank_history"> | Date | string
  waitlist?: Prisma.XOR<Prisma.WaitlistScalarRelationFilter, Prisma.waitlistWhereInput>
}, "id">

export type waitlist_rank_historyOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  waitlist_id?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  score?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.waitlist_rank_historyCountOrderByAggregateInput
  _avg?: Prisma.waitlist_rank_historyAvgOrderByAggregateInput
  _max?: Prisma.waitlist_rank_historyMaxOrderByAggregateInput
  _min?: Prisma.waitlist_rank_historyMinOrderByAggregateInput
  _sum?: Prisma.waitlist_rank_historySumOrderByAggregateInput
}

export type waitlist_rank_historyScalarWhereWithAggregatesInput = {
  AND?: Prisma.waitlist_rank_historyScalarWhereWithAggregatesInput | Prisma.waitlist_rank_historyScalarWhereWithAggregatesInput[]
  OR?: Prisma.waitlist_rank_historyScalarWhereWithAggregatesInput[]
  NOT?: Prisma.waitlist_rank_historyScalarWhereWithAggregatesInput | Prisma.waitlist_rank_historyScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"waitlist_rank_history"> | string
  waitlist_id?: Prisma.UuidWithAggregatesFilter<"waitlist_rank_history"> | string
  rank?: Prisma.IntWithAggregatesFilter<"waitlist_rank_history"> | number
  score?: Prisma.IntWithAggregatesFilter<"waitlist_rank_history"> | number
  reason?: Prisma.StringWithAggregatesFilter<"waitlist_rank_history"> | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"waitlist_rank_history"> | Date | string
}

export type waitlist_rank_historyCreateInput = {
  id?: string
  rank: number
  score: number
  reason: string
  created_at?: Date | string
  waitlist: Prisma.waitlistCreateNestedOneWithoutWaitlist_rank_historyInput
}

export type waitlist_rank_historyUncheckedCreateInput = {
  id?: string
  waitlist_id: string
  rank: number
  score: number
  reason: string
  created_at?: Date | string
}

export type waitlist_rank_historyUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  score?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  waitlist?: Prisma.waitlistUpdateOneRequiredWithoutWaitlist_rank_historyNestedInput
}

export type waitlist_rank_historyUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  waitlist_id?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  score?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type waitlist_rank_historyCreateManyInput = {
  id?: string
  waitlist_id: string
  rank: number
  score: number
  reason: string
  created_at?: Date | string
}

export type waitlist_rank_historyUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  score?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type waitlist_rank_historyUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  waitlist_id?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  score?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Waitlist_rank_historyListRelationFilter = {
  every?: Prisma.waitlist_rank_historyWhereInput
  some?: Prisma.waitlist_rank_historyWhereInput
  none?: Prisma.waitlist_rank_historyWhereInput
}

export type waitlist_rank_historyOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type waitlist_rank_historyCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  waitlist_id?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  score?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type waitlist_rank_historyAvgOrderByAggregateInput = {
  rank?: Prisma.SortOrder
  score?: Prisma.SortOrder
}

export type waitlist_rank_historyMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  waitlist_id?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  score?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type waitlist_rank_historyMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  waitlist_id?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  score?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type waitlist_rank_historySumOrderByAggregateInput = {
  rank?: Prisma.SortOrder
  score?: Prisma.SortOrder
}

export type waitlist_rank_historyCreateNestedManyWithoutWaitlistInput = {
  create?: Prisma.XOR<Prisma.waitlist_rank_historyCreateWithoutWaitlistInput, Prisma.waitlist_rank_historyUncheckedCreateWithoutWaitlistInput> | Prisma.waitlist_rank_historyCreateWithoutWaitlistInput[] | Prisma.waitlist_rank_historyUncheckedCreateWithoutWaitlistInput[]
  connectOrCreate?: Prisma.waitlist_rank_historyCreateOrConnectWithoutWaitlistInput | Prisma.waitlist_rank_historyCreateOrConnectWithoutWaitlistInput[]
  createMany?: Prisma.waitlist_rank_historyCreateManyWaitlistInputEnvelope
  connect?: Prisma.waitlist_rank_historyWhereUniqueInput | Prisma.waitlist_rank_historyWhereUniqueInput[]
}

export type waitlist_rank_historyUncheckedCreateNestedManyWithoutWaitlistInput = {
  create?: Prisma.XOR<Prisma.waitlist_rank_historyCreateWithoutWaitlistInput, Prisma.waitlist_rank_historyUncheckedCreateWithoutWaitlistInput> | Prisma.waitlist_rank_historyCreateWithoutWaitlistInput[] | Prisma.waitlist_rank_historyUncheckedCreateWithoutWaitlistInput[]
  connectOrCreate?: Prisma.waitlist_rank_historyCreateOrConnectWithoutWaitlistInput | Prisma.waitlist_rank_historyCreateOrConnectWithoutWaitlistInput[]
  createMany?: Prisma.waitlist_rank_historyCreateManyWaitlistInputEnvelope
  connect?: Prisma.waitlist_rank_historyWhereUniqueInput | Prisma.waitlist_rank_historyWhereUniqueInput[]
}

export type waitlist_rank_historyUpdateManyWithoutWaitlistNestedInput = {
  create?: Prisma.XOR<Prisma.waitlist_rank_historyCreateWithoutWaitlistInput, Prisma.waitlist_rank_historyUncheckedCreateWithoutWaitlistInput> | Prisma.waitlist_rank_historyCreateWithoutWaitlistInput[] | Prisma.waitlist_rank_historyUncheckedCreateWithoutWaitlistInput[]
  connectOrCreate?: Prisma.waitlist_rank_historyCreateOrConnectWithoutWaitlistInput | Prisma.waitlist_rank_historyCreateOrConnectWithoutWaitlistInput[]
  upsert?: Prisma.waitlist_rank_historyUpsertWithWhereUniqueWithoutWaitlistInput | Prisma.waitlist_rank_historyUpsertWithWhereUniqueWithoutWaitlistInput[]
  createMany?: Prisma.waitlist_rank_historyCreateManyWaitlistInputEnvelope
  set?: Prisma.waitlist_rank_historyWhereUniqueInput | Prisma.waitlist_rank_historyWhereUniqueInput[]
  disconnect?: Prisma.waitlist_rank_historyWhereUniqueInput | Prisma.waitlist_rank_historyWhereUniqueInput[]
  delete?: Prisma.waitlist_rank_historyWhereUniqueInput | Prisma.waitlist_rank_historyWhereUniqueInput[]
  connect?: Prisma.waitlist_rank_historyWhereUniqueInput | Prisma.waitlist_rank_historyWhereUniqueInput[]
  update?: Prisma.waitlist_rank_historyUpdateWithWhereUniqueWithoutWaitlistInput | Prisma.waitlist_rank_historyUpdateWithWhereUniqueWithoutWaitlistInput[]
  updateMany?: Prisma.waitlist_rank_historyUpdateManyWithWhereWithoutWaitlistInput | Prisma.waitlist_rank_historyUpdateManyWithWhereWithoutWaitlistInput[]
  deleteMany?: Prisma.waitlist_rank_historyScalarWhereInput | Prisma.waitlist_rank_historyScalarWhereInput[]
}

export type waitlist_rank_historyUncheckedUpdateManyWithoutWaitlistNestedInput = {
  create?: Prisma.XOR<Prisma.waitlist_rank_historyCreateWithoutWaitlistInput, Prisma.waitlist_rank_historyUncheckedCreateWithoutWaitlistInput> | Prisma.waitlist_rank_historyCreateWithoutWaitlistInput[] | Prisma.waitlist_rank_historyUncheckedCreateWithoutWaitlistInput[]
  connectOrCreate?: Prisma.waitlist_rank_historyCreateOrConnectWithoutWaitlistInput | Prisma.waitlist_rank_historyCreateOrConnectWithoutWaitlistInput[]
  upsert?: Prisma.waitlist_rank_historyUpsertWithWhereUniqueWithoutWaitlistInput | Prisma.waitlist_rank_historyUpsertWithWhereUniqueWithoutWaitlistInput[]
  createMany?: Prisma.waitlist_rank_historyCreateManyWaitlistInputEnvelope
  set?: Prisma.waitlist_rank_historyWhereUniqueInput | Prisma.waitlist_rank_historyWhereUniqueInput[]
  disconnect?: Prisma.waitlist_rank_historyWhereUniqueInput | Prisma.waitlist_rank_historyWhereUniqueInput[]
  delete?: Prisma.waitlist_rank_historyWhereUniqueInput | Prisma.waitlist_rank_historyWhereUniqueInput[]
  connect?: Prisma.waitlist_rank_historyWhereUniqueInput | Prisma.waitlist_rank_historyWhereUniqueInput[]
  update?: Prisma.waitlist_rank_historyUpdateWithWhereUniqueWithoutWaitlistInput | Prisma.waitlist_rank_historyUpdateWithWhereUniqueWithoutWaitlistInput[]
  updateMany?: Prisma.waitlist_rank_historyUpdateManyWithWhereWithoutWaitlistInput | Prisma.waitlist_rank_historyUpdateManyWithWhereWithoutWaitlistInput[]
  deleteMany?: Prisma.waitlist_rank_historyScalarWhereInput | Prisma.waitlist_rank_historyScalarWhereInput[]
}

export type waitlist_rank_historyCreateWithoutWaitlistInput = {
  id?: string
  rank: number
  score: number
  reason: string
  created_at?: Date | string
}

export type waitlist_rank_historyUncheckedCreateWithoutWaitlistInput = {
  id?: string
  rank: number
  score: number
  reason: string
  created_at?: Date | string
}

export type waitlist_rank_historyCreateOrConnectWithoutWaitlistInput = {
  where: Prisma.waitlist_rank_historyWhereUniqueInput
  create: Prisma.XOR<Prisma.waitlist_rank_historyCreateWithoutWaitlistInput, Prisma.waitlist_rank_historyUncheckedCreateWithoutWaitlistInput>
}

export type waitlist_rank_historyCreateManyWaitlistInputEnvelope = {
  data: Prisma.waitlist_rank_historyCreateManyWaitlistInput | Prisma.waitlist_rank_historyCreateManyWaitlistInput[]
  skipDuplicates?: boolean
}

export type waitlist_rank_historyUpsertWithWhereUniqueWithoutWaitlistInput = {
  where: Prisma.waitlist_rank_historyWhereUniqueInput
  update: Prisma.XOR<Prisma.waitlist_rank_historyUpdateWithoutWaitlistInput, Prisma.waitlist_rank_historyUncheckedUpdateWithoutWaitlistInput>
  create: Prisma.XOR<Prisma.waitlist_rank_historyCreateWithoutWaitlistInput, Prisma.waitlist_rank_historyUncheckedCreateWithoutWaitlistInput>
}

export type waitlist_rank_historyUpdateWithWhereUniqueWithoutWaitlistInput = {
  where: Prisma.waitlist_rank_historyWhereUniqueInput
  data: Prisma.XOR<Prisma.waitlist_rank_historyUpdateWithoutWaitlistInput, Prisma.waitlist_rank_historyUncheckedUpdateWithoutWaitlistInput>
}

export type waitlist_rank_historyUpdateManyWithWhereWithoutWaitlistInput = {
  where: Prisma.waitlist_rank_historyScalarWhereInput
  data: Prisma.XOR<Prisma.waitlist_rank_historyUpdateManyMutationInput, Prisma.waitlist_rank_historyUncheckedUpdateManyWithoutWaitlistInput>
}

export type waitlist_rank_historyScalarWhereInput = {
  AND?: Prisma.waitlist_rank_historyScalarWhereInput | Prisma.waitlist_rank_historyScalarWhereInput[]
  OR?: Prisma.waitlist_rank_historyScalarWhereInput[]
  NOT?: Prisma.waitlist_rank_historyScalarWhereInput | Prisma.waitlist_rank_historyScalarWhereInput[]
  id?: Prisma.UuidFilter<"waitlist_rank_history"> | string
  waitlist_id?: Prisma.UuidFilter<"waitlist_rank_history"> | string
  rank?: Prisma.IntFilter<"waitlist_rank_history"> | number
  score?: Prisma.IntFilter<"waitlist_rank_history"> | number
  reason?: Prisma.StringFilter<"waitlist_rank_history"> | string
  created_at?: Prisma.DateTimeFilter<"waitlist_rank_history"> | Date | string
}

export type waitlist_rank_historyCreateManyWaitlistInput = {
  id?: string
  rank: number
  score: number
  reason: string
  created_at?: Date | string
}

export type waitlist_rank_historyUpdateWithoutWaitlistInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  score?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type waitlist_rank_historyUncheckedUpdateWithoutWaitlistInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  score?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type waitlist_rank_historyUncheckedUpdateManyWithoutWaitlistInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  score?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type waitlist_rank_historySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  waitlist_id?: boolean
  rank?: boolean
  score?: boolean
  reason?: boolean
  created_at?: boolean
  waitlist?: boolean | Prisma.waitlistDefaultArgs<ExtArgs>
}, ExtArgs["result"]["waitlist_rank_history"]>

export type waitlist_rank_historySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  waitlist_id?: boolean
  rank?: boolean
  score?: boolean
  reason?: boolean
  created_at?: boolean
  waitlist?: boolean | Prisma.waitlistDefaultArgs<ExtArgs>
}, ExtArgs["result"]["waitlist_rank_history"]>

export type waitlist_rank_historySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  waitlist_id?: boolean
  rank?: boolean
  score?: boolean
  reason?: boolean
  created_at?: boolean
  waitlist?: boolean | Prisma.waitlistDefaultArgs<ExtArgs>
}, ExtArgs["result"]["waitlist_rank_history"]>

export type waitlist_rank_historySelectScalar = {
  id?: boolean
  waitlist_id?: boolean
  rank?: boolean
  score?: boolean
  reason?: boolean
  created_at?: boolean
}

export type waitlist_rank_historyOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "waitlist_id" | "rank" | "score" | "reason" | "created_at", ExtArgs["result"]["waitlist_rank_history"]>
export type waitlist_rank_historyInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  waitlist?: boolean | Prisma.waitlistDefaultArgs<ExtArgs>
}
export type waitlist_rank_historyIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  waitlist?: boolean | Prisma.waitlistDefaultArgs<ExtArgs>
}
export type waitlist_rank_historyIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  waitlist?: boolean | Prisma.waitlistDefaultArgs<ExtArgs>
}

export type $waitlist_rank_historyPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "waitlist_rank_history"
  objects: {
    waitlist: Prisma.$waitlistPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    waitlist_id: string
    rank: number
    score: number
    reason: string
    created_at: Date
  }, ExtArgs["result"]["waitlist_rank_history"]>
  composites: {}
}

export type waitlist_rank_historyGetPayload<S extends boolean | null | undefined | waitlist_rank_historyDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$waitlist_rank_historyPayload, S>

export type waitlist_rank_historyCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<waitlist_rank_historyFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Waitlist_rank_historyCountAggregateInputType | true
  }

export interface waitlist_rank_historyDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['waitlist_rank_history'], meta: { name: 'waitlist_rank_history' } }
  /**
   * Find zero or one Waitlist_rank_history that matches the filter.
   * @param {waitlist_rank_historyFindUniqueArgs} args - Arguments to find a Waitlist_rank_history
   * @example
   * // Get one Waitlist_rank_history
   * const waitlist_rank_history = await prisma.waitlist_rank_history.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends waitlist_rank_historyFindUniqueArgs>(args: Prisma.SelectSubset<T, waitlist_rank_historyFindUniqueArgs<ExtArgs>>): Prisma.Prisma__waitlist_rank_historyClient<runtime.Types.Result.GetResult<Prisma.$waitlist_rank_historyPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Waitlist_rank_history that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {waitlist_rank_historyFindUniqueOrThrowArgs} args - Arguments to find a Waitlist_rank_history
   * @example
   * // Get one Waitlist_rank_history
   * const waitlist_rank_history = await prisma.waitlist_rank_history.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends waitlist_rank_historyFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, waitlist_rank_historyFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__waitlist_rank_historyClient<runtime.Types.Result.GetResult<Prisma.$waitlist_rank_historyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Waitlist_rank_history that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {waitlist_rank_historyFindFirstArgs} args - Arguments to find a Waitlist_rank_history
   * @example
   * // Get one Waitlist_rank_history
   * const waitlist_rank_history = await prisma.waitlist_rank_history.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends waitlist_rank_historyFindFirstArgs>(args?: Prisma.SelectSubset<T, waitlist_rank_historyFindFirstArgs<ExtArgs>>): Prisma.Prisma__waitlist_rank_historyClient<runtime.Types.Result.GetResult<Prisma.$waitlist_rank_historyPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Waitlist_rank_history that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {waitlist_rank_historyFindFirstOrThrowArgs} args - Arguments to find a Waitlist_rank_history
   * @example
   * // Get one Waitlist_rank_history
   * const waitlist_rank_history = await prisma.waitlist_rank_history.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends waitlist_rank_historyFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, waitlist_rank_historyFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__waitlist_rank_historyClient<runtime.Types.Result.GetResult<Prisma.$waitlist_rank_historyPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Waitlist_rank_histories that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {waitlist_rank_historyFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Waitlist_rank_histories
   * const waitlist_rank_histories = await prisma.waitlist_rank_history.findMany()
   * 
   * // Get first 10 Waitlist_rank_histories
   * const waitlist_rank_histories = await prisma.waitlist_rank_history.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const waitlist_rank_historyWithIdOnly = await prisma.waitlist_rank_history.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends waitlist_rank_historyFindManyArgs>(args?: Prisma.SelectSubset<T, waitlist_rank_historyFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$waitlist_rank_historyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Waitlist_rank_history.
   * @param {waitlist_rank_historyCreateArgs} args - Arguments to create a Waitlist_rank_history.
   * @example
   * // Create one Waitlist_rank_history
   * const Waitlist_rank_history = await prisma.waitlist_rank_history.create({
   *   data: {
   *     // ... data to create a Waitlist_rank_history
   *   }
   * })
   * 
   */
  create<T extends waitlist_rank_historyCreateArgs>(args: Prisma.SelectSubset<T, waitlist_rank_historyCreateArgs<ExtArgs>>): Prisma.Prisma__waitlist_rank_historyClient<runtime.Types.Result.GetResult<Prisma.$waitlist_rank_historyPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Waitlist_rank_histories.
   * @param {waitlist_rank_historyCreateManyArgs} args - Arguments to create many Waitlist_rank_histories.
   * @example
   * // Create many Waitlist_rank_histories
   * const waitlist_rank_history = await prisma.waitlist_rank_history.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends waitlist_rank_historyCreateManyArgs>(args?: Prisma.SelectSubset<T, waitlist_rank_historyCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Waitlist_rank_histories and returns the data saved in the database.
   * @param {waitlist_rank_historyCreateManyAndReturnArgs} args - Arguments to create many Waitlist_rank_histories.
   * @example
   * // Create many Waitlist_rank_histories
   * const waitlist_rank_history = await prisma.waitlist_rank_history.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Waitlist_rank_histories and only return the `id`
   * const waitlist_rank_historyWithIdOnly = await prisma.waitlist_rank_history.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends waitlist_rank_historyCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, waitlist_rank_historyCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$waitlist_rank_historyPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Waitlist_rank_history.
   * @param {waitlist_rank_historyDeleteArgs} args - Arguments to delete one Waitlist_rank_history.
   * @example
   * // Delete one Waitlist_rank_history
   * const Waitlist_rank_history = await prisma.waitlist_rank_history.delete({
   *   where: {
   *     // ... filter to delete one Waitlist_rank_history
   *   }
   * })
   * 
   */
  delete<T extends waitlist_rank_historyDeleteArgs>(args: Prisma.SelectSubset<T, waitlist_rank_historyDeleteArgs<ExtArgs>>): Prisma.Prisma__waitlist_rank_historyClient<runtime.Types.Result.GetResult<Prisma.$waitlist_rank_historyPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Waitlist_rank_history.
   * @param {waitlist_rank_historyUpdateArgs} args - Arguments to update one Waitlist_rank_history.
   * @example
   * // Update one Waitlist_rank_history
   * const waitlist_rank_history = await prisma.waitlist_rank_history.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends waitlist_rank_historyUpdateArgs>(args: Prisma.SelectSubset<T, waitlist_rank_historyUpdateArgs<ExtArgs>>): Prisma.Prisma__waitlist_rank_historyClient<runtime.Types.Result.GetResult<Prisma.$waitlist_rank_historyPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Waitlist_rank_histories.
   * @param {waitlist_rank_historyDeleteManyArgs} args - Arguments to filter Waitlist_rank_histories to delete.
   * @example
   * // Delete a few Waitlist_rank_histories
   * const { count } = await prisma.waitlist_rank_history.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends waitlist_rank_historyDeleteManyArgs>(args?: Prisma.SelectSubset<T, waitlist_rank_historyDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Waitlist_rank_histories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {waitlist_rank_historyUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Waitlist_rank_histories
   * const waitlist_rank_history = await prisma.waitlist_rank_history.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends waitlist_rank_historyUpdateManyArgs>(args: Prisma.SelectSubset<T, waitlist_rank_historyUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Waitlist_rank_histories and returns the data updated in the database.
   * @param {waitlist_rank_historyUpdateManyAndReturnArgs} args - Arguments to update many Waitlist_rank_histories.
   * @example
   * // Update many Waitlist_rank_histories
   * const waitlist_rank_history = await prisma.waitlist_rank_history.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Waitlist_rank_histories and only return the `id`
   * const waitlist_rank_historyWithIdOnly = await prisma.waitlist_rank_history.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends waitlist_rank_historyUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, waitlist_rank_historyUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$waitlist_rank_historyPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Waitlist_rank_history.
   * @param {waitlist_rank_historyUpsertArgs} args - Arguments to update or create a Waitlist_rank_history.
   * @example
   * // Update or create a Waitlist_rank_history
   * const waitlist_rank_history = await prisma.waitlist_rank_history.upsert({
   *   create: {
   *     // ... data to create a Waitlist_rank_history
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Waitlist_rank_history we want to update
   *   }
   * })
   */
  upsert<T extends waitlist_rank_historyUpsertArgs>(args: Prisma.SelectSubset<T, waitlist_rank_historyUpsertArgs<ExtArgs>>): Prisma.Prisma__waitlist_rank_historyClient<runtime.Types.Result.GetResult<Prisma.$waitlist_rank_historyPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Waitlist_rank_histories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {waitlist_rank_historyCountArgs} args - Arguments to filter Waitlist_rank_histories to count.
   * @example
   * // Count the number of Waitlist_rank_histories
   * const count = await prisma.waitlist_rank_history.count({
   *   where: {
   *     // ... the filter for the Waitlist_rank_histories we want to count
   *   }
   * })
  **/
  count<T extends waitlist_rank_historyCountArgs>(
    args?: Prisma.Subset<T, waitlist_rank_historyCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Waitlist_rank_historyCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Waitlist_rank_history.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Waitlist_rank_historyAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Waitlist_rank_historyAggregateArgs>(args: Prisma.Subset<T, Waitlist_rank_historyAggregateArgs>): Prisma.PrismaPromise<GetWaitlist_rank_historyAggregateType<T>>

  /**
   * Group by Waitlist_rank_history.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {waitlist_rank_historyGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends waitlist_rank_historyGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: waitlist_rank_historyGroupByArgs['orderBy'] }
      : { orderBy?: waitlist_rank_historyGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, waitlist_rank_historyGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWaitlist_rank_historyGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the waitlist_rank_history model
 */
readonly fields: waitlist_rank_historyFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for waitlist_rank_history.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__waitlist_rank_historyClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  waitlist<T extends Prisma.waitlistDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.waitlistDefaultArgs<ExtArgs>>): Prisma.Prisma__waitlistClient<runtime.Types.Result.GetResult<Prisma.$waitlistPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the waitlist_rank_history model
 */
export interface waitlist_rank_historyFieldRefs {
  readonly id: Prisma.FieldRef<"waitlist_rank_history", 'String'>
  readonly waitlist_id: Prisma.FieldRef<"waitlist_rank_history", 'String'>
  readonly rank: Prisma.FieldRef<"waitlist_rank_history", 'Int'>
  readonly score: Prisma.FieldRef<"waitlist_rank_history", 'Int'>
  readonly reason: Prisma.FieldRef<"waitlist_rank_history", 'String'>
  readonly created_at: Prisma.FieldRef<"waitlist_rank_history", 'DateTime'>
}
    

// Custom InputTypes
/**
 * waitlist_rank_history findUnique
 */
export type waitlist_rank_historyFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the waitlist_rank_history
   */
  select?: Prisma.waitlist_rank_historySelect<ExtArgs> | null
  /**
   * Omit specific fields from the waitlist_rank_history
   */
  omit?: Prisma.waitlist_rank_historyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.waitlist_rank_historyInclude<ExtArgs> | null
  /**
   * Filter, which waitlist_rank_history to fetch.
   */
  where: Prisma.waitlist_rank_historyWhereUniqueInput
}

/**
 * waitlist_rank_history findUniqueOrThrow
 */
export type waitlist_rank_historyFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the waitlist_rank_history
   */
  select?: Prisma.waitlist_rank_historySelect<ExtArgs> | null
  /**
   * Omit specific fields from the waitlist_rank_history
   */
  omit?: Prisma.waitlist_rank_historyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.waitlist_rank_historyInclude<ExtArgs> | null
  /**
   * Filter, which waitlist_rank_history to fetch.
   */
  where: Prisma.waitlist_rank_historyWhereUniqueInput
}

/**
 * waitlist_rank_history findFirst
 */
export type waitlist_rank_historyFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the waitlist_rank_history
   */
  select?: Prisma.waitlist_rank_historySelect<ExtArgs> | null
  /**
   * Omit specific fields from the waitlist_rank_history
   */
  omit?: Prisma.waitlist_rank_historyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.waitlist_rank_historyInclude<ExtArgs> | null
  /**
   * Filter, which waitlist_rank_history to fetch.
   */
  where?: Prisma.waitlist_rank_historyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of waitlist_rank_histories to fetch.
   */
  orderBy?: Prisma.waitlist_rank_historyOrderByWithRelationInput | Prisma.waitlist_rank_historyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for waitlist_rank_histories.
   */
  cursor?: Prisma.waitlist_rank_historyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` waitlist_rank_histories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` waitlist_rank_histories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of waitlist_rank_histories.
   */
  distinct?: Prisma.Waitlist_rank_historyScalarFieldEnum | Prisma.Waitlist_rank_historyScalarFieldEnum[]
}

/**
 * waitlist_rank_history findFirstOrThrow
 */
export type waitlist_rank_historyFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the waitlist_rank_history
   */
  select?: Prisma.waitlist_rank_historySelect<ExtArgs> | null
  /**
   * Omit specific fields from the waitlist_rank_history
   */
  omit?: Prisma.waitlist_rank_historyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.waitlist_rank_historyInclude<ExtArgs> | null
  /**
   * Filter, which waitlist_rank_history to fetch.
   */
  where?: Prisma.waitlist_rank_historyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of waitlist_rank_histories to fetch.
   */
  orderBy?: Prisma.waitlist_rank_historyOrderByWithRelationInput | Prisma.waitlist_rank_historyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for waitlist_rank_histories.
   */
  cursor?: Prisma.waitlist_rank_historyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` waitlist_rank_histories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` waitlist_rank_histories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of waitlist_rank_histories.
   */
  distinct?: Prisma.Waitlist_rank_historyScalarFieldEnum | Prisma.Waitlist_rank_historyScalarFieldEnum[]
}

/**
 * waitlist_rank_history findMany
 */
export type waitlist_rank_historyFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the waitlist_rank_history
   */
  select?: Prisma.waitlist_rank_historySelect<ExtArgs> | null
  /**
   * Omit specific fields from the waitlist_rank_history
   */
  omit?: Prisma.waitlist_rank_historyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.waitlist_rank_historyInclude<ExtArgs> | null
  /**
   * Filter, which waitlist_rank_histories to fetch.
   */
  where?: Prisma.waitlist_rank_historyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of waitlist_rank_histories to fetch.
   */
  orderBy?: Prisma.waitlist_rank_historyOrderByWithRelationInput | Prisma.waitlist_rank_historyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing waitlist_rank_histories.
   */
  cursor?: Prisma.waitlist_rank_historyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` waitlist_rank_histories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` waitlist_rank_histories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of waitlist_rank_histories.
   */
  distinct?: Prisma.Waitlist_rank_historyScalarFieldEnum | Prisma.Waitlist_rank_historyScalarFieldEnum[]
}

/**
 * waitlist_rank_history create
 */
export type waitlist_rank_historyCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the waitlist_rank_history
   */
  select?: Prisma.waitlist_rank_historySelect<ExtArgs> | null
  /**
   * Omit specific fields from the waitlist_rank_history
   */
  omit?: Prisma.waitlist_rank_historyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.waitlist_rank_historyInclude<ExtArgs> | null
  /**
   * The data needed to create a waitlist_rank_history.
   */
  data: Prisma.XOR<Prisma.waitlist_rank_historyCreateInput, Prisma.waitlist_rank_historyUncheckedCreateInput>
}

/**
 * waitlist_rank_history createMany
 */
export type waitlist_rank_historyCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many waitlist_rank_histories.
   */
  data: Prisma.waitlist_rank_historyCreateManyInput | Prisma.waitlist_rank_historyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * waitlist_rank_history createManyAndReturn
 */
export type waitlist_rank_historyCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the waitlist_rank_history
   */
  select?: Prisma.waitlist_rank_historySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the waitlist_rank_history
   */
  omit?: Prisma.waitlist_rank_historyOmit<ExtArgs> | null
  /**
   * The data used to create many waitlist_rank_histories.
   */
  data: Prisma.waitlist_rank_historyCreateManyInput | Prisma.waitlist_rank_historyCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.waitlist_rank_historyIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * waitlist_rank_history update
 */
export type waitlist_rank_historyUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the waitlist_rank_history
   */
  select?: Prisma.waitlist_rank_historySelect<ExtArgs> | null
  /**
   * Omit specific fields from the waitlist_rank_history
   */
  omit?: Prisma.waitlist_rank_historyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.waitlist_rank_historyInclude<ExtArgs> | null
  /**
   * The data needed to update a waitlist_rank_history.
   */
  data: Prisma.XOR<Prisma.waitlist_rank_historyUpdateInput, Prisma.waitlist_rank_historyUncheckedUpdateInput>
  /**
   * Choose, which waitlist_rank_history to update.
   */
  where: Prisma.waitlist_rank_historyWhereUniqueInput
}

/**
 * waitlist_rank_history updateMany
 */
export type waitlist_rank_historyUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update waitlist_rank_histories.
   */
  data: Prisma.XOR<Prisma.waitlist_rank_historyUpdateManyMutationInput, Prisma.waitlist_rank_historyUncheckedUpdateManyInput>
  /**
   * Filter which waitlist_rank_histories to update
   */
  where?: Prisma.waitlist_rank_historyWhereInput
  /**
   * Limit how many waitlist_rank_histories to update.
   */
  limit?: number
}

/**
 * waitlist_rank_history updateManyAndReturn
 */
export type waitlist_rank_historyUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the waitlist_rank_history
   */
  select?: Prisma.waitlist_rank_historySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the waitlist_rank_history
   */
  omit?: Prisma.waitlist_rank_historyOmit<ExtArgs> | null
  /**
   * The data used to update waitlist_rank_histories.
   */
  data: Prisma.XOR<Prisma.waitlist_rank_historyUpdateManyMutationInput, Prisma.waitlist_rank_historyUncheckedUpdateManyInput>
  /**
   * Filter which waitlist_rank_histories to update
   */
  where?: Prisma.waitlist_rank_historyWhereInput
  /**
   * Limit how many waitlist_rank_histories to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.waitlist_rank_historyIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * waitlist_rank_history upsert
 */
export type waitlist_rank_historyUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the waitlist_rank_history
   */
  select?: Prisma.waitlist_rank_historySelect<ExtArgs> | null
  /**
   * Omit specific fields from the waitlist_rank_history
   */
  omit?: Prisma.waitlist_rank_historyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.waitlist_rank_historyInclude<ExtArgs> | null
  /**
   * The filter to search for the waitlist_rank_history to update in case it exists.
   */
  where: Prisma.waitlist_rank_historyWhereUniqueInput
  /**
   * In case the waitlist_rank_history found by the `where` argument doesn't exist, create a new waitlist_rank_history with this data.
   */
  create: Prisma.XOR<Prisma.waitlist_rank_historyCreateInput, Prisma.waitlist_rank_historyUncheckedCreateInput>
  /**
   * In case the waitlist_rank_history was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.waitlist_rank_historyUpdateInput, Prisma.waitlist_rank_historyUncheckedUpdateInput>
}

/**
 * waitlist_rank_history delete
 */
export type waitlist_rank_historyDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the waitlist_rank_history
   */
  select?: Prisma.waitlist_rank_historySelect<ExtArgs> | null
  /**
   * Omit specific fields from the waitlist_rank_history
   */
  omit?: Prisma.waitlist_rank_historyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.waitlist_rank_historyInclude<ExtArgs> | null
  /**
   * Filter which waitlist_rank_history to delete.
   */
  where: Prisma.waitlist_rank_historyWhereUniqueInput
}

/**
 * waitlist_rank_history deleteMany
 */
export type waitlist_rank_historyDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which waitlist_rank_histories to delete
   */
  where?: Prisma.waitlist_rank_historyWhereInput
  /**
   * Limit how many waitlist_rank_histories to delete.
   */
  limit?: number
}

/**
 * waitlist_rank_history without action
 */
export type waitlist_rank_historyDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the waitlist_rank_history
   */
  select?: Prisma.waitlist_rank_historySelect<ExtArgs> | null
  /**
   * Omit specific fields from the waitlist_rank_history
   */
  omit?: Prisma.waitlist_rank_historyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.waitlist_rank_historyInclude<ExtArgs> | null
}
