#!/usr/bin/env node
/**
 * Clone-and-run entry for RealEST.
 *
 *   ./start.sh
 *   node scripts/start-app.mjs --check
 *   node scripts/start-app.mjs --local-supabase
 */

import { spawn, spawnSync } from "node:child_process";
import { existsSync, readFileSync, realpathSync, writeFileSync } from "node:fs";
import { createServer } from "node:net";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  collectEnvIssues,
  decidePortAction,
  LOCAL_DEV_DEFAULTS,
  looksLikeRealestHtml,
  mapSupabaseStatusEnv,
  meetsNodeRequirement,
  mergeEnvSources,
  MIN_NODE_MAJOR,
  missingKeysMessage,
  parseEnvFile,
  parseListenerPid,
  serializeEnvFile,
  startAppReadyLine,
  waitForHttp,
} from "./lib/start-app-core.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = process.env.START_APP_ROOT
  ? join(process.env.START_APP_ROOT)
  : join(__dirname, "..");
const ENV_LOCAL_PATH = join(ROOT, ".env.local");
const ENV_EXAMPLE_PATH = join(ROOT, ".env.example");

function parseArgs(argv) {
  const args = {
    check: false,
    install: true,
    localSupabase: false,
    noLocalSupabase: false,
    verify: true,
    port: Number(process.env.PORT) || 3000,
    timeoutMs: 180_000,
  };

  for (let i = 0; i < argv.length; i += 1) {
    const token = argv[i];
    if (token === "--check") args.check = true;
    else if (token === "--no-install") args.install = false;
    else if (token === "--local-supabase") args.localSupabase = true;
    else if (token === "--no-local-supabase") args.noLocalSupabase = true;
    else if (token === "--no-verify") args.verify = false;
    else if (token === "--port") args.port = Number(argv[++i]);
    else if (token === "--timeout-ms") args.timeoutMs = Number(argv[++i]);
    else if (token === "--help" || token === "-h") args.help = true;
    else throw new Error(`Unknown argument: ${token}`);
  }

  return args;
}

function log(message) {
  process.stdout.write(`${message}\n`);
}

function loadEnvFile(path) {
  if (!existsSync(path)) return {};
  return parseEnvFile(readFileSync(path, "utf8"));
}

function currentEnv() {
  return mergeEnvSources(loadEnvFile(ENV_LOCAL_PATH), process.env);
}

function ensureEnvExample() {
  if (existsSync(ENV_EXAMPLE_PATH)) return;
  throw new Error(
    `.env.example is missing. Restore it from git before starting the app.`,
  );
}

function writeEnvLocal(env) {
  const body = serializeEnvFile(env, [
    "# Generated by scripts/start-app.mjs for local development.",
    "# Do not commit this file.",
  ]);
  writeFileSync(ENV_LOCAL_PATH, body, { encoding: "utf8" });
}

function commandExists(command) {
  const result = spawnSync("sh", ["-c", `command -v ${command}`], {
    encoding: "utf8",
  });
  return result.status === 0;
}

function run(command, args, options = {}) {
  log(`$ ${command} ${args.join(" ")}`);
  const stdio = options.capture
    ? ["pipe", "pipe", "pipe"]
    : options.input
      ? ["pipe", "inherit", "inherit"]
      : "inherit";
  const result = spawnSync(command, args, {
    cwd: ROOT,
    stdio,
    encoding: "utf8",
    input: options.input,
    env: options.env ?? process.env,
  });
  if (result.status !== 0) {
    const detail = options.capture
      ? `${result.stdout ?? ""}\n${result.stderr ?? ""}`
      : "";
    throw new Error(
      `${command} ${args.join(" ")} failed with exit ${result.status}${detail ? `\n${detail}` : ""}`,
    );
  }
  return result;
}

async function portIsFree(port) {
  return new Promise((resolve) => {
    const server = createServer();
    server.once("error", () => resolve(false));
    server.once("listening", () => {
      server.close(() => resolve(true));
    });
    server.listen(port, "127.0.0.1");
  });
}

function readListenerPid(port) {
  const ss = spawnSync("ss", ["-H", "-tlnp", `sport = :${port}`], {
    encoding: "utf8",
  });
  if (ss.status === 0) {
    const pid = parseListenerPid(`${ss.stdout ?? ""}\n${ss.stderr ?? ""}`, port);
    if (pid) return pid;
  }

  const lsof = spawnSync(
    "lsof",
    ["-iTCP:" + port, "-sTCP:LISTEN", "-n", "-P", "-t"],
    { encoding: "utf8" },
  );
  if (lsof.status === 0) {
    const pid = parseListenerPid(lsof.stdout ?? "", port);
    if (pid) return pid;
  }
  return null;
}

function readProcessCwd(pid) {
  try {
    return realpathSync(`/proc/${pid}/cwd`);
  } catch {
    return null;
  }
}

async function collectUsedPorts(startPort) {
  const used = [];
  for (let port = startPort; port < startPort + 20; port += 1) {
    if (!(await portIsFree(port))) used.push(port);
  }
  return used;
}

async function resolveListenPort(preferredPort, repoRoot) {
  const usedPorts = await collectUsedPorts(preferredPort);
  const pid = usedPorts.includes(preferredPort)
    ? readListenerPid(preferredPort)
    : null;
  const occupantCwd = pid ? readProcessCwd(pid) : null;
  const decision = decidePortAction({
    preferredPort,
    repoRoot,
    occupantCwd,
    usedPorts,
  });

  if (decision.action === "reuse") {
    const url = `http://127.0.0.1:${decision.port}`;
    try {
      const response = await fetch(url, { redirect: "manual", cache: "no-store" });
      const html = await response.text();
      if (looksLikeRealestHtml(html)) {
        return { ...decision, pid, occupantCwd };
      }
    } catch {
      // Fall through and bind the next port.
    }
    return {
      action: "listen",
      port: decidePortAction({
        preferredPort,
        repoRoot,
        occupantCwd: null,
        usedPorts,
      }).port,
      reason: "same-repo-not-reusable",
      pid,
      occupantCwd,
    };
  }

  return { ...decision, pid, occupantCwd };
}

function maybeStartLocalSupabase() {
  const configPath = join(ROOT, "supabase", "config.toml");
  if (!existsSync(configPath)) {
    run("npx", ["--yes", "supabase", "init"], { input: "n\nn\n" });
  }

  log("Starting local Supabase via Docker. First run may download images.");
  run("npx", ["--yes", "supabase", "start"]);
  const status = run("npx", ["--yes", "supabase", "status", "-o", "env"], {
    capture: true,
  });
  const mapped = mapSupabaseStatusEnv(parseEnvFile(status.stdout ?? ""));
  const issues = collectEnvIssues(mapped);
  if (issues.missingRequired.length > 0) {
    throw new Error(
      `Local Supabase started but did not provide: ${issues.missingRequired.join(", ")}`,
    );
  }

  const existing = loadEnvFile(ENV_LOCAL_PATH);
  const nextEnv = mergeEnvSources(LOCAL_DEV_DEFAULTS, existing, mapped);
  writeEnvLocal(nextEnv);
  log(`Wrote ${ENV_LOCAL_PATH} from local Supabase.`);
  return nextEnv;
}

function installDependencies() {
  if (!existsSync(join(ROOT, "package.json"))) {
    throw new Error("package.json not found. Run this from the repo root.");
  }

  const lockfile = join(ROOT, "package-lock.json");
  const nodeModules = join(ROOT, "node_modules");
  if (existsSync(nodeModules) && existsSync(join(nodeModules, "next"))) {
    log("Dependencies already installed.");
    return;
  }

  if (existsSync(lockfile)) {
    run("npm", ["ci"]);
  } else {
    run("npm", ["install"]);
  }
}

function printHelp() {
  log(`Start RealEST locally after a clone.

Usage:
  ./start.sh
  node scripts/start-app.mjs [options]

Options:
  --check              Validate Node + env, then exit
  --local-supabase     Start a local Supabase stack with Docker
  --no-local-supabase  Never start Docker/Supabase; require .env.local keys
  --no-install         Skip npm ci/install
  --no-verify          Do not HTTP-check the app after boot
  --port <n>           Listen port (default 3000)
  --timeout-ms <n>     How long to wait for the first HTTP response
`);
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) {
    printHelp();
    return 0;
  }

  log("RealEST start");
  log(`Repo: ${ROOT}`);

  if (!meetsNodeRequirement(process.versions.node)) {
    throw new Error(
      `Node.js ${MIN_NODE_MAJOR}+ is required. This shell has v${process.versions.node}.`,
    );
  }
  log(`Node v${process.versions.node}`);

  ensureEnvExample();

  let env = currentEnv();
  let issues = collectEnvIssues(env);

  const shouldStartLocalSupabase =
    !args.check &&
    (args.localSupabase ||
      (issues.missingRequired.length > 0 &&
        !args.noLocalSupabase &&
        commandExists("docker")));

  if (issues.missingRequired.length > 0 && shouldStartLocalSupabase) {
    if (!commandExists("docker")) {
      throw new Error("Docker is required for --local-supabase and was not found on PATH.");
    }
    env = mergeEnvSources(env, maybeStartLocalSupabase());
    issues = collectEnvIssues(env);
  }

  if (issues.missingRequired.length > 0) {
    if (!existsSync(ENV_LOCAL_PATH) && existsSync(ENV_EXAMPLE_PATH)) {
      writeFileSync(ENV_LOCAL_PATH, readFileSync(ENV_EXAMPLE_PATH));
      log(`Created ${ENV_LOCAL_PATH} from .env.example. Fill in the real keys.`);
    }
    throw new Error(missingKeysMessage(issues.missingRequired));
  }

  if (issues.missingRecommended.length > 0) {
    log(
      `Warning: recommended keys missing (${issues.missingRecommended.join(", ")}). Homepage can boot; some API routes will fail.`,
    );
  }

  if (args.check) {
    log("Env check passed.");
    return 0;
  }

  if (args.install) {
    installDependencies();
  }

  const resolved = await resolveListenPort(args.port, ROOT);
  if (resolved.action === "reuse") {
    const url = `http://127.0.0.1:${resolved.port}`;
    log(
      `This clone is already serving at ${url} (pid ${resolved.pid ?? "unknown"}).`,
    );
    log(startAppReadyLine(url));
    return 0;
  }

  if (resolved.reason === "other-repo" || resolved.reason === "occupied-unknown") {
    log(
      `Port ${args.port} is in use by pid ${resolved.pid ?? "unknown"} (${resolved.occupantCwd ?? "unknown cwd"}). Starting this clone on ${resolved.port}.`,
    );
  }

  const listenPort = resolved.port;
  const childEnv = {
    ...process.env,
    ...env,
    PORT: String(listenPort),
    NEXT_PUBLIC_APP_URL: `http://localhost:${listenPort}`,
    NEXT_PUBLIC_SITE_URL: `http://localhost:${listenPort}`,
    NEXT_TELEMETRY_DISABLED: "1",
  };

  log(`Starting Next.js on http://localhost:${listenPort}`);
  const child = spawn("npx", ["next", "dev", "--port", String(listenPort)], {
    cwd: ROOT,
    env: childEnv,
    stdio: ["inherit", "pipe", "pipe"],
  });

  let shuttingDown = false;
  const forward = (chunk, stream) => {
    stream.write(chunk);
  };
  child.stdout.on("data", (chunk) => forward(chunk, process.stdout));
  child.stderr.on("data", (chunk) => forward(chunk, process.stderr));

  const stop = (signal = "SIGTERM") => {
    if (shuttingDown) return;
    shuttingDown = true;
    if (child.exitCode == null) child.kill(signal);
  };

  process.on("SIGINT", () => stop("SIGINT"));
  process.on("SIGTERM", () => stop("SIGTERM"));

  const childFailed = new Promise((_, reject) => {
    child.on("exit", (code, signal) => {
      if (shuttingDown) return;
      reject(
        new Error(
          `Next.js exited before becoming ready (code=${code}, signal=${signal}).`,
        ),
      );
    });
  });

  const url = `http://127.0.0.1:${listenPort}`;
  if (args.verify) {
    await Promise.race([
      waitForHttp(url, { timeoutMs: args.timeoutMs }),
      childFailed,
    ]);
    log(startAppReadyLine(url));
    try {
      const homepage = await fetch(url, { redirect: "manual", cache: "no-store" });
      log(`Homepage HTTP ${homepage.status}`);
      if (homepage.status >= 500) {
        log(
          "The server is up, but the homepage returned 5xx. Check Supabase keys and the Next.js log above.",
        );
      }
    } catch (error) {
      log(`Homepage probe failed: ${error instanceof Error ? error.message : error}`);
    }
  } else {
    log(startAppReadyLine(url));
  }

  log(`Open ${url}`);
  const exitCode = await new Promise((resolve) => {
    child.on("exit", (code) => resolve(code ?? 1));
  });
  return exitCode;
}

main()
  .then((code) => {
    process.exit(code);
  })
  .catch((error) => {
    process.stderr.write(`${error instanceof Error ? error.message : error}\n`);
    process.exit(1);
  });
